dracutdevs/dracut

dracut.spec
This adds systemd-ask-password and systemd-sysctl motules to the spec file
It also alphabeticaly orders the newly introduced systemd based module
in the spec file.
To be merged after sdaskpw and sdsyctl modules have been merged.
Fixes #
=> fix: add systemd-ask-password and systemd-syctl modules to the spec file

dracut.spec
The directory name was changed in 16efdfa25c65c31acc97d91b7baf4f7bb4ea8510.
=> fix: update dbus module directory in spec file

test/TEST-30-ISCSI/test.sh
```
mke2fs 1.45.6 (20-Mar-2020)
Filesystem too small for a journal
Discarding device blocks:          done
Creating filesystem with 1024 1k blocks and 128 inodes
Allocating group tables: 0/1   done
Writing inode tables: 0/1   done
Writing superblocks and filesystem accounting information: 0/1   done
cp: error writing '/sysroot/usr/bin/bash': No space left on device
cp: error writing '/sysroot/usr/bin/grep': No space left on device
cp: error writing '/sysroot/usr/bin/ping': No space left on device
[…]
```
=> ci: more disk space for test 30 iscsi

dracut.cmdline.7.asc
```
asciidoc: WARNING: dracut.cmdline.7.asc: line 1115: nested inline passthrough
```
=> docs: fix dracut.cmdline.7

test/TEST-01-BASIC/test.sh, test/TEST-02-SYSTEMD/test.sh, test/TEST-03-USR-MOUNT/test.sh, test/TEST-04-FULL-SYSTEMD/test.sh, test/TEST-10-RAID/test.sh, test/TEST-11-LVM/test.sh, test/TEST-12-RAID-DEG/test.sh, test/TEST-13-ENC-RAID-LVM/test.sh, test/TEST-14-IMSM/test.sh, test/TEST-15-BTRFSRAID/test.sh, test/TEST-16-DMSQUASH/test.sh, test/TEST-17-LVM-THIN/test.sh, test/TEST-20-NFS/test.sh, test/TEST-30-ISCSI/test.sh, test/TEST-35-ISCSI-MULTI/test.sh, test/TEST-40-NBD/test.sh, test/TEST-50-MULTINIC/test.sh, test/TEST-60-BONDBRIDGEVLANIFCFG/test.sh
Because some of the CI tests fail randomly while grepping for the
test success marker, let's be specific of the file format grep will
search to eleminate all failure sources.
=> ci: force binary files for grep on disk images

modules.d/10i18n/module-setup.sh
Invalid space broke the creation of the keyboard subdirectories,
leading to a symbolic link
usr/share/consolefonts,consoletrans,keymaps,unimaps ->
/usr/lib/kbd/consolefonts,consoletrans,keymaps,unimaps
in the created initramfs.
With this fix the correct symlinks are created again:
usr/share/consolefonts -> /usr/lib/kbd/consolefonts
usr/share/consoletrans -> /usr/lib/kbd/consoletrans
usr/share/keymaps -> /usr/lib/kbd/keymaps
usr/share/unimaps -> /usr/lib/kbd/unimaps
=> fix(i18n): create the keyboard symlinks again

dracut-init.sh
A test of the form
if ! command; then
_ret=$?
...
return _ret
fi
does not capture the return code of `command`, but the negation of the return code, leaving _ret == 0. The test of this form in inst_multiple has been refactored to capture and return the right value.
=> fix:  proper return code for inst_multiple in dracut-init.sh

dracut.cmdline.7.asc, modules.d/95fcoe/lldpad.sh, modules.d/95fcoe/parse-fcoe.sh
fcoe: rename rd.nofcoe to rd.fcoe
The current name of this bool is kinda stupid. Based on the manpage
setting it to 0 turns off fcoe, which means that nofcoe=1 should mean
that it is on.
Let's just do the same thing as with rd.lvm=0, rd.luks=0,....
=> fcoe: rename rd.nofcoe to rd.fcoe

modules.d/35network-manager/module-setup.sh, modules.d/35network-manager/nm-config.sh, modules.d/35network-manager/nm-run.service, modules.d/35network-manager/nm-run.sh, modules.d/40network/netroot.sh
Sorry for the second pull request, but I no longer trust in local make check.
This is a slightly different approach, where we only start nm from the unit, but we keep other stuff in init queue.
In the current state, services that depend on network need to
use dracut hooks, since nothing with pull in the network
targets into the transaction.
In the future, it would be nice to provide developers on systemd-only
systems the possibility to not use dracut hooks at all, but simply put
normal systemd services into the initrd.
Also, some modules even right now depend on systemd ordering, like
cryptsetup, so let's make sure, that the ordering inside systemd work
properly as well.
Fixes #
=> fix(network-manager): run as a service if systemd module is present

modules.d/50drm/module-setup.sh
on my system (ThinkPad X201s) I have several modalias entries that are
empty:
/sys/bus/platform/devices/dock.0/modalias
/sys/bus/platform/devices/dock.1/modalias
/sys/bus/platform/devices/dock.2/modalias
executing the drm module setup thus results in the following errors
dracut-install: No SOURCE argument given
when calling dracut_instmods and hostonly mode is enabled.
Skip those entries, as there are no modules to load in this case
anyways.
Note: it is not sufficient to use [['s -s test (file size is greater
than zero), as all those files are 4096B if you stat them.
Fixes https://bugs.debian.org/982146
=> fix: skip empty modalias files in drm module setup

dracut.sh
There is no `fstab_lines_l` variable used before.
The `--include` option was turned into `++include` and therefore the
switch option is not reachable anymore.
=> fix(dracut.sh): remove unneeded variables

.packit.yml
This pull request adds the initial packit [1][2] support for fedora maintenance which
should get us started of automating the release process from upstream release to fedora.
This PR completes the first 2 steps in packit's onboarding process and is limited to rawhide ( so it should not break anything), the rest of the onboarding process needs to be completed by @haraldh as well as any fine tuning of packit. 
( I just put some sample entries there to get us started ).
1. https://packit.dev
2. https://packit.dev/docs/guide/
=> feat(github): adding packit support for fedora maintenance

dracut.sh
When a GZIP environment variable is set, this leads to various breakage:
In case 'pigz' is installed and GZIP is defined as a path, e.g.
/usr/local/bin/gzip, then dracut will fail with the following message:
~~~
pigz: abort: cannot provide files in GZIP environment variable
~~~
In case 'pigz' isn't installed and regular 'gzip' is used and GZIP is
defined as a path, e.g. /usr/local/bin/gzip, then the path will be
zipped and dracut will fail for no obvious reason.  Trying again, dracut
will then fail with following message:
~~~
gzip: /usr/local/bin/gzip.gz already exists;	not overwritten
~~~
In any case, GZIP environment should be unset to avoid breakage or
unwanted behaviour. This variable is anyway obsolescent, from gzip(1)
manpage.
Signed-off-by: Renaud Métrich <rmetrich@redhat.com>
This …
=> Harden dracut against GZIP environment variable

modules.d/90kernel-modules/module-setup.sh
On SUSE, there is no /lib/modules.d, only /usr/lib/modules.d.
Upstream-Bug: http://bugzilla.opensuse.org/show_bug.cgi?id=1180822
Reference: bsc#1180822
=> fix(kernel-modules): Optionally add /usr/lib/modules.d to initramfs

dracut.sh, modules.d/01fips/fips.sh, modules.d/80cms/cmssetup.sh, modules.d/90crypt/crypt-lib.sh, modules.d/90dmsquash-live/dmsquash-generator.sh, modules.d/90dmsquash-live/dmsquash-live-root.sh, modules.d/90livenet/livenet-generator.sh, modules.d/90mdraid/mdmon-pre-udev.sh, modules.d/95nbd/nbd-generator.sh, modules.d/95nfs/module-setup.sh, modules.d/99base/init.sh, modules.d/99shutdown/shutdown.sh, test/TEST-03-USR-MOUNT/create-root.sh, test/TEST-04-FULL-SYSTEMD/create-root.sh, test/TEST-11-LVM/test.sh, test/TEST-12-RAID-DEG/create-root.sh, test/TEST-14-IMSM/test.sh, test/TEST-17-LVM-THIN/test.sh, test/TEST-20-NFS/test.sh
Ensuring that directory creations dont trigger error if directory
previously existed as well as create parent directories if needed.
Majority of the code already does this, this takes care of the rest where it didn't.
=> fix: always use mkdir -p

.github/labeler.yml
There is no longer need to have pull requests labeled with the needs
review label since reviews are now mandatory on pull request.
Fixes #
=> chore(labeler): remove the needs review label

dracut.cmdline.7.asc, modules.d/35network-legacy/ifup.sh, modules.d/35network-legacy/parse-ip-opts.sh, modules.d/95nbd/nbd-generator.sh, modules.d/95nbd/nbdroot.sh, modules.d/95nbd/parse-nbdroot.sh, modules.d/99fs-lib/fs-lib.sh
For https://github.com/SFTtech/stiefelsystem we use NBD over IPv6-linklocal. This was not supported in dracut.
* Add v6 linklocal support for network module (already upstream in network manager)
* Add v6 support for NBD
* Some minor fixes discovered along the way
=> feat(nbd): support ipv6 link local nbds

modules.d/95udev-rules/module-setup.sh
Install `64-btrfs.rules` unconditionally to mark btrfs devices ready or not.
In case no `btrfs` kernel module is available in the initramfs, the device should not be ready.
Depends on: https://github.com/systemd/systemd/pull/18802
Fixes: https://github.com/dracutdevs/dracut/issues/947
=> fix(udev-rules): add btrfs udev rules by default

.packit.yml
Since packit is now working let's extend it to cover more releases.
With this config change,copr builds will happen on pull requests
for all fedora development branches and the next major RHEL release
( fedora-eln ) and on commits, copr builds will happen on all fedora
release and the next major RHEL release.
=> chore(.packit.yml): adding all fedora release + centos to packit

modules.d/90qemu/module-setup.sh
This adds support for virtio-mem devices, which provide a dynamic
amount of memory in a VM. Right now, the driver gets loaded and any
memory gets added to the system when loading the kernel module from disk.
While not strictly required to boot, we want to be able to
1) add virito-mem provided memory to the system early while booting up
2) add virtio-mem provided memory even when booting without a disk
3) add virtio-mem devices without adding actual memory in kdump
environments such that we can query things like:
a) is a certain PFN currently plugged in the hypervisor and, therefore,
should actually be read when creating a system dump. (kexec-tools
prepares the vmcore header, like on x86-64)
b) which ranges of a virtio-mem device are currently plugged in the
hypervisor and, therefore, …
=> qemu: include the virtio_mem kernel module

.github/workflows/lint.yml, .shellcheckrc, Makefile
This pull request `shellcheck` to the ci and checks every directory (and subdirs), which contains a `.shchkdir` file.
The `.shchkdir` file solution is temporary, until all of dracut is shellcheck error free and all  `.shchkdir` files will be removed at the end and the `luizm/action-sh-checker` shellcheck and shfmt github action will be used exclusively.
=> ci: add shellcheck

install/dracut-install.c
If a `kmod_module` is missing the `path`, it is `builtin`.
=> fix(install): handle builtin modules

modules.d/06dbus-broker/module-setup.sh
dbus-broker.service has a 'dbus.service' alias which is installed when the service gets enabled.
If the alias is not present in the initrd image, services requiring D-Bus in the initrd fail to start because they depend on dbus.service, which doesn't exist.
Therefore, enable the service to create the alias.
=> dbus-broker: enable the service

.packit.yml
Seems like there is a missing glib2 build in the pipeline, so
fedora-eln only fails, and therefore is of no use for us.
=> ci: disable fedora-eln for now

modules.d/99memstrack/memstrack-report.sh, modules.d/99memstrack/module-setup.sh
memstrack does not need to depend on `bash` but does on `systemd`.
Fixes #
=> fix(memstrack): correct dependencies

modules.d/90nvdimm/module-setup.sh
`_provider_dirs` should not have been quoted, because it should expand
to multiple arguments.
Just remove the whole variable and add those arguments.
Fixes: https://github.com/dracutdevs/dracut/issues/1273
=> fix(nvdimm): shellcheck regression

modules.d/90multipath/module-setup.sh, modules.d/90multipath/multipathd-stop.sh
A shellcheck regression quoted `HARD` in
```shell
kill "$HARD" "$pid" > /dev/null 2>&1
```
which would error on an empty "HARD".
Instead of fixing this, use `pkill` instead and also add it to the
non-optional list of binaries to install, which was revised also.
Fixes: https://github.com/dracutdevs/dracut/issues/1275
=> fix(multipath): revise multipathd-stop

modules.d/91zipl/module-setup.sh
There is no grub2 dracut module.
=> fix(zipl): don't depend on grub2

modules.d/35network-manager/nm-lib.sh
=> fix(network-manager): nm-lib.sh does not require bash

modules.d/95lunmask/parse-lunmask.sh
`parse-lunmask.sh` is not a bash script
and dash doesn't understand `read -a`.
Revert to the initial code.
Fixes: https://github.com/dracutdevs/dracut/issues/1271
=> fix(lunmask): shellcheck regression

modules.d/35network-manager/nm-run.service
Otherwise nm-run.service will run only in basic.target, which is too
late in the initramfs.
=> fix(network-manager): no default deps for nm-run.service

modules.d/40network/net-lib.sh
Commit e25c536c70bab4a4d6 introduced a regression in iface_has_carrier
due to unclear variable naming.
=> fix(network): correct regression in iface_has_carrier

modules.d/99base/dracut-lib.sh
Patch 2fabaaa62dcfd31e593ca changed the behaviour for `dash`
under the assumption, that dash does not take parameters for `.` aka
`source`. Although this is true, the original positional parameters of
the `source_all` function are still in place, so everything is
fine with the old way of sourcing.
=> fix(base): source hooks without exec

modules.d/98dracut-systemd/dracut-cmdline.sh
Commit 3532978de04c7 introduced a regression, where the `root` could be
`root=block:block:/dev/foo`.
=> fix(dracut-systemd): regression on root=block:

modules.d/95nbd/nbdroot.sh
`$opts`, `$preopts` and `$nbdport` shouldn't have been quoted as they
can expand to multiple options.
Fixes: https://github.com/dracutdevs/dracut/issues/1270
=> fix(nbd): shellcheck regression

dracut-functions.sh
This unquated regex could be splitted into two arguments and sed will
not work. I've see giving error of wrong arguments being used on my
desktop.
Fix a word splitting issue.
Fixes #
=> fix: fix word splitting issue for sed in get_ucode_file

dracut.sh
When omitting a module from the command line via -o or --omit
it's expected that it behaves in the same manner as adding a module from the
command line as in it does not overwrite existing omissions of other modules in
configuration file(s).
This should fix #1341
Fixes #
=> fix(dracut.sh): omission is an addition to other omission in conf files

modules.d/10i18n/module-setup.sh
On system that doesn't have either consolefonts, consoletrans, keymaps,
or unimaps, "kbddir" is empty, thus the followed installation will
broken with errors like:
cp: cannot stat '/consolefonts/*': No such file or directory
Let's report the checks as failure if "kbddir" is empty.
Signed-off-by: Đoàn Trần Công Danh <congdanhqx@gmail.com>
Fixes #
=> fix(i18n): skip if data is missing

dracut-logger.sh
There are a bunch of `logger: unknown facility name: --user` errors
during a run. This is because logger is getting passed something like:
```
logger -p --user.info
```
Where it should be something like:
```
logger -p user.info
```
=> fix(dracut-logger.sh): double dash trigger unknown logger warnings during run

modules.d/35network-manager/nm-run.service
If teaming is set up via NetworkManager we don't want systemd to take
down the userspace teamd process when NetworkManager quits. `KillMode=process`
will allow it to leave those processes behind.
This is fallout from the change to run NetworkManager via systemd (c17c5b7).
With `KillMode=process` we get something like:
```
sh-5.1# journalctl -u nm-run -o cat | tail
<info>  [1618411262.7030] quitting now that startup is complete
<info>  [1618411262.7030] device (team0): carrier: link connected
<info>  [1618411262.7033] device (team0): team port ens2 was released
<info>  [1618411262.7033] device (team0): team port ens3 was released
<info>  [1618411262.7033] manager: NetworkManager state is now CONNECTED_SITE
<info>  [1618411262.7034] exiting (success)
nm-run.service: Deactivated …
```
=> fix(network-manager): nm-run.service: don't kill forked processes

modules.d/35network-manager/nm-lib.sh, modules.d/35network-manager/nm-run.service, modules.d/35network-manager/nm-run.sh
```
commit 0152fa88c9a155ac3e34c575da6c7ed2134b32f0
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Tue Apr 13 11:45:35 2021 -0400
network-manager: use /run/NetworkManager/initrd/neednet in initqueue
We don't want to start NetworkManager if networking is not needed.
Right now nm-config.sh lays down /usr/lib/dracut/hooks/initqueue/finished/nm.sh
which will cause the initqueue to run. If nothing exists in
/usr/lib/dracut/hooks/initqueue/finished/ then it will short circuit and
the initqueue won't run anything. But what if something else needed
something to run in the initqueue? nm-run.sh would still get started,
even though /usr/lib/dracut/hooks/initqueue/finished/nm.sh didn't exist.
In this case let's just trigger off of /run/NetworkManager/initrd/neednet
like we are doing in the systemd …
```
=> fix(network-manager): only run NetworkManager if rd.neednet=1 

modules.d/35network-manager/initrd-no-auto-default.conf, modules.d/35network-manager/module-setup.sh, modules.d/35network-manager/nm-config.sh, modules.d/35network-manager/nm-initrd.service, modules.d/35network-manager/nm-lib.sh, modules.d/35network-manager/nm-wait-online-initrd.service
This is version 2 of #927. I did only some basic testing on it; I plan to do more tests in the next days. In the meantime, comments are welcome.
This commit changes how NM is started inside the initrd. Instead of running NM in the special `--configure-and-quit=initrd` mode, which sets up network and quits, start it as a daemon.
This has multiple advantages. First, we no longer need to run NM in a special mode that requires additional code and maintenance. NetworkManager works exactly as in the real root.
One problem of the current configure-and-quit approach is that once NM has quit, dynamic addresses can expire if the initrd setup takes longer than the DHCP lease interval or than the IPv6 address lifetime. Running NM as a service
solves this problem.
Now NM runs with D-Bus support and …
=> network-manager: run as daemon with D-Bus

test/TEST-30-ISCSI/create-client-root.sh, test/TEST-30-ISCSI/test.sh, test/TEST-35-ISCSI-MULTI/create-client-root.sh, test/TEST-35-ISCSI-MULTI/test.sh
While creating the striped md raid0 sometimes this error occures:
```
mdadm: Defaulting to version 1.2 metadata
mdadm: RUN_ARRAY failed: Unknown error 524
Failed to clear hint file.
Device /dev/md0 not found.
Powering off.
```
Add debug output with the size of the disks.
=> fix(TEST ISCSI): try to debug md error 524

modules.d/06dbus-daemon/module-setup.sh
Don't hard exit in `check()`. The transaction logic only checks if it
should/can include the module. Just return `255` and the `dbus` meta
module will pick its dependency.
Fixes #
=> fix(dbus-daemon): only error out in install()

test/TEST-35-ISCSI-MULTI/99-idesymlinks.rules, test/TEST-35-ISCSI-MULTI/client-init.sh, test/TEST-35-ISCSI-MULTI/create-client-root.sh, test/TEST-35-ISCSI-MULTI/create-server-root.sh, test/TEST-35-ISCSI-MULTI/server-init.sh, test/TEST-35-ISCSI-MULTI/test.sh, test/test-functions
`qemu_add_drive_args` can be used to generate arguments to specify disks for a qemu machine (`-M q35`).
This is mostly useful to address those raw disks via `/dev/disk/by-id`, because due to parallel probing in the kernel `/dev/sd*` can point to anything.
Due to parallel probing of the linux kernel `/dev/sd*` can't be used to reliably address a hard disk. This can be seen by the many spurious failures of the dracut CI, where `mdadm` failed with error 524 or tests failed due to the success marker message written to the wrong disk.
* don't rely on `/dev/sd*` but use disk ids and `/dev/disk/by-id/ata-disk_<name>`
* specify the exact qemu machine architecture `-M q35` needed for the
disk ids. A later patch will move this to `run-qemu`, when all tests are converted
* due to `-M q35` the …
=> ci: use disk ids for TEST 35 ISCSI MULTI

modules.d/95nbd/nbdroot.sh, modules.d/95nbd/parse-nbdroot.sh, test/TEST-40-NBD/test.sh
* Correct the systemd generated sysroot.mount unit with the options
received by the DHCP request and do a `daemon-reload`.
* Inject the `nbd-client -check /dev/nbd0` in the finished initqueue.
* Reactivate the NBD tests and prepare them for NetworkManager tests.
Fixes #
=> fix(nbd): make nbd work again with systemd

modules.d/00systemd/module-setup.sh, modules.d/01fips/fips.sh, modules.d/95nbd/nbdroot.sh
Came across some old systemd/udev version checks in modules so I removed those and what followed since it should not be needed anymore + it's somewhat weird if vendors/distributions are shipping old systemd versions with newer dracut....
Fixes #
=> fix: remove old systemd/udev version checks

dracut.sh
Adding modulesload modulesloadconfdir global variables
Fixes #
=> fix(dracut.sh): add global vars for modules-load

modules.d/90kernel-modules/module-setup.sh
The watchdog module pulls in the device specific watchdog if that
module is enabled, but in the case where we need a generic initrd
we don't get all watchdog drivers which means if we have a watchdog
enabled for that usecase it may get kicked too late in the boot
process so we need the drivers in the initrd for the generic case too.
Signed-off-by: Peter Robinson <pbrobinson@gmail.com>
Fixes #
=> 90kernel-modules: add watchdog drivers for generic initrd

modules.d/00systemd/module-setup.sh
Adding /etc/hosts and /etc/nsswitch.conf to the hostonly install section.
After careful consideration the systemd module is the most logical place to have this. 
Fixes #
=> fix(systemd): include hosts and nsswitch.conf in hostonly mode

modules.d/35network-manager/nm-lib.sh
Create the `/run/NetworkManager/initrd` directory before creating
`/run/NetworkManager/initrd/neednet`. Somehow on Fedora 32 this
directory is missing, when the script is running.
This fixes all NetworkManager tests for Fedora 32.
Fixes #
=> fix(network-manager): create /run directories

modules.d/01systemd-ask-password/module-setup.sh, modules.d/01systemd-coredump/module-setup.sh, modules.d/01systemd-repart/module-setup.sh, modules.d/01systemd-sysctl/module-setup.sh, modules.d/01systemd-sysusers/module-setup.sh
Depending on systemd meta module causes circular dependency,
prevents the existance of multiple systemd based meta modules
and is redunant.
Fixes #
=> fix(systemd-modules): remove dependency on systemd meta module

dracut.spec, modules.d/01systemd-ac-power/99-initrd-power-targets.rules, modules.d/01systemd-ac-power/initrd-on-ac-power.target, modules.d/01systemd-ac-power/initrd-on-battery-power.target, modules.d/01systemd-ac-power/module-setup.sh
Introducing the systemd-ac-power module
This module introduces two new targets which are run based on the power state in initrd which users/projects/products can then use when running on ac or battery power.
A typical service type unit to be used with this would look like this when on AC
```
[Unit]
Description=Run When I'm On AC Power In Initrd 
[Service]
...
[Install]
WantedBy=initrd-on-ac-power.target
```
And this when on battery
```
[Unit]
Description=Run When I'm On Battery Power In Initrd 
[Service]
...
[Install
WantedBy=initrd-on-battery-power.target
```
If the situation requires it, a belt and suspenders approach for the type units can be achieved by adding the `ConditionACPower=` with true or false depending on the target.
=> feat(systemd-ac-power): introducing the systemd-ac-power module

modules.d/99img-lib/img-lib.sh, modules.d/99img-lib/module-setup.sh
The system currently throws numerous nasty warning messages during
the boot, about ignored null bytes in input.
This patch adds a filter to the dd command, to filter these null
bytes out, and thus to prevent these warning messages.
Signed-off-by: Lev Veyde <lveyde@redhat.com>
- [V] I have tested it locally
Fixes #
This patch fixes the warning messages about the "ignored null byte in input" during the boot.
=> fix(img-lib): Fixed the "ignored null byte in input" issue

modules.d/02systemd-networkd/module-setup.sh, modules.d/40network/module-setup.sh
Let's make systemd-networkd a proper network provider which should fix #737
Node that this PR adds dependencies on the dbus module ( since it provides networkd dbus files ) as well as sysusers ( which replaces the grep passwd section from the existing module ) and should not be merged until I have provided the rest of the modules hostnamed, timesyncd,resolved etc. ( read as do not enable automerge  ) which will provide the libraries in the existing module.  
Fixes #
=> fix(systemd-networkd): make systemd-networkd a proper network provider 

modules.d/40network/module-setup.sh
Use globalvariable for systemd networkd instead of path
Pointed out by @shaba here 
https://github.com/dracutdevs/dracut/commit/ea779750c371102c04252b48f1b7d9c7ece7cf93#r49856218
Fixes #
=> fix(network): use global variable for sdnetworkd instead of path

modules.d/35network-manager/nm-wait-online-initrd.service
With Fedora 32, only the command line option works for `nm-online`.
Fixes #
=> fix(network-manager): set timeout via command line option

modules.d/01systemd-coredump/module-setup.sh, modules.d/01systemd-repart/module-setup.sh, modules.d/01systemd-sysctl/module-setup.sh, modules.d/01systemd-sysusers/module-setup.sh
Fixing quotes around *.conf entries in systemd modules
Fixes #
=> fix: quotes in systemd modules

modules.d/95iscsi/module-setup.sh
Only rely on socket activation. This speeds up in case iscsi isn't used
and also prevents failures, where iscsiuio stopping somehow disables
iscsi.
Fixes #
=> fix(iscsi): only rely on socket activiation

dracut.sh
Currently when dracut search for btrfs device used for initramfs, it
assumes the mount points passed in with "--mount" are all mounted with
given mount path. If user want the device to be mounted to a different
location in initramfs, this will not be true.
eg. with "--mount '/dev/mapper/vol /sysroot btrfs rw,relatime,subvolid=256,subvol=/root'"
and having '/dev/mapper/vol' currently mounted on '/', will raise an
error:
ERROR: cannot access '/sysroot': No such file or directory
So search for actual mount point of given device.
=> fix: search for btrfs devices from actual mount poiont

test/TEST-30-ISCSI/server-init.sh, test/TEST-30-ISCSI/test.sh, test/TEST-35-ISCSI-MULTI/server-init.sh, test/TEST-35-ISCSI-MULTI/test.sh
Test for `pidof tgtd` and not the shell background jobs.
Spurious ISCSI CI test failures.
=> test(ISCSI): fix the watchdog loop

modules.d/95iscsi/module-setup.sh
Since Fedora 34, iscsid.service requires:
- iscsi-init.service
- iscsi-shutdown.service
- a non-empty /var/lib/iscsi/nodes/.dracut
=> fix(iscsi): add iscsid.service requirements

modules.d/35network-legacy/dhclient.conf
Adding the following commonly used options to dhclient.conf
- netbios-name-servers
- netbios-scope
- ntp-servers
- dhcp6.domain-search
- dhcp6.fqdn
- dhcp6.name-servers
- dhcp6.sntp-servers
Fixes #
=> fix(network-legacy): add missing options to dhclient.conf

modules.d/90multipath/multipathd.service
fix(multipath): stop multipath before udev db cleanup
All device-mapper based devices, including device-mapper-multipath,
do reuse the udev db from the initramfs after switching to the root fs.
Therefore device-mapper devices have to be correctly initialized before
the udev daemon is stopped, to have the correct entries in the udev db.
See also https://bugzilla.redhat.com/show_bug.cgi?id=1949076
Fixes #
=>  fix(multipath): stop multipath before udev db cleanup

modules.d/40network/module-setup.sh
dracut-install triggers "ERROR: installing '/usr/lib/wicked/bin/*'"
when find_binary is being used to determine if wicked is installed
so let's just check for the wicked type service unit instead.
Fixes #
=> fix(network): use wicked unit instead of find_binary

dracut.spec, modules.d/01systemd-udevd/module-setup.sh
Introducing the systemd-udevd module. 
This module includes the current upstream rules and solves a bunch of `Failed to run builtin 'hwdb $foo'` I noticed when running dracut and systemd in debug mode and brings udev alive in the initrd so it seems we have been missing a few potentially essential rules.  We might want to add global variables for the udev directory's
- [X ] I have tested it locally
Fixes #
=> feat(systemd-udevd): introducing the systemd-udevd module

dracut.sh
Adding missing global variables for udev
udevconfdir --> /etc/udev
udevrulesdir --> /usr/lib/udev/rules.d
udevrulesconfdir --> /etc/udev/rules.d
Fixes #
=> fix(dracut): adding missing globalvars for udev

.github/workflows/labels.yml
With the event called pull_request_target added to GitHub Actions, the
cron job can be removed.
See:
https://www.jclem.net/posts/labeling-prs-on-public-github-repositories
=> ci: remove label cron job

modules.d/01systemd-udevd/module-setup.sh
Switch to using the recently merged udev global variables. 
Fixes #
=> fix(systemd-udev): use global vars instead of fixed path

modules.d/35network-legacy/module-setup.sh, modules.d/35network-manager/module-setup.sh, modules.d/95udev-rules/module-setup.sh, test/TEST-30-ISCSI/test.sh
Removing sourcing of network link files from the udev-rules module.
What always should be included should be placed in the systemd-network
module and other modules that provide/require spesific link files
should add them, themselves via their relevant include section.
Fixes #
=> fix(udev-rules): remove sourcing of network link files

modules.d/01systemd-sysusers/module-setup.sh
This has been tested along with #1417, #1418, #1419 and with the entire install section of udev-rules module commented out. 
The sd-udevd module correctly detects and loads all it's included udev files. 
The sd-sysusers  correctly creates all users/groups for the included rules file in sd-udevd.
The sd-tmpfiles correctly creates everything on the host as well. 
Afaikt now with sd-udevd completed systemd based initrd should no longer have to require the udev-rules module in other words it can be cleaned up and left for legacy/alternative init system to strictly use.
Fixes #
=> fix(systemd-sysusers): misc fixes and cleanup

test/run-qemu
E.g. `uname -i` does not work in Arch Linux containers.
=> test: use `uname -m` to determine qemu-system

Makefile
On non-rpm distributions this does not make sense.
Fixes #
=> chore: skip rpmbuild, if there is no rpmbuild installed

dracut-initramfs-restore.sh
Fallback to /lib/modules/$(uname -r)/initrd, if present and all other
files don't exist.
Fixes #
=> feat: also restore the initramfs from /lib/modules

modules.d/90crypt/module-setup.sh
Just install all `=crypto` drivers in the generic initramfs, because who
are we to decide which combinations are allowed in current and future
`cryptsetup`. We only could install blacklist filter in the future, if
there are modules, which are definetely not used and are huge in size.
Fixes #
=> fix(crypt): install all crypto modules in the generic initrd

dracut-init.sh
This solves all issues, where builtin kernel modules are not recognized
as such.
Fixes: https://github.com/dracutdevs/dracut/issues/1146
Fixes: https://github.com/dracutdevs/dracut/issues/1099
=> fix: add `modules.builtin.modinfo` to the initramfs

dracut.sh, modules.d/90kernel-modules/module-setup.sh
This is important for running `depmod` in the initrd.
=> fix: install all depmod relevant configuration files

dracut-init.sh
Let's also resolve the compiled in aliases to builtin modules.
=> fix: include `modules.builtin.alias` in the initramfs

test/TEST-20-NFS/test.sh
`dhclient` on Arch does not understand the `--timeout` parameter.
`/etc/virc` does not need to be installed in tests. This is a debugging
leftover.
=> test(NFS): let it run in an Arch container

.github/workflows/lint.yml, dracut.sh, modules.d/35network-manager/module-setup.sh, modules.d/98integrity/evm-enable.sh
The bump of removed the `-d` option for `shfmt`. Readd it until upstream
is fixed.
See also:
https://github.com/luizm/action-sh-checker/issues/44
=> style: make indent and let shfmt fail again

dracut-init.sh, dracut.sh, install/dracut-install.c
Modern Linux kernels support zstd-compressed modules, which was added
by commit 73f3d1b48f50 ("lib: Add zstd modules").
Commit c3d7ef377eb ("kbuild: add support for zstd compressed modules")
added support of compressing modules with zstd to kernel Makefiles.
libkmod >= 28 built with libzstd is also required.
P.S. Support of decompressing zstd-compressed /lib/firmware seems to be missing in dracut-install, I did not try.
=> Support ZSTD-compressed kernel modules

dracut-functions.sh, dracut.sh
On systems with a large number of devices (1000 or so), usually multipath devices,
dracut can spend a lot of time stat'ing the devices to collect the
major/minor numbers, leading to huge slowness rebuilding the initramfs
when stat'ing devices is slow (seen with oracleasm file systems in
particular).
This commit implements a basic cache stored in a file under
DRACUT_TMPDIR storing the major:minor corresponding to the specified
device.
Reproducer: create N loopback devices used as a LVM extension to volume
group hosting the root file system
~~~
truncate -s 10m devices/$i; losetup loop$i devices/$i
done
~~~
With standard code (tested with RHEL8.3 dracut):
~~~
2440
~~~
With this code:
~~~
205
~~~
- [N/A] I have reviewed and updated any documentation if relevant
- [N/A] I am providing new code …
=> fix(dracut-functions): implement a cache for get_maj_min

modules.d/99base/module-setup.sh
Setting `DEBUG_MEM_LEVEL` in the build phase prevents
`setmemdebug()` to call `getargnum`, which would use `dracut-getarg`
in the initrd runtime phase.
No more:
```
modules.d/99base/dracut-lib.sh: line 217: dracut-getarg: command not found
```
=> fix(base): suppress calls to getarg in build phase

dracut.sh, man/dracut.8.asc, man/dracut.conf.5.asc
Gummiboot was merged into systemd and official became systemd-boot in 2015 ( 6 years ago )
and no longer was being maintained as Gummiboot from that point.
It's safe to say distribution should have migrated to sd-boot by now so let's deprecate
it.
Fixes #
=> fix: deprecate gummiboot

test/container/Dockerfile-Arch, test/container/Dockerfile-Fedora-33, test/container/Dockerfile-Fedora-34, test/container/Dockerfile-Fedora-latest
for `/etc/profile.d/dracut-test.sh`
Fixes #
=> ci: don't use `rpm` to determine the kernel version

test/container/Dockerfile-Fedora-33, test/container/Dockerfile-Fedora-34, test/container/Dockerfile-Fedora-latest, test/container/Dockerfile-OpenSuse-latest
pigz speeds up things considerably. Although pigz is already installed
by default, explicitely adding it makes sure, it will not disappear
unnoticed.
Fixes #
=> ci: ensure pigz is installed in the CI containers

modules.d/99fs-lib/module-setup.sh
Noticed that ext3 is still being used in the wild so let's add it to the crc32c list
so downstream does not have to carry a patch for it.
Fixes #
=> fix: adding crc32c for ext3

modules.d/45url-lib/url-lib.sh
Fixes: 8e84fa726 ("fix(url-lib): shellcheck for modules.d/45url-lib")
Behaviour introduced by that commit made the following to be run:
`curl "--globoff --location --retry 3 --fail --show-error" http://192.168.1.173:8000/test.ks`
instead of:
`curl --globoff --location --retry 3 --fail --show-error http://192.168.1.173:8000/test.ks`
This broke downloading kickstart file in anaconda-dracut.
=> fix(url-lib): fix passing args

modules.d/35network-manager/module-setup.sh, modules.d/35network-manager/nm-lib.sh
=> fix(network-manager): cope with distributions not using `libexec`

dracut.sh
Results in `usr/lib64 -> ..//usr/lib` for Arch Linux otherwise.
Fixes #
=> fix(dracut): prevent symbolic links containing `//`

src/util/util.c
This pull request fixes a - very minor - issue that `dracut-util` emits an error mesage without a trailing newline which looks quite ugly.
The other error I attempted to fix became worse with my patch so I removed it again. I will file an issue instead.
=> dracut-util: print error message with newline

modules.d/99base/dracut-dev-lib.sh, modules.d/99base/dracut-lib.sh, modules.d/99base/module-setup.sh, test/TEST-01-BASIC/test.sh, test/TEST-02-SYSTEMD/test.sh, test/TEST-03-USR-MOUNT/test.sh, test/TEST-04-FULL-SYSTEMD/test.sh, test/TEST-10-RAID/test.sh, test/TEST-11-LVM/test.sh, test/TEST-12-RAID-DEG/test.sh, test/TEST-13-ENC-RAID-LVM/test.sh, test/TEST-14-IMSM/test.sh, test/TEST-15-BTRFSRAID/test.sh, test/TEST-16-DMSQUASH/test.sh, test/TEST-17-LVM-THIN/test.sh, test/TEST-20-NFS/test.sh, test/TEST-30-ISCSI/test.sh, test/TEST-35-ISCSI-MULTI/test.sh, test/TEST-40-NBD/test.sh, test/TEST-50-MULTINIC/test.sh, test/TEST-98-GETARG/test.sh
To share the `wait_for_dev` function and use it without side effects on
install time, split out the needed functions in an extra library.
Fixes: https://github.com/dracutdevs/dracut/issues/1494
=> fix(base): split out `dracut-dev-lib.sh`

dracut.sh
Don't try to `mknod` by setting DRACUT_NO_MKNOD.
Don't try to `cp` extended attributrs by setting DRACUT_NO_XATTR.
Fixes #
=> feat(dracut.sh): detect running in a container

modules.d/99base/dracut-dev-lib.sh, modules.d/99base/module-setup.sh
```
dracut-dev-lib.sh: line 92: str_replace: command not found
dracut-dev-lib.sh: line 98: /var/tmp/dracut.sabKZg/initramfs/initqueue/finished/devexists-.sh: No such file or directory
dracut-dev-lib.sh: line 83: /var/tmp/dracut.sabKZg/initramfs/emergency/80-.sh: No such file or directory
```
Fixes #
=> fix(base): add missing `str_replace` to `dracut-dev-lib.sh`

modules.d/99squash/init-squash.sh, modules.d/99squash/module-setup.sh
It is possible that user setup some early mount in the rootfs even
earlier, so just be more robust and cover that case too.
Fixes #
=> fix(squash): don't mount the mount points if already mounted

src/install/dracut-install.c
If --kerneldir is not specified, use /lib/modules/$(uname -r).
Fixes #1505
=> fix(install): sane default --kerneldir

dracut.sh
Otherwise the output is cluttered with:
```
Mode:           real
Files:          1364
Linked:         5 files
Compared:       0 xattrs
Compared:       384 files
Saved:          12.84 KiB
Duration:       0.052674 seconds
```
Fixes #
=> fix(dracut): pipe hardlink output to `dinfo`

dracut-functions.sh
If `get_maj_min_cache_file` is unset `get_maj_min()` would error out.
Fix it to work without a cache file set.
Fixes #
=> fix(dracut-functions): get_maj_min without get_maj_min_cache_file set

src/install/dracut-install.c
If not specified, use /lib/firmware.
Not sure if this is a feature or a fix... I can change the commit title if necessary.
=> feat(install): add default value for --firmwaredirs

src/install/dracut-install.c
There are log_error() and log_debug() calls in parse_argv().
=> fix(install): configure logging earlier

modules.d/90crypt/cryptroot-ask.sh
Fixes a regression that prevents unlocking of a luks volume with a key file using the 90crypt module.
The reason for the regression is the incorrectly quoted variable $cryptsetupoptions that can contain multiple arguments separated by spaces.
* Remove quotes from $cryptsetupopts in 90crypt module.
Fixes #1528
=> Remove quotes from cryptsetupopts in 90crypt module

modules.d/99squash/module-setup.sh
Also install umount binary, make it possible to cleanup squash overlay
mounts. This is useful for other tools reusing the dracut initramfs built
with squash module enabled.
=> feat(squash): install umount util

modules.d/35network-manager/nm-initrd.service
Otherwise units with `After=network.target` won't have any effect.
=> fix(network-manager): pull in network.target in nm-initrd.service

src/install/dracut-install.c
Spotted when reconfiguring LGTM for RHEL 9 dracut repo.
/cc @lnykryn 
LGTM link: https://lgtm.com/projects/g/redhat-plumbers/dracut-rhel9/snapshot/9bfa5beea1b251d28deaae948f4bce12d45b1abe/files/src/install/dracut-install.c?sort=name&dir=ASC&mode=heatmap#L1452
=> fix(install): add a missing ret value assignment

modules.d/90multipath/module-setup.sh
Include additional multipath configuration files even if they are placed in a non-default location.
=> fix(multipath): get config. dir from configuration

modules.d/01fips/fips.sh, modules.d/01fips/module-setup.sh
On s390x, the `BOOT_IMAGE` karg injected by the bootloader is not a path
to the kernel image, but rather an integer describing the index of the
menu entry selected. Because of the way the s390x bootloader works,
there is no information retained about e.g. the path of the kernel that
was loaded.
This causes issues for the FIPS code which assumes that `BOOT_IMAGE` is
a path to the kernel image to derive the HMAC path. In non-OSTree
systems, this ends up working anyway, because the kernel is located at
the root of the boot partition.  In OSTree systems, this is not the
case. However, OSTree systems use BLS configs, and they are named in
reverse order of precedence (i.e. menu ordering). So from the
`BOOT_IMAGE` integer, we can figure out which BLS entry was selected.
Add some code to do just …
=> fix(fips): handle s390x OSTree systems

modules.d/99squash/module-setup.sh
Don't use absolute path, or it may resolve to wrong files after unpack
the initramfs to a subpath on a running system.
=> fix(squash): create relative symlinks

modules.d/35network-manager/module-setup.sh
Previously when NM was run without dbus then teaming would come
up appropriately [1], but now that dbus exists we also need to
include some supporting infrastructure to allow for it to work
again.
[1] https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/d689380cfc5734a29b1302d68027190e1a606265
=> fix(network-manager): support teaming under NM+systemd

dracut.sh
While including a directory using '--include' option, the file and
subdirectory names that begin with '.' are not included. Also, dracut
throws a warning message when a subdirectory is empty or only has
files or subdirectories that begin with '.'.
For example, while trying to include /tmpdata directory with the
below tree:
```  # tree -a /tmpdata
/tmpdata
├── .anothertestdir
├── testdir
│   └── .testsubdir
└── .testfile
```
dracut throws the below warning message:
```
cp: cannot stat '/tmpdata/testdir/*': No such file or directory
#
```
and this is how the included /tmpdata directory tree looks:
```
root
└── testdir
```
No file or directory beginning with '.' is included & also, copying
/tmpdata/testdir reported "No such file or directory" warning. Using
'.' instead of '*' in the below …
=> fix(dracut.sh): handle symlinks and files beginning with '.' appropriately while using '-i' option

modules.d/91crypt-gpg/crypt-gpg-lib.sh
Sometimes I forget to insert the gpg card before the first password prompt is printed. 
If the gpg card is not inserted before the `--card-status` command is executed then the public key is not linked with the card. Therefore, the LUKS partition cannot be decrypted. To solve this, the `--card--status` command is executed on each try.
Fixes #
=> fix(crypt-gpg): Execute --card-status on each try

modules.d/45url-lib/url-lib.sh
Currently, nfs_fetch_url() makes just one pre-pivot hook for umount. 
When nf_fetch_url() is called multiple times, it's always overwritten by the latter one.
As a result, some NFS remains without cleanup by umount. 
This PR is to make a separate hook per NFS mount in nfs_fetch_url().
Fixes #
=> fix(url-lib): make pre-pivot hook separetely per nfs mount

modules.d/35network-manager/nm-initrd.service
We get a nice warning about it being deprecated:
```
systemd-udev-settle.service is deprecated. Please fix nm-initrd.service not to pull it in.
```
The service is deprecated because its purpose was to wait for the
discovery of all hardware, but it didn't guarantee that (see the
systemd-udev-settle man page).
NM now runs as an independent service and can deal with devices showing
up at any point, but it does need udev to be started. For now just
Want/After systemd-udev-trigger.
=> fix(network-manager): don't pull in systemd-udev-settle

modules.d/95qeth_rules/module-setup.sh
On s390x KVM machines, the follow errors occurred,
```
$ kdumpctl rebuild
kdump: Rebuilding /boot/initramfs-4.18.0-321.el8.s390xkdump.img
/usr/lib/dracut/modules.d/95qeth_rules/module-setup.sh: line 13: /sys/devices/qeth/*/online: No such file or directory
/usr/lib/dracut/modules.d/95qeth_rules/module-setup.sh: line 13: /sys/devices/qeth/*/online: No such file or directory
```
because s390x KVM uses virtual devices and /sys/devices/qeth/*/online
doesn't exist. Eliminate this error by checking the existence
beforehand.
Fixes #
=> fix(qeth_rules): check the existence of /sys/devices/qeth/*/online beforehand

src/install/dracut-install.c
Fix potential memory leaks in two locations and use
_exit(EXIT_FAILURE) if asprintf(&abspath, ...) fails.
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
Be more consistent in exiting if `asprintf()` fails, i.e. exit the same way as other code paths using `asprintf()`
Fix memory leaks in these cases:
- `lstat()` says the file does not exist
- recursion happens because `abspath` is a symlink
Fixes #
=> fix(dracut-install): tweaks to get_real_file()

modules.d/99squash/module-setup.sh
When running kdump on PowerPC, the following bug is hit:
[    0.391629] Freeing unused kernel memory: 5568K
[    0.391634] This architecture does not have kernel memory protection.
/bin/sh: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
[    0.392214] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
[    0.392214]
[    0.392223] CPU: 6 PID: 1 Comm: init Not tainted 4.18.0-319.el8.ppc64le #1
[    0.392228] Call Trace:
[    0.392234] [c00000000c703c10] [c000000008ecb94c] dump_stack+0xb0/0xf4 (unreliable)
[    0.392243] [c00000000c703c50] [c000000008167324] panic+0x148/0x3c4
[    0.392249] [c00000000c703cf0] [c000000008170474] do_exit+0xcd4/0xd40
[    0.392255] [c00000000c703dc0] [c0000000081705b0] …
=> 99squash: keep ld cache under initdir

modules.d/98dracut-systemd/dracut-cmdline-ask.service
systemd-vconsole-setup.service may fail if the user specifies a missing keymap,
see [1,2,3], or font. This is unfortunate, but the system should not refuse
boot. It is better to continue, possible without the desired font or keymap.
All other systemd services that depend on systemd-vconsole-setup.service do so
without a hard Requires=.
(In particular, systemd-vconsole-setup internally will try to do as much setup
as possible, and will load the font even if it cannot load the keymap and vice
versa.)
[1] https://fedoraproject.org/wiki/Common_F34_bugs#kbd-legacy-media
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1955162
[3] https://bugzilla.redhat.com/show_bug.cgi?id=1955793
=> dracut-systemd: do not use Requires for vconsole-setup.service

modules.d/90kernel-modules/module-setup.sh
Include the same extra modules for ARM also on RISC-V and add drivers/mmc/host
and drivers/spi to the list.
=> fix(kernel-modules): add more modules on RISC-V

modules.d/99base/module-setup.sh
inst_binary uses ${dracutsysrootdir} internally to find the source
file.
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
Fixes #
The generated initramfs printed errors during boot because `dracut-util` was missing behind `dracut-getarg` and `dracut-getargs`.
=> fix(base): Fix installing dracut-util

modules.d/35network-manager/module-setup.sh
Since version 1.32, NetworkManager launches a tiny external helper to determine the hostname via reverse DNS resolution through glibc's nss-dns. Include the binary.
=> fix(network-manager): include nm-daemon-helper binary

modules.d/99squash/module-setup.sh
This tailing '/' will result in following error:
dracut-install: ERROR: installing '/etc/ld.so.conf.d/'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.kEFQLs/initramfs -d /etc/ld.so.conf.d/
=> fix(squash): remove tailing '/' when installing ld.so.conf.d

modules.d/99base/init.sh
We want word splitting to occur so that the arguments are passed
separately, and we don't end up passing an empty string if no arguments
are specified.
Bug: https://bugs.gentoo.org/803548
Fixes: 2fabaaa62dcfd31e593ca45e1374e55adae29d6b
=> fix(base): do not quote $initargs for switch_root

man/dracut.cmdline.7.asc
An Infiniband network can be segmented in different partitions, similar to VLANs. Each partition is identified by a partition key (P_Key).
On Linux, a new partition for a IP-over-Infiniband device can be created via e.g.:
```
echo 0x8001 > /sys/class/net/ib0/create_child
```
The resulting interface will be `ib0.8001` with P_Key 0x8001.
Document a new command line argument to create the partition.
NetworkManager is going to implement the new option in [1].
[1] https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/884
=> docs: introduce a 'ib-pkey=' command line argument

modules.d/35network-manager/module-setup.sh, modules.d/35network-manager/nm-run.sh
NetworkManager leaves state files behind in `"/run/NetworkManager/devices"`.
These files are in keyfile format (glib's GKeyFile API).
Other users want to parse the dhcpopts file, for example anaconda ([1]).
We need to write the dhcpopts file in a format that is defined and easy
to handle from a shell script. As already previously, this format is
a bash script that sets certain variables. That means, to load the file,
the user could execute it as bash script. But this is dangerous, as the
file contains potentially untrusted data from the network.
Optimally, users still don't trust the .dhcpopts file to be safe for
executing! It would be far better if they too try to parse the file
instead of executing it. That is not trivial however.
Anyway, make sure we properly quote and handle the …
=> fix(network-manager): ensure safe content of /tmp/dhclient."$ifname".dhcpopts

src/install/dracut-install.c, src/install/hashmap.c, src/install/hashmap.h, src/install/log.c, src/install/log.h, src/install/macro.h, src/install/strv.c, src/install/strv.h, src/install/util.c, src/install/util.h
Fixed few cppcheck warnings
Find the attached for cppcheck results
[cppcheck-results.txt](https://github.com/dracutdevs/dracut/files/6806386/cppcheck-results.txt)
Signed-off-by: Shreenidhi Shedi <sshedi@vmware.com>
Signed-off-by: Shreenidhi Shedi <yesshedi@gmail.com>
installer code fixes
- [] I have tested it locally
- [] I have reviewed and updated any documentation if relevant
- [] I am providing new code and test(s) for it
Fixes #
nit picking fixes
=> fix(install): reduce cppcheck warnings

modules.d/35network-manager/nm-lib.sh, modules.d/40network/module-setup.sh, modules.d/80cms/cmsifup.sh
When NetworkManager is running as systemd service, it's not enough to write connection files; the module should also tell NetworkManager to reload the connections from disk so that any new connection can be auto-activated.
https://bugzilla.redhat.com/show_bug.cgi?id=1975929
=> fix(cms): reload NetworkManager connections

modules.d/99squash/module-setup.sh
There are some workarounds in dracut.sh for FIPS/libpthread covering
some hidden lib dependency issues. These workarounds didn't take effect
for the squash loader since the squash loader is installed
independently. So apply these workarounds again.
Also skip the lib detection code, since these extra installed libs
are small, and squash loader contents are dropped after switch root,
won't be an issue to be always installed. And this makes the code
cleaner.
Fixes #
=> fix(squash): apply FIPS and libpthread workaround

modules.d/35network-manager/nm-run.sh
Anaconda parses the 'filename' variable [1] set in /tmp/net.$netif.dhcpopts to determine the name of the kickstart file to use.
[1] https://github.com/rhinstaller/anaconda/blob/anaconda-35.21-1/dracut/fetch-kickstart-net.sh#L31-L34
=> fix(network-manager): write DHCP filename option to dhcpopts file

modules.d/98usrmount/mount-usr.sh
Currently $_dev is always overridden with the value returned by
label_uuid_to_dev(). This results in an empty value if $_dev is a
device path. Fix this by calling label_uuid_to_dev() conditionally.
Bug: https://bugs.gentoo.org/807971
Fixes d3532978de04c78f53664dad7b37705a49a7ee54
=> fix(usrmount): do not empty _dev variable

modules.d/95nvmf/parse-nvmf-boot-connections.sh
- ifname should be the interface on which $traddr can be reached. It currently gets set to "lo", which is incorrect. This patch identifies the correct interface that would be used for the nvme-of-tcp connection.
- 'ip l show' and 'ip route get' both succeed if interface and route are present. Current 'if' condition (wrongly) produces a warning when the commands succeed. This patch fixes that.
Signed-off-by: Charles Rose <charles.rose@dell.com>
Fixes #
=> fix(nvmf): validate_ip_conn

dracut.conf.d/suse.conf.example, dracut.sh
This pull request changes the default compression option for SUSE to zstd, due to an internal company decision.
It also checks whether the target kernel has zstd support compiled in; otherwise, it does not compress the initramfs image.
=> ci: change default compression option for SUSE

modules.d/90multipath/multipathd.service
This removes the `ExecStop=` field from multipath.service.
Some CI runs do rarely encounter a failure related to this
service in initrd, which seems to be stemming from a socket
I/O race between the client and the server on shutdown.
It looks like the client (`multipathd shutdown`) can lose the race,
hit an I/O error, and cause the whole unit to fail (even if the server
managed to shutdown properly already).
Notably, the upstream unit does not have such stop command
as the daemon can already perform a graceful exit through
its signal handler.
As such, this commit re-aligns the two units by dropping the
custom stop-command, thus avoiding any of the existing
races.
Refs:
* https://github.com/coreos/fedora-coreos-tracker/issues/803
* …
=> fix(multipath): drop ExecStop= setting from service unit

src/install/dracut-install.c
Now dracut-install writes message like
`dracut-install: Error 'Cannot allocate memory' initiating pipe stream from 'ldd /bin/sh4 2>&1'`
instead of segmentation fault
=> fix(install): segfault on popen error

test/run-qemu, tools/test-github.sh
There appears to be an issue with newer QEMU versions (spotted with Arch
Linux and C9S containers) which causes the respective GH Actions to hang
when booting a QEMU VM in combination with the `-cpu max` parameter.
During (a particularly painful) debugging session I once managed to get
some output from such "frozen" machine (using `earlycon` and
`earlyprintk` kernel cmdline options), and in that particular case the
VM died with a trap caused by an invalid opcode.
I couldn't reproduce this locally, only in GH Actions environment with
Arch Linux and C9S containers. Also, so far I haven't found out which
specific CPUID flag causes this, but using the `IvyBridge-v2` feature
set seems to mitigate the issue.
---
I came across this when configuring our downstream dracut CI for C9S,
but it …
=> test: don't use `-cpu max` in GH Actions

dracut-initramfs-restore.sh
When a forced shutdown is issued through sending a burst of **Ctrl-Alt-Del** keys, *systemd* sends SIGTERM to all processes. This ends up killing *dracut-initramfs-restore* as well, preventing the script from detecting that the unpack of the initramfs is incomplete, which later causes a crash to happen when *shutdown* tries to execute from the unpacked initramfs.
This fix makes sure *dracut-initramfs-restore* remains alive to detect the unpack failed (because *cpio* was killed by *systemd* too).
Refs:
* [2023665 - Make sure dracut-initramfs-restore cleans up the incompletely unpacked initramfs upon forced shutdown](https://bugzilla.redhat.com/show_bug.cgi?id=2023665)
=> fix(shutdown): be robust against forced shutdown

modules.d/80cms/module-setup.sh, modules.d/90dmsquash-live-ntfs/module-setup.sh
fuse3 no longer includes ulockmgr_server.
https://github.com/libfuse/libfuse/blob/master/ChangeLog.rst#libfuse-300-2016-12-08
Fixes #
=> fix(dmsquash-live-ntfs,cms): fuse3 no longer requires ulockmgr_server

modules.d/95dasd_rules/module-setup.sh, modules.d/95qeth_rules/module-setup.sh, modules.d/95zfcp_rules/module-setup.sh
/usr/lib/udev/collect has been removed from systemd v246, so make it optional in the udev rules
dependency of s390 udev rules on collect
- [X ] I have tested it locally
- [X ] I have reviewed and updated any documentation if relevant
Fixes #
=> fix(s390_rules): make collect optional

modules.d/90dmsquash-live/module-setup.sh
Systemd is an optional module for the dmsquash-live module. This scenario
is properly handled for other modules (for example livenet module) but not for
dmsquash-live module.
Fixes #
=> fix(dmsquash-live): do not install systemd files when systemd is not enabled

modules.d/90crypt/module-setup.sh
In hostonly mode, include the tpm2-tss module if any encrypted volumes are configured in `/etc/crypttab` to be decrypted using the TPM2 device (`tpm2-device=` option).
More info on the [crypttab man page](https://www.freedesktop.org/software/systemd/man/crypttab.html#tpm2-device=).
=> feat(crypt): check if tpm2-tss module is needed in hostonly mode

modules.d/91fido2/module-setup.sh, pkgbuild/dracut.spec
From systemd v248, the systemd-cryptsetup component allows to unlock encrypted storage using FIDO2 security tokens.
This module adds to the initramfs image the dependencies required to unlock an encrypted root filesystem, which are basically the [libfido2](https://github.com/Yubico/libfido2) library and its missing dependencies.
It also needs the `60-fido-id.rules` and the `fido_id` program added by the systemd-udevd module.
More info on the [systemd-cryptenroll](https://www.freedesktop.org/software/systemd/man/systemd-cryptenroll.html#--fido2-device=PATH) and [crypttab](https://www.freedesktop.org/software/systemd/man/crypttab.html#fido2-device=) man pages.
=> feat(fido2): introducing the fido2 module

man/dracut.cmdline.7.asc
The [man page](https://github.com/dracutdevs/dracut/blob/master/man/dracut.cmdline.7.asc#misc) still states the old value of `rd.retry` of _30 seconds_, which does not reflect the [current situation](https://github.com/dracutdevs/dracut/blob/master/modules.d/99base/init.sh#L163) ([introduced here](https://github.com/dracutdevs/dracut/commit/517d27a75f678d4c295cbb07687453950b55df5a)) of _180 seconds_.
Update man page of `rd.retry` to 180 seconds.
=> fix(man): default value of rd.retry was increased to 180 seconds

modules.d/95resume/module-setup.sh
On platforms where the kernel is built without suspend/resume support we
see "cat: /sys/power/resume: No such file or directory" message when
creating an initrd image. Check for the presence of /sys/power/resume
first before reading it.
- [N/A] I am providing new code and test(s) for it
=> fix(resume): check for presence of /sys/power/resume

modules.d/01fips/fips.sh
Support for this flag was broken in 4257798f8ad8570e6918ca9b819ffa254d4316ff
- [*] I have tested it locally
- [*] I have reviewed and updated any documentation if relevant
Fixes #
=> fix(fips.sh): repsect rd.fips.skipkernel

modules.d/90mdraid/mdraid_start.sh
If the system provides more than one UUID, the __MD_UUID_ var contains a [line break](https://github.com/dracutdevs/dracut/blob/master/modules.d/99base/dracut-lib.sh#L315) after each UUID. Therefore the [strstr](https://github.com/dracutdevs/dracut/blob/master/modules.d/99base/dracut-lib.sh#L31)
function could not find any UUID, caused by the additional spaces provided to the function.
Furthermore this could lead to a boot interruption, because the start of a degraded raid1 won't be executed. So, manual
interaction is necessary.
**Scenario**:
System with two raid1 (md0+md1) partitions. One disk fails and system tries to boot:
- udev discovers raid partitions and starts to assemble them [incrementally](https://github.com/dracutdevs/dracut/blob/master/modules.d/90mdraid/65-md-incremental-ims …
=> fix(mdraid): allow UUID comparison for more than one UUID

modules.d/90crypt/module-setup.sh
In hostonly mode, include the fido2 module if any encrypted volumes are configured in `/etc/crypttab` to be decrypted using a FIDO2 device.
More info on the [crypttab man page](https://www.freedesktop.org/software/systemd/man/crypttab.html#fido2-device=).
PR created following https://github.com/dracutdevs/dracut/pull/1641#issuecomment-977598222
=> feat(crypt): check if fido2 module is needed in hostonly mode

modules.d/95resume/module-setup.sh, modules.d/99base/dracut-lib.sh
This pull request fixes `95suspend` module and a function from `99base`, so resumes from hibernation using https://github.com/bircoph/suspend work in Gentoo.
Fixes #
- `95suspend` module setup now also searches for /usr/lib64/suspend/resume and /usr/lib64/uswsusp/resume , which are relevant on distros like Gentoo.
- `label_uuid_to_dev` now returns the unaltered input when it does not match any of the alternate ways to designate a device. Previously, the function was returning nothing, leading to potential failures in several places.
=> Minor fixes on `95suspend` and `99base`

.github/workflows/container.yml
Fedora 33 is scheduled to reach end-of-life (EOL) on 2021-11-30.
No new dracut releases should be ending up in that Fedora release at this point.
Fixes #
=> ci: remove Fedora 33 container

modules.d/35network-legacy/ifup.sh, modules.d/35network-legacy/parse-ip-opts.sh, modules.d/45ifcfg/write-ifcfg.sh
End with error, or show a warning when nonexistent device is specified for network setup like `ip=10.12.8.12::10.12.255.254:255.255.0.0:xk12:eth0:off`.
I've added the error only for `write-ifcfg.sh`, as I think no such setup should be written. For the rest I added only warnings, as I'm not sure `$dev` is not set to something else, or it can be a non-critical error.
Fixes #1712424
I'm new to this - this is my first issue, so I'm not entirely sure how to test this. The test suite does not work for me, locally, but I'll try to create a reproducer.
=> Add errors and warnings when network interface does not exist

dracut.sh
Handle missing compression tools, or otherwise lack of support
for the configured compression method, more gracefully. It's normally not necessary to bail out if e.g. *xz* is not installed.
- [x ] I have reviewed and updated any documentation if relevant
=> Improve logic for selecting initramfs compression

modules.d/50drm/module-setup.sh
Starting with kernel 5.17 the kernel supports the builtin privacy screens
built into the LCD panel of some new laptop models.
This means that the drm drivers will now return -EPROBE_DEFER from their
probe() method on models with a builtin privacy screen when the privacy
screen provider driver has not been loaded yet.
Make dracut add the privacy screen providing drivers to the initrd
(when necessary for hostmode=yes), so that drm drivers on affected
drivers can probe() successfully.
Signed-off-by: Hans de Goede <hdegoede@redhat.com>
Fixes #
=> fix(drm): Add privacy screen modules to the initrd

modules.d/35network-manager/nm-run.sh
There can be files in this directory, eg "bonding_masters" if a
network bond is in use.
Fixes #1604
=> fix(network-manager): skip non-directories in /sys/class/net

modules.d/45url-lib/module-setup.sh
This is an attempt to unlock PR #909 (created via https://github.com/dracutdevs/dracut/pull/909#issuecomment-984607481). As far as I could test, it fixes a current issue.
**Description**
The current detection routine for openssl-based libcurl assumes that
libcurl has its own hardcoded path to the ca-bundle. Fix the
cases where curl is compiled with:
```
--with-ca-fallback --without-ca-path --without-ca-bundle
```
In this case, we must also grep in OpenSSLs libcrypto.
Other changes:
- Filter reported but non-existant paths.
- Strip nul bytes returned by grep.
- Consider that ca-bundles might use '.pem' instead of '.crt'.
=> fix(url-lib): improve ca-bundle detection

modules.d/01systemd-sysusers/module-setup.sh, modules.d/01systemd-sysusers/sysusers-dracut.conf
Fixes a regression with systemd not running units with ConditionNeedsUpdate set in initrds
Fixes #1656
=> fix(systemd-sysusers): override systemd-sysusers.service

modules.d/01systemd-coredump/module-setup.sh, modules.d/01systemd-journald/module-setup.sh, modules.d/01systemd-networkd/module-setup.sh, modules.d/01systemd-resolved/module-setup.sh, modules.d/01systemd-timesyncd/module-setup.sh
Fixes the regression introduced by https://github.com/systemd/systemd/pull/20056
As discussed in #1656 and #1657
Include the new sysusers.d files to allow compatability with future systemd releases. Otherwise the users would be missing inside the initrd.
Fixes #
=> fix(systemd-sysusers): use split systemd sysuser configs

modules.d/95rootfs-block/module-setup.sh
When dracut is called with the "--modules" argument, the base
module needs to be specificed by the caller. Dracut already has
a well functioning dependency management system that could be used
to not make base module special.
Fixes #
=> fix: make the base module dependency explicit

src/dracut-cpio/src/main.rs
This is a workaround for GRUB2's Btrfs implementation, which doesn't
correctly handle gaps between extents.
A fix has already been proposed upstream via
https://lists.gnu.org/archive/html/grub-devel/2021-10/msg00206.html
Given that this bug is severe, it makes sense to include this minimal
workaround.
Signed-off-by: David Disseldorp <ddiss@suse.de>
https://bugzilla.opensuse.org/show_bug.cgi?id=1190982
=> fix(cpio): write zeros instead of seek for padding and alignment

modules.d/35network-wicked/module-setup.sh
Since [wicked-0.6.67](https://github.com/openSUSE/wicked/blob/version-0.6.67/wicked.spec.in#L117), its dbus configuration files can be installed in /etc or /usr/share, what was breaking this module in openSUSE Tumbleweed.
Also, check if it's using `libexec` or `lib` instead of displaying always an error.
=> fix(network-wicked): multiple path corrections

dracut.sh
Invalid config file/directory path should not be silently ignored.
Fixes issue #1136
Fixes #1136
=> fix(dracut.sh): do not ignore invalid config file or dir path

modules.d/90dmsquash-live/dmsquash-live-root.sh
An example kernel command line option for this configuration
root=/dev/sda1 ro rd.live.image rd.live.overlay.overlayfs=1
The change checks if $FSIMG is empty and adds a symlink from
/run/rootfsbase to /run/initramfs/live and changes the place
of the creation of the required mount point directories.
Fixes #
=> fix(dmsquash-live): overlayfs on a block device root

modules.d/01systemd-integritysetup/module-setup.sh, pkgbuild/dracut.spec
Adds module support for [systemd-integritysetup](https://github.com/systemd/systemd/pull/20902) which utilizes [dm-integrity](https://www.kernel.org/doc/html/latest/admin-guide/device-mapper/dm-integrity.html).
=> feat(dm-integrity): add module for systemd-integritysetup

modules.d/40network/net-lib.sh
- fix(40network): consistent use of "$gw" for gateway
- [x ] I have tested it locally
Fixes #
=> Fix inconsistent variable use in 40network

modules.d/90multipath/module-setup.sh, modules.d/90multipath/multipathd.service
Fix some issues in multipathd.service, and eliminate the differences
wrt the unit file shipped with multipath-tools upstream. The ultimate
goal is to be able drop the service unit file from dracut and use the
one from upstream. I have sent a patch series to the dm-devel mailing
list today ("[PATCH 0/4] multipathd: service unit fixes").
Also, despite the recent changes in upstream multipath-tools,
we still get warnings about systemd-udev-settle.service, this time
for multipathd-configure.service. It would be nice to get rid of them,
too. This patch set avoids installing that unit file if mpathconf isn't
available.
@bmarzins, you're invited to push a fix for multipathd-configure.service
to this branch. I expect that simply dropping the dependencies on
systemd-udevd-settle.service will …
=> multipath fixes

modules.d/90lvm/64-lvm.rules, modules.d/90lvm/lvm_scan.sh, modules.d/90lvm/module-setup.sh
This series makes various updates to the lvm module:
- removes support for the unused lvm snapshot management feature
- removes automated editing of deprecated lvm.conf lvmetad settings
- removes an unused udev rule
- replaces the use of --partial with --activationmode degraded
- removes checks for using options that have existed for many years
- uses the filter generated by dracut when lvm.conf has no filter set
- only attempts to activate an LV when the LV is seen on devices
- [x ] I have tested it locally
Fixes #
=> improve lvm module

modules.d/90kernel-modules/module-setup.sh
Mailbox drivers might be needed by some of the devices used in the
initrd. For example, on the Raspberry Pi 4, the MMC 'sdhci-iproc' driver
depends on 'bcm2835-mailbox'.
Signed-off-by: Adrien Thierry <athierry@redhat.com>
=> fix(kernel-modules): add mailbox drivers for arm

modules.d/90kernel-modules-extra/module-setup.sh
The regular expression here is trying to handle various kernel
module compression schemas and was missing the zst extension
which indicates use of zstd.
Fixes #
=> fix(kernel-modules-extra): Handle zstd module extension

modules.d/99memstrack/memstrack-start.sh, modules.d/99memstrack/memstrack.service, modules.d/99memstrack/module-setup.sh
This makes the scripts POSIX compatible and bash is no longer needed.
Use nohup instead of disown, and let systemd track the service properly.
=> fix(memstrack): drop bash runtime requirement

modules.d/95dasd_rules/parse-dasd.sh, modules.d/95zfcp_rules/parse-zfcp.sh
The collect binary has been removed, so the rules are broken
Fixes #
=> fix(S390_rules): remove collect based udev rule creators

Makefile, modules.d/98dracut-systemd/dracut-shutdown-onfailure.service, modules.d/98dracut-systemd/dracut-shutdown.service, modules.d/98dracut-systemd/dracut-shutdown.service.8.asc, pkgbuild/dracut.spec
It may happen that `dracut-shutdown.service` fails, for example on timeout due to very low bandwidth.
In such case, for hardening purposes, a new `dracut-shutdown-onfailure.service` unit doing `dracut-shutdown.service` cleanup needs to execute to make sure switching root to an incomplete initramfs won't occur later.
See also [RHBZ #1924587](https://bugzilla.redhat.com/show_bug.cgi?id=1924587).
Fixes #
=> fix(dracut-shutdown): add cleanup handler on failure

dracut-initramfs-restore.sh
The unpack fails if the initrd is not compressed or compressed with bzip2 or LZO.
Fixes #1463
=> fix(dracut-initramfs-restore.sh): add missing compression options

modules.d/40network/module-setup.sh
The test for the wicked service is never met because it does not have execute permission.
=> fix(network): wrong test of wicked unit

modules.d/01fips/fips-noboot.sh, modules.d/01fips/fips.sh, modules.d/01fips/module-setup.sh
This pull request applies minor fixes in the fips module:
- Change a wrong error message.
- Remove unused local variables and add a missing one.
- Make sure dracut-lib is sourced within the fips-noboot script.
=> fix(fips): minor fixes

dracut.sh, modules.d/99base/dracut-lib.sh
From bash manpage, `FUNCNAME` exists only inside functions. When in debug mode, make sure to use an empty default value as `FUNCNAME[0]` when outside of functions.
With bash4 this wasn't an issue, but is with bash5 with hardening option **set -u** used, as shown in the example below:
Incorrect:
~~~
$ bash -u -c 'echo -n ${FUNCNAME[0]}'
bash: line 1: FUNCNAME[0]: unbound variable
$
~~~
Correct:
~~~
$ bash -u -c 'echo -n ${FUNCNAME[0]-}'
$
~~~
This hardening enables sourcing `dracut-lib.sh` from external utilities executing in the initramfs such as `clevis-luks-askpass`, which uses hardening option **set -u** internally (see [Clevis PR 340](https://github.com/latchset/clevis/pull/340))
- [N/A] I have reviewed and updated any documentation if relevant
- [N/A] I …
=> fix(dracut): be more robust when using 'set -u'

modules.d/91fido2/module-setup.sh, modules.d/91tpm2-tss/module-setup.sh
This adds the missing libraries libcryptsetup-token-systemd-fido2.so libcryptsetup-token-systemd-tpm2.so to their module fixes #1676 
TODO create a new p11-kit module.
Fixes #
=> Add missing libraries

modules.d/99img-lib/module-setup.sh
rmdir is used in some modules but not properly installed (e.g. img-lib module).
It would make it easier to ration about the dependencies and would save
a bit of intramfs space to just use rm instead.
- [ X ] I have tested it locally
Fixes #
=> fix(img-lib): install rmdir

modules.d/62bluetooth/module-setup.sh
Add a missing /usr/share path ( fixes #1627 )
Use variable instead of hard path
Fixes #
=> fix(bluetooth): dbus configuration path fixes

modules.d/62bluetooth/module-setup.sh
Do not fail if any of the expected configuration files don't exist.
Upstream bluez explicitly asked distributions to not ship a `main.conf`, so that the compiled-in system-wide defaults for bluez are used, unless the user explicitly configures something else.
For example, SUSE ships the template under `/usr/share/doc/packages/bluez/main.conf`, if the user wants to configure system-wide settings, he can copy it to `/etc/bluetooth` and edit it.
=> fix(bluetooth): make hostonly configuration files optional

modules.d/95dasd_rules/module-setup.sh, modules.d/95zfcp_rules/module-setup.sh
Arguments to the inst_rules_wildcard function need quoting
rules naming *-s390x-* was obsolete and broken
- [ X] I have tested it locally
Fixes #
=> S390 rules fix inst rules arguments

modules.d/01systemd-coredump/module-setup.sh, modules.d/01systemd-timesyncd/module-setup.sh
This pull requests adds the required `systemd-sysusers` dependency to `systemd-coredump` and `systemd-timesyncd` after the split of systemd sysuser configs (https://github.com/dracutdevs/dracut/commit/fec93bb22181f80056b40231fca36c422248ade0),
=> fix(systemd-sysusers): add required dependency after the split of systemd sysuser configs

modules.d/01systemd-journald/module-setup.sh
This pull request removes a duplicate entry in the inst_multiple call (lines 45 and 48 are equal):
https://github.com/dracutdevs/dracut/blob/631d5f72a223288aa1f48bb8e8d0313e75947400/modules.d/01systemd-journald/module-setup.sh#L45-L48
=> fix(systemd-journald): remove duplicate entry in inst_multiple

modules.d/95iscsi/iscsiroot.sh
Commit 7374943ae3d06 ("fix(iscsi): add support for the new iscsiadm
"no-wait" (-W) command") added some code to try to disable iscsi's
NOPs, since they are considered "bad" for an iscsi root disc,
but that code doesn't work because the session is already established
at this point. Open-iscsi will change so that it automatically
disables NOPs for the root disc, so this code can just go away.
Fixes #
=> fix(iscsi): Remove unneeded iscsi NOP-disable code

dracut.sh
- Typo assigning `depmodd` and `depmodconfdir`.
- Typo exporting a variable called sysctl instead of `sysctld`.
=> fix(dracut.sh): error exporting sysctl variables

dracut-functions.sh, dracut.sh, modules.d/95rootfs-block/module-setup.sh
zfs detection is currently done by the zfs dracut module installed by
downstream, resulting in a lot of duplicated code. This commit puts zfs
detection into the core dracut logic, allowing for detection of zfs
partitions to be done at the same time as all others. It also allows for
dracut to correctly create a `root=` cmdline parameter for zfs.
Signed-off-by: Savyasachee Jha <hi@savyasacheejha.com>
- Adds a `zfs_devs` function analogous to `btrfs_devs` in `dracut-functions.sh`
- Adds detection of zfs devices using function in the above point
- If the rootfs is on a zfs partition, then allows for setting a `root=zfs:<zfs dataset>` cmdline parameter
Fixes #
Nothing
=> Add zfs detection

src/install/util.c
__GLIBC_PREREQ is only defined in glibc. This change reverts
the recent change from ef0f848a67fdd0a0dab135acbd1cd7fa0179a95c.
The portability of the code outweights the benefits of the
earlier change.
Fixes #
=> fix(install): restore musl support

modules.d/90dmsquash-live/dmsquash-live-root.sh
An example kernel command line arguments for this configuration
iso-scan/filename=distro.iso root=live:CDLABEL=ISO
rd.live.image rd.live.overlay=/dev/sda:/overlay.img
iso-scan would mount /dev/sda first and keep it mounted. The change
allows detecting if the permanent overlay drive is already mounted.
It also ensures that the mount is writable, as permanent overlay
requires writable storage.
Fixes #
=> fix(dmsquash-live): permanent overlay on the same drive as LiveCD .iso

dracut.sh
This pull request drops `restorecon` call from dracut.sh, as AFAICT there is no need for it. `cp` already applies appropriate label on the target file (unless `--preserve=context` is used).
- drop `restorecon` call
=> fix(dracut.sh): drop restorecon call

modules.d/10i18n/module-setup.sh
The findkeymap function in the `10i18n/module-setup.sh` manipulates the shell  options and relies on restoring them using the trap. However, as the function might be called recursively, each recursive invocation changes the signal handler to its
own. As the recursion is entered with shell options already modified, the changed trap handler is replaced with restoration to the modified shell options, not the original ones. This patch wraps the findkeymap function so that the shellopts are manipulated and restored outside the recursion.
- wrap the recursive `findkeymap` function with a wrapper in which the shell options are manipulated and restored correctly
=> Fix shell options leaking from the 10i18n module.

modules.d/98dracut-systemd/dracut-shutdown.service
This pull request fixes dependencies of `dracut-systemd.service`. `dracut-systemd.service` is not an early boot service, therefore it should not use `DefaultDependencies=no`. This automatically fixes the service's ordering dependencies, as in its current state it is missing `Before=shutdown.target umount.target`.
=> fix(98dracut-systemd): fix service dependencies

modules.d/62bluetooth/module-setup.sh
Do not display an error message if the `$dbussystem/bluetooth.conf` file don't exist.
This line was added in commit https://github.com/dracutdevs/dracut/commit/34b1dd2e26c343e9000094db01a7985b6851adf1 to include the missing `/usr/share/dbus-1/system.d/bluetooth.conf` in Arch Linux, but not all Linux distributions ship this file (e.g.: Fedora, SUSE...).
=> fix(bluetooth): make $dbussystem/bluetooth.conf optional

dracut-initramfs-restore.sh
It can happen that SELINUXTYPE is not set, e.g., in Fedora/RHEL
installation images /etc/selinux/config is an empty file. That means
that setfiles fails, which makes dracut-initramfs-restore fail too
because it uses "set -x", which means that dracut-shutdown.service
fails. But, after commit 7ab1d00227cad6f1b86ba01fdc766769faebb031, a
failure of dracut-shutdown.service means that the final switch back into
initrd is skipped. Let's just add an additional sanity check to
workaround that.
=> fix(dracut-initramfs-restore.sh): check if SELINUXTYPE is set

modules.d/90dmsquash-live/module-setup.sh, modules.d/95udev-rules/module-setup.sh
Include cdrom udev rules by default, even if
systemd-udevd or dmsquash-live dracut modules
are not installed.
Fixes #
=> fix(udev-rules): add cdrom udev rules by default

dracut.sh
binutils 2.38 added support for aarch64 efi binaries to objcopy, so it is now possible to create combined efi images for aarch64 as well.
This PR adds support for this to dracut.
Fixes #1629
=> feat: add aarch64 uefi support

modules.d/50plymouth/module-setup.sh
`dpkg-architecture` prints warnings and errors to stderr. If the system does not have gcc installed, it issues a warning:
```
dpkg-architecture: warning: cannot determine CC system type, falling back to default (native compilation)
```
This fix checks only the value of the queried variable.
=> fix(plymouth): hide dpkg-architecture stderr messages

modules.d/35connman/cm-config.sh, modules.d/35connman/cm-initrd.service, modules.d/35connman/cm-lib.sh, modules.d/35connman/cm-run.sh, modules.d/35connman/cm-wait-online-initrd.service, modules.d/35connman/module-setup.sh, modules.d/35connman/netroot.sh, modules.d/40network/module-setup.sh
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
Add a new 35connman module.
This module supersedes issue #1682 as almost all of my Yocto images use connman and the remote booted one was the odd one out. This module allows using connman as the network tool both in initramfs and the squashfs root that the initramfs is generated from.
The network-connman module depends on systemd, since connman, unlike NetworkManager, doesn't have a configure-and-exit mode so a scripted network initialization is not possible. Also, connman deletes the connections when exiting.
Fixes #
=> feat(connman): introduce connman support module

modules.d/90lvm/lvm_scan.sh
The "lvm config" commands that check the filter settings will
often find nothing set and report an error message:
"Configuration node devices/filter not found"
Direct these messages to /dev/null so they do not appear as
noise in system logs.
- I have tested it locally
=> fix(lvm): ignore expected error message from lvm config

dracut-initramfs-restore.sh
=> fix(dracut-initramfs-restore.sh): unpack uncompressed initrd as last option

docs/BASH.md, modules.d/10i18n/module-setup.sh, modules.d/62bluetooth/module-setup.sh, src/install/dracut-install.c, test/TEST-04-FULL-SYSTEMD/test.sh
Glob is in most cases not expected to evaluate to null. To avoid unexpected failures, don't use the `nullglob` option.
I've found no code (WRT the modifications applied) where nullglob is needed, as the variable is either checked explicitly by `[[ -f $file ]]`, or passed to `inst_multiple -o` where the file string is actually expected instead. I think more code is actually expecting an invalid argument instead of missing one (f.e. `cp`), so this increases resiliency.
- removed `nullglob` option use
- alternative implementation for findkeymap (10i18n module) with `mapfile` (recursion overwrites `trap` setting)
- fixed `dracut-install` not to fail when `-o` is specified, but no source is specified
_ _ _ _
E.g., a PR which I don't think should be needed: …
=> Avoid using nullglob option and fix dracut-install

src/install/dracut-install.c
While the "clone copy" operation changes the ownership of the cloned files, the "normal copy" using `cp` does not preserve it.
This causes errors with configuration files with o= permissions that belong to a systemd group. E.g., systemd-networkd using WireGuard keys (https://wiki.archlinux.org/title/WireGuard#systemd-networkd):
```
localhost:~ # ls -l /etc/systemd/network
total 4
-rw-r----- 1 root systemd-network 39 Apr  4 09:06 20-wired.network
localhost:~ # lsinitrd | grep etc/systemd/network/
-rw-r-----   1 root     root       39 Apr  4 09:06 etc/systemd/network/20-wired.network
localhost:~ # journalctl -b -p3
Apr 04 09:37:11 localhost systemd-networkd[335]: Failed to open configuration file '/etc/systemd/network/20-wired.network': Permission denied
Apr 04 09:37:11 localhost …
```
=> fix(dracut-install): copy files preserving ownership attributes

modules.d/45url-lib/url-lib.sh
Trigger the existing retry condition on connection refused
to mitigate transient connectivity issues.
This pull request updates the default curl options to include `--retry-connrefused`, triggering retry behavior if connections are refused.
Testing (using a python web server serving single file, foo)
```
jamesm@x1:~/src/dracut$ curl --globoff --location --retry 3 --fail --show-error  localhost:8000/foo
curl: (7) Failed to connect to localhost port 8000: Connection refused
jamesm@x1:~/src/dracut$ curl --globoff --location --retry 3 --fail --show-error  localhost:8000/foo
hello dracut
jamesm@x1:~/src/dracut$ echo $?
0
jamesm@x1:~/src/dracut$ curl --globoff --location --retry 3 --fail --show-error --retry-connrefused localhost:8000/foo
curl: (7) Failed to connect to localhost port 8000: …
```
=> feat(url-lib.sh): Add --retry-connrefused to default curl arguments

dracut.sh, man/dracut.8.asc
This pull request adds the missing usage and man section of the `--libdirs` option (introduced almost 10 years ago... https://github.com/dracutdevs/dracut/commit/c9143a63).
=> Add missing usage and man section of --libdirs option

modules.d/35network-manager/nm-lib.sh, modules.d/45ifcfg/write-ifcfg.sh
The dracut-logger functions are only available during the initrd generation.
For internal initrd scripts that run at boot, dracut-lib provides `warn()` and `info()`.
This PR should cover all the wrong calls:
```
modules.d/35network-manager/nm-lib.sh:14:        derror "nm-initrd-generator not found"
modules.d/45ifcfg/write-ifcfg.sh:107:        derror "Cannot find network interface '$_netif'!"
```
=> Avoid calling unavailable dracut-logger functions from boot scripts

dracut-functions.sh, modules.d/95resume/module-setup.sh
The `block_is_netdevice` function requires the device in <maj:min> format, but the `swap_devs` array is populated with the content of /proc/swaps, which prints the devices using their paths from /dev.
This causes the check method to never detect if swap is mounted on a network device.
=> fix(resume): correct call to block_is_netdevice function

modules.d/90lvm/module-setup.sh
Since commit https://github.com/dracutdevs/dracut/commit/7ffc5e38 `lvm_scan.sh` requires `grep`.
https://github.com/dracutdevs/dracut/blob/a7a4b76c4ad5794f5f8a24ecd5b495f1512d05f7/modules.d/90lvm/lvm_scan.sh#L55-L65
=> fix(lvm): add missing grep requirement

modules.d/95nfs/module-setup.sh, modules.d/95nfs/nfs-start-rpc.sh
- `parse-nfsroot.sh` requires `sed`, `chmod` and `chown`.
```
modules.d/95nfs/parse-nfsroot.sh:92:        sed -i -e \
modules.d/95nfs/parse-nfsroot.sh:96:    # and even again after the sed, in case it was not yet specified
modules.d/95nfs/parse-nfsroot.sh:127:chown rpc:rpc /var/lib/rpcbind
modules.d/95nfs/parse-nfsroot.sh:128:chmod 770 /var/lib/rpcbind
```
- Avoid errors when `rpcbind` tries to write to the `/run/rpcbind` directory.
```
Apr 13 11:35:43 localhost systemd[1]: Starting dracut pre-pivot and cleanup hook...
Apr 13 11:33:13 localhost rpc.idmapd[262]: exiting on signal 15
Apr 13 11:33:13 localhost rpcbind[253]: cannot open file = /run/rpcbind/rpcbind.xdr for writing
Apr 13 11:33:13 localhost rpcbind[253]: cannot save any registration
Apr 13 11:33:13 localhost rpcbind[253]: …
```
=> fix(nfs): give /run/rpcbind ownership to rpc user and add missing requirements

modules.d/90kernel-network-modules/module-setup.sh
Commit 1e92f728 ("Add a --hostonly-nics option") allows only installing
the network drivers for specified NICs. But it doesn't allow an emtpy
--hostonly-nics. Specifying empty hostonly-nics is needed to address the
following use cases,
- drivers/s390/net is installed regardless of --hostonly-nics. There is
no need to repeat it
- get_dev_module couldn't find the driver for a bond or a bridge
network interface so it's better for a module to install a bond
or bridge driver itself
- dracut kdump module wants to install the needed network drivers by
itself because it can't add the --hostonly-nics option to dracut when
itself is a dracut module
This patch distinguishes between an empty --hostonly-nics and --hostonly-nics
not added so a user can pass an empty --hostonly-nics option.
This pull …
=> fix(kernel-network-modules): allow specifying empty --hostonly-nics

dracut.sh, lsinitrd.sh, man/dracut.8.asc, man/dracut.usage.asc, man/lsinitrd.1.asc
Consistent with issue #1628 and PR #1634, add missing dracut default output files.
When using systemd-boot and kernel-install, dracut runs a hook script (install.d/50-dracut.install) to generate the initrd at the correct place in the ESP. However, when calling dracut manually the initrd is saved in the traditional place in /boot. The same happens with lsinitrd, it does not detect the default initrd.
Fix the auto detection that doesn't notice the bootloader spec installation.
=> Add missing dracut default output files

dracut.conf.d/fedora.conf.example
Changes
/usr/bin/vi is just a wrapper shell script to run /usr/libexec/vi which is the vi binary.
/usr/bin/vi is available in initramfs.img, but /usr/libexec/vi is missing.
As as result, the vi command never works.
This PR is to add /usr/libexec/vi.
=> fix(fedora.conf): vi binary is missing

modules.d/98dracut-systemd/dracut-cmdline-ask.service, modules.d/98dracut-systemd/dracut-cmdline.service, modules.d/98dracut-systemd/dracut-emergency.service, modules.d/98dracut-systemd/dracut-initqueue.service, modules.d/98dracut-systemd/dracut-mount.service, modules.d/98dracut-systemd/dracut-pre-mount.service, modules.d/98dracut-systemd/dracut-pre-pivot.service, modules.d/98dracut-systemd/dracut-pre-trigger.service, modules.d/98dracut-systemd/dracut-pre-udev.service, modules.d/98dracut-systemd/dracut-shutdown-onfailure.service, modules.d/98dracut-systemd/dracut-shutdown.service, modules.d/98dracut-systemd/emergency.service
This pull request improves dracut's service files a tiny bit.
- Remove reference to dracut.bootup(7) from two services that are not part of boot process.
- Use Documentation= directive instead of a comment to refer to a man page.
=> Use Documentation= to point to man page

dracut.sh
dracut-logger is sourced in dracut-init, so any earlier calls to logger functions before dracut-init is sourced fail.
Fix issue #1758
Fixes #1758
=> fix(dracut.sh): avoid calling dfatal before dracut-logger is sourced

modules.d/90dmsquash-live/dmsquash-live-root.sh
fstype is not the correct type for the live device.
Fixes #
=> fix(dmsquash-live): mount live device with the correct type

man/dracut.usage.asc
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> dracut.usage: Fix dracut.cmdline reference from section 5 to 7

test/container/Dockerfile-Debian
sudo is required to run the CI tests.
=> ci: install sudo for the debian container

dracut.sh, lsinitrd.sh
On new installations, /etc/machine-id may exist and be empty, and also /efi or /boot/efi may be a mount point, leading to an invalid initramfs output file.
Excerpt from a failed openQA test:
```
2022-05-01 09:03:19 <3> install(3949) [Ruby] lib/cheetah.rb(log_stream_line):211 Error output: dracut: Executing: /usr/bin/dracut --kver=5.17.4-1-default --force
2022-05-01 09:03:19 <3> install(3949) [Ruby] lib/cheetah.rb(log_stream_line):211 Error output: dracut: Can't write to /boot/efi//5.17.4-1-default: Directory /boot/efi//5.17.4-1-default does not exist or is not accessible.
2022-05-01 09:03:19 <3> install(3949) [Ruby] lib/cheetah.rb(record_status):183 Status: 1
2022-05-01 09:03:19 <3> install(3949) [Ruby] yast2/execute.rb(rescue in popup_error):232 Execution of command "[["/usr/bin/dracut", …
```
=> fix(dracut.sh): always check that MACHINE_ID is not empty 

modules.d/95iscsi/iscsiroot.sh
If user specify multiple netroot in cmdline, and one of it is not accessible, previous implement would exit discovery flow.
After this chang, it would continue trying other netroot.
Actually, the previous implement is not reasonable in another way, if we specify 3 netroot, and the second netroot would fail, the others are ok. Then the first netroot would connect success, and the third would not be connected.
- [✓] I have tested it locally
- [✓] I have reviewed and updated any documentation if relevant
- [✓] I am providing new code and test(s) for it
Fixes https://github.com/dracutdevs/dracut/issues/1798
=> fix(iscsi): do not exit in handle_netroot() if discovery failed

.github/labeler.yml, man/dracut.cmdline.7.asc, modules.d/95virtiofs/module-setup.sh, modules.d/95virtiofs/mount-virtiofs.sh, modules.d/95virtiofs/parse-virtiofs.sh, pkgbuild/dracut.spec
Currently, dracut can't mount virtiofs as root filesystem.
Make possible to boot virtual machines off virtiofs,
passing "root=virtiofs:\<mtag\>", using the mount tag <mtag>
as root filesystem. Alternatively this module also supports
"rootfstype=virtiofs root=\<mtag\>"
- [ x ] I have tested it locally
=> feat(virtiofs): virtiofs root filesystem support

dracut.sh, man/dracut.8.asc, man/dracut.conf.5.asc, shell-completion/bash/dracut, shell-completion/bash/lsinitrd
This PR adds missing bash completion options, missing options in dracut.sh usage, dracut and dracut.conf man pages and attempts to unify the text format of each part. Specifically:
- man/dracut.conf: set common format to each option, add/correct default values and add missing options.
```
force_add_dracutmodules
libdirs
squash_compress
aggresive_strip
do_hardlink
prefix
hostonly_mode
hostonly_nics
sshkey
regenerate_all
noimageifnotneeded
uefi
machine_id
enhanced_cpio
```
- man/dracut: set common format to each option, correct default compression options and add missing options.
```
--rebuild
--aggresive-strip
--hostonly-mode
--hostonly-nics
--noimageifnotneeded
```
- dracut.sh: set common format to each usage option and add missing options.
```
--no-machineid
```
=> Update dracut and dracut.conf man, dracut usage and bash completion

man/dracut.conf.5.asc
The `regenerate_all` option is used before sourcing the configuration files. 
I introduced this wrong manual entry in #1815, somehow I missed it, sorry.
https://github.com/dracutdevs/dracut/blob/9bef71094eba84a9eac161fc45386ccd73bd2b34/dracut.sh#L873
https://github.com/dracutdevs/dracut/blob/9bef71094eba84a9eac161fc45386ccd73bd2b34/dracut.sh#L950-L962
=> docs(dracut.conf): regenerate_all not supported

man/dracut.cmdline.7.asc, modules.d/98integrity/ima-keys-load.sh
- Add missing `evmx509` option to dracut.cmdline man page.
- Avoid displaying `ls` error when there is no IMA certificate (IMA appraisal can be used without digital signatures, just by storing hash digests instead, and protecting against file tampering using EVM):
```
May 24 17:25:05 localhost dracut-pre-pivot[510]: ls: cannot access '/sysroot/etc/keys/ima/*': No such file or directory
```
=> integrity: minor fix and missing option in doc

man/dracut.cmdline.7.asc, modules.d/95nvmf/module-setup.sh, modules.d/95nvmf/parse-nvmf-boot-connections.sh
- Deprecate old nvmf cmdline options without the `rd.` prefix.
- Add missing `rd.nonvmf` cmdline option to man page.
Fixes #1831
=> fix(nvmf): deprecate old nvmf cmdline options

Makefile
`CWD` is not a Make variable. This may have worked accidentally for some
people if their shell happend to provide `CWD` and Make picked it up.
As is, this tends to pick up git versions of unrelated parent
directories, e.g. when packaging for distributions.
* Fix usage of potentially unset variable to determine git ceiling in Makefile
- [N/A] I am providing new code and test(s) for it
Here as an example building the release tarball on with Archlinux/GNU Make/Bash (no `$CWD`):
```
conrad@serotonin ~/hack/dracut-apk $ git log -1 --oneline
f5145bc (HEAD -> master, origin/master) Initial release
conrad@serotonin ~/hack/dracut-apk $ tar xf dracut-056.tar.xz
conrad@serotonin ~/hack/dracut-apk $ cd dracut-056/
conrad@serotonin ~/hack/dracut-apk/dracut-056 $ …
```
=> Use Make variable CURDIR for current directory

dracut-init.sh, dracut.sh, modules.d/62bluetooth/module-setup.sh, src/install/dracut-install.c
The firmware loading path is
1. contents of /sys/module/firmware_class/parameters/path (`fw_path_para`), if any
2. /lib/firmware/updates/$(uname -r)
3. /lib/firmware/updates
4. /lib/firmware/$(uname -r)
5. /lib/firmware
Always.
Repeated single-character strstr()s -> strpbrk() and stat()s with unused buffers -> access()es.
Also check for `.zst`-suffixed firmware, coming in 5.19: https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/driver-core.git/commit/?h=driver-core-next&id=23cfbc6ec44e5e80d5522976ff45ffcdcddfb230
62bluetooth `inst_multiple`s its firmware (for some reason?); glob at the end of the unglobbed paths to catch compressed fw.
=> Fix firmware loading paths, supprt .zst-suffixed firmware

modules.d/80lvmthinpool-monitor/module-setup.sh, modules.d/80lvmthinpool-monitor/start-thinpool-monitor.service, modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh, pkgbuild/dracut.spec
Previously dracut didn't support the feature of lvm thinpool autoextend.
The feature is useful to cases such as kdump, when vmcore to be saved to a
lvm thin volume. The thinpool should be able to autoextend, otherwise an
IO error will be caused and leaves an incomplete vmcore.
There is lvm2-monitor.service and dmeventd avaliable, however
considering [1], it is not suitable for kdump and memory limited cases.
This patch achieves the same by parallel looping a shell function in the
background, which calls lvextend periodically. If thredshold reaches,
autoextend it, if not then nothing happens.
[1]: https://lists.fedoraproject.org/archives/list/kexec@lists.fedoraproject.org/message/YF254ZO3PJ3U56P4OKHV3JNYP2PJUMYX/
Signed-off-by: Tao Liu <ltao@redhat.com>
- [Y] I have tested it locally
- [Y] …
=> feat(lvm): add new module lvmthinpool-monitor

dracut.sh, man/dracut.8.asc, man/dracut.conf.5.asc
Add an option `--parallel` which can currently be used with
`--regenerate-all`. With `--regenerate-all --parallel`, dracut will be
run in parallel for all kernels found.
Also introduce a config file equivalent setting: `parallel="yes"`.
In my testing I've found a linear speed up in execution time.
* add option `--regenerate-parallel`
=> feat(dracut): support parallel execution with --parallel

Makefile
Makefile uses recursively expanded macros and as can be seen by simply
adding `$(warning Call to shell)` in front of `$(shell ...)` Foo's in the
Makefile, we are calling out to shell 9 times just to get the working
directory, a working directory which doesn't change during Make!
Let's save few pony's and reduce it to 2...
=> fix(Makefile): reduce the number of shell invocations

install.d/50-dracut.install
If KERNEL_INSTALL_VERBOSE=1, let's make sure dracut also produces
extended output for debugging purposes.
- [ X ] I have tested it locally
- [ X ] I have reviewed and updated any documentation if relevant
Fixes #
=> kernel-install: Add --verbose if KERNEL_INSTALL_VERBOSE=1

src/install/dracut-install.c
Reduced allocations, fixes in patches 2 and 3
Split off #1796
=> Fix/optimise dracut-install abs_rel

src/install/dracut-install.c
The four commits @marcosfrm mentioned in https://github.com/dracutdevs/dracut/pull/1796/files#r899623860:
* popen() is awful and, helpfully, splits on the unescaped filename
* ldd messages may be internationalised
* fix waiting (and string parsing instead of waiting) for cp and ldd
=> Fix dracut-install subprocesses

man/dracut.8.asc
`s/--no-strip/--nostrip`
Fixes #1852
=> fix(man): correct typo

modules.d/10i18n/module-setup.sh
Commit https://github.com/dracutdevs/dracut/commit/f3441cc7 removed shell
options but didn't adapt all the code that requires nullglob and globstar.
This caused the initrd to be generated without the required includes for
keymaps.
Reported downstream  in openSUSE TW after the update to 057:
- https://bugzilla.suse.com/show_bug.cgi?id=1200950
- https://bugzilla.suse.com/show_bug.cgi?id=1200951
=> fix(i18n): add required includes for keymaps

modules.d/45url-lib/url-lib.sh
This pull request makes curl write directly to a file instead of using redirection via stdout. The redirection was originally added in 5c274467d6a4959b7f451f9a211ffbb38d69b641 to workaround https://bugzilla.redhat.com/show_bug.cgi?id=989133 (curl would create no file if the source was empty), but I don't see that problem with current curl.
A nice side-effect of this change is that curl shows download progress.
=> refactor(url-lib): write curl output directly to file

test/container/Dockerfile-Arch
tgt has a dependency on glibc
Fixes  https://github.com/dracutdevs/dracut/issues/1890
=> ci: add glibc to the Arch Linux container

modules.d/90dmsquash-live/dmsquash-live-root.sh
Do not assume that `overlay` is always a module.  Check first for
`overlay` in `/proc/filesystems`.
Signed-off-by: Federico Vaga <federico.vaga@cern.ch>
See this discussion thread:
https://www.spinics.net/lists/linux-initramfs/msg04900.html
=> fix(dmsquash-live-root): check kernel for built-in `overlay` drivers

dracut-init.sh
Currently only the `inst_multiple` function propagates the result code returned by `dracut-install`.
This was missing since 043 (e.g.: https://github.com/dracutdevs/dracut/blob/043/dracut-functions.sh#L751)
=> fix(dracut-init.sh): propagate the result code returned by dracut-install

dracut-init.sh, lsinitrd.sh
`skipcpio` source path has changed since https://github.com/dracutdevs/dracut/commit/9f9bf8a1
`dracut-install` source path has changed since https://github.com/dracutdevs/dracut/commit/3420a70d
=> fix: correct skipcpio and dracut-install source path

modules.d/90dmsquash-live/dmsquash-live-root.sh, modules.d/90dmsquash-live/module-setup.sh
When the new grub2 iso is written to a usb drive the disk label points
to a partition that does not include the full iso image. This causes
checkisomd5 to run with the wrong data and it fails.
This patch adds a check that will test to see if there is a parent
device that is a disk, and to run checkisomd5 on it instead of on the
partition pointed to by the label.
When running from an iso this will return the original
/dev/disk/by-label/ path, and when running from a usb drive it will
return the parent device (eg. /dev/sda).
Resolves: rhbz#2107858
=> dmsquash-live-root: Run checkisomd5 on correct device

dracut.sh, man/dracut.conf.5.asc
Defining dracut.conf variable 'uefi_secureboot_engine' is passed through to sbsign with --engine flag
dracut.sh
Fixes #
=> pass optional --engine to sbsign to allow signing with hardware devices

dracut.sh
If file is not a regular file (test -f), dracut.sh fails,
which is unexpected change of behaviour.
The workaround would be to create an empty file.
The following example currently fails:
```
dracut --conf /dev/null
```
After the change 
Fixes: #1835
=> fix(dracut.sh): do not fail on irregular files

modules.d/00systemd/module-setup.sh
Set the right permissions for the `/etc/machine-id` file.
Fixes #1864
=> fix(systemd): set right permissions for the machine-id file

test/TEST-02-SYSTEMD/test.sh, test/TEST-11-LVM/test.sh, test/TEST-13-ENC-RAID-LVM/test.sh, test/TEST-15-BTRFSRAID/test.sh, test/TEST-17-LVM-THIN/test.sh
var/lib/nfs/rpc_pipefs is only needed for NFS mounts.
Fixes #
=> fix(test): remove unnecessary setup steps

test/container/Dockerfile-Debian
This change allows executing TEST-20-NFS on Debian.
Fixes #
=> ci: dependencies for testing nfs module for Debian

modules.d/90dmsquash-live/dmsquash-live-root.sh, modules.d/99base/dracut-lib.sh
Check first for squashfs in `/proc/filesystems`.
This is needed in the --no-kernel use case to avoid the error:
modprobe: FATAL: Module overlay not found in directory /lib/modules/<kver>
Introduce load_fstype function to make it easier to check `/proc/filesystems`
before calling modprobe.
Fixes #
=> fix(dmsquash-live): check kernel for built-in squashfs drivers

modules.d/30convertfs/convertfs.sh, modules.d/30convertfs/module-setup.sh
This pull request drops a duplicate definition of `ismounted`.
=> Drop duplicate definition of ismounted

modules.d/50drm/module-setup.sh
Due to non-availability of Hyper-V video driver hyperv_drm in kdump
initramfs, the console seems to be in hang state with no text over it.
We should also go through the /sys/bus/vmbus/devices and include drivers
referenced there.
For reference: https://bugzilla.redhat.com/show_bug.cgi?id=2099502
=> fix(drm): add video drivers needed on hyper-v and similar

modules.d/95virtiofs/module-setup.sh, modules.d/95virtiofs/mount-virtiofs.sh
When dracut.sh is called with "--modules virtiofs", make sure
dracut-lib.sh is installed by making the base module a dependency.
Fixes #
=> fix(virtiofs): ismounted has a dependency on the base module

src/install/dracut-install.c
in `install_dependent_modules` we use `&path[kerneldirlen]` as the key for inserting,
let's do the same for checking.
otherwise installing kernel module has circular dependency from a custom kernel
module directory will cause infinite recursion and segfault.
```bash
$ grep ipmi kbuilt/lib/modules/5.10.121/modules.dep
kernel/drivers/char/ipmi/ipmi_msghandler.ko:
kernel/drivers/char/ipmi/ipmi_devintf.ko: kernel/drivers/char/ipmi/ipmi_msghandler.ko
$ grep ipmi kbuilt/lib/modules/5.10.121/modules.softdep
softdep ipmi_msghandler post: ipmi_devintf
$ ./dracut-install -D /tmp --kerneldir ~/working/kernel/linux-5.10.121/kbuilt/lib/modules/5.10.121 -m ipmi-devintf
Segmentation fault (core dumped)
```
```bash
(gdb) b install_dependent_modules
Breakpoint 1 at 0x7db0: file …
```
=> fix(dracut-install): use stripped kernel module path as hash key

modules.d/01systemd-networkd/module-setup.sh
Typo in `systemd-networkd.socket` local configuration path.
=> fix(systemd-networkd): typo in systemd-networkd.socket local conf path

src/skipcpio/skipcpio.c
If lsinitrd is called from a context in which SIGPIPE is ignored (e.g.,
from a systemd unit with default setting of IgnoreSIGPIPE=), the
following line will result in an error being issued:
bin="$($SKIP "$image" | { read -r -N 6 bin && echo "$bin"; })"
An example error from `kdumpctl start` (which internally just calls
`systemctl start kdump.service`):
kdumpctl[1287]: ERROR: src/skipcpio/skipcpio.c:191:main(): fwrite
A minimal reproducer:
systemd-run -t sh -c '/path/to/skipcpio /path/to/any/file | false'
=> fix(skipcpio): ignore broken pipe

dracut-initramfs-restore.sh
With the current "try and fail" approach, the system log contains errors until
the correct initrd compression is reached.
E.g. extra error log produced by a zstd compressed initrd, until the right option is reached:
```
Aug 17 09:42:18 localhost.localdomain dracut-initramfs-restore[6670]: gzip: stdin: not in gzip format
Aug 17 09:42:18 localhost.localdomain dracut-initramfs-restore[6671]: cpio: premature end of archive
Aug 17 09:42:18 localhost.localdomain dracut-initramfs-restore[6669]: ERROR: src/skipcpio/skipcpio.c:191:main(): fwrite
Aug 17 09:42:18 localhost.localdomain dracut-initramfs-restore[6675]: bzcat: (stdin) is not a bzip2 file.
Aug 17 09:42:18 localhost.localdomain dracut-initramfs-restore[6674]: ERROR: src/skipcpio/skipcpio.c:191:main(): fwrite
Aug 17 09:42:18 …
```
=> fix(dracut-initramfs-restore.sh): hide unpack errors

modules.d/95nfs/nfs-start-rpc.sh, modules.d/95virtiofs/mount-virtiofs.sh, modules.d/99base/dracut-lib.sh
Check first for fs support in `/proc/filesystems` before attempting
to load the kernel module.
This is needed in the --no-kernel use case to avoid the error:
modprobe: FATAL: Module overlay not found in directory /lib/modules/<kver>
=> fix(nfs,virtiofs): check kernel for builtin fs drivers

shell-completion/bash/dracut
Add missing `-p` and `--parallel` options introduced in commit https://github.com/dracutdevs/dracut/commit/6d92326201014cde9ab04b90367017f875d3b991
=> fix(shell-completion): add missing -p and --parallel options

test/TEST-02-SYSTEMD/test.sh, test/TEST-03-USR-MOUNT/test.sh, test/TEST-04-FULL-SYSTEMD/test.sh, test/TEST-10-RAID/test.sh, test/TEST-11-LVM/test.sh, test/TEST-12-RAID-DEG/test.sh, test/TEST-13-ENC-RAID-LVM/test.sh, test/TEST-14-IMSM/test.sh, test/TEST-15-BTRFSRAID/test.sh, test/TEST-17-LVM-THIN/test.sh, test/TEST-20-NFS/test.sh, test/TEST-30-ISCSI/test.sh, test/TEST-35-ISCSI-MULTI/test.sh, test/TEST-40-NBD/test.sh, test/TEST-50-MULTINIC/test.sh, test/TEST-60-BONDBRIDGEVLANIFCFG/test.sh
rootfs-block module would always include the following
modules: udev-rules base fs-lib
This is a follow-up to a1d4041cee5f7b2d8da9192338d5e81315e758ef
=> test: list only the required modules explicitly

dracut.sh
- Use logger functions instead of `printf`: `dracut-logger` is sourced in `dracut-init`, so any `printf` calls after sourcing `dracut-init` should be replaced with logger functions.
- Remove duplicate "_dracut:_" string in logger functions: `dracut-logger` functions already prepend the "_dracut:_" prefix to the message, so avoid the ugly "_dracut: dracut:_ " log entries.
=> Minor log fixes

.github/workflows/manualtest.yml
This workflow allows it to run any of the 29 tests
on any of the 4 containers.
On commit, currently the CI only runs 24 tests out of the 116
possible combinations of test runs.
As the project grows, the usefulness of this tool will also grow.
=> ci: add workflow for manual test run

modules.d/00systemd/module-setup.sh
`sys-kernel-config.mount` needs `modprobe@configfs.service` since systemd v246.7 (https://github.com/systemd/systemd/commit/42cc2855), so the kernel configfs fails to mount in the initrd.
=> fix(systemd): add missing modprobe@.service

modules.d/99base/dracut-lib.sh
Use parameter expansion default value if the second argument is missing. The current code mistakenly reuses the null second argument.
- [✔] I have tested it locally
=> fix(load_fstype): use $1 if $2 is missing

modules.d/10i18n/module-setup.sh
If the `FONT` option defined in `/etc/vconsole.conf` refers to a file with its
extension, not just the file name, dracut should not fail and install it. The
`systemd-vconsole-setup` service ends up calling `setfont`, which supports both file
names and files with extensions.
Example:
```
FONT=b.fnt
-rw-r--r-- 1 root root 4096 Aug 24 15:21 /usr/share/kbd/consolefonts/b.fnt
dracut-install: ERROR: installing '/usr/share/kbd/consolefonts/b.fnt.*'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.K4WIyf/initramfs /usr/share/kbd/consolefonts/b.fnt.*
```
=> fix(i18n): do not fail if FONT in /etc/vconsole.conf has the file extension

modules.d/00systemd/module-setup.sh
`systemd-sysroot-fstab-check` is a symlink to `systemd-fstab-generator` added in
systemd commit https://github.com/systemd/systemd/commit/cd7ad0cb
systemd has a temporary patch until dracut installs it (https://github.com/systemd/systemd/commit/db527621)
=> feat(systemd): install systemd-sysroot-fstab-check

dracut.sh
feat(dracut.sh): populate uefi_cmdline if no other cmdline is given
When creating uefi image in hostonly mode (with using --hostonly-cmdline),
it makes sense to copy current kernel commandline from /proc/cmdline,
in case there are no other options specified.
Usually, the cmdline.d/*.conf file is generated by module rootfs-block
(or other modules), but it might, not handle all cases correctly,
and specifying --kernel-cmdline every time is not much user-friendly.
`/proc/cmdline` will be used as a last option for for uefi `.cmdline` entry.
__TBD__
**TODO: document this**
Shouldn't be probably needed/desired to test this, as the host `/proc/cmdline` would need to be remounted.
=> feat(dracut.sh): populate uefi_cmdline if no other cmdline is given

dracut-init.sh, dracut.sh, modules.d/99squash/module-setup.sh
Even after commit dc21638c3f0a, kdump kernel could still crash when the CPU is reconfigured to run in compatibility mode of older CPU version. Fix it.
=> fix(squash): build ld cache for squash loader

.github/workflows/container.yml
Login to GitHub Container Registry as the actor instead of the repository owner.
Upgrade to login-action@v2 and build-push-action@v3 Github Actions.
Fixes: #1865
=> ci: improve CI for containers

modules.d/99base/module-setup.sh
Silence the printing out root entry of passwd file
while including base module.
dracut: *** Including module: base ***
root:x:0:0:root:/root:/bin/bash
dracut: *** Including module: fs-lib ***
=> chore(base): do not output root entry while installing base

modules.d/95udev-rules/load-modules.sh, modules.d/95udev-rules/module-setup.sh
Arch linux no longer needs a special load-modules.sh file.
Seems this is one of those temporary workarounds from 2010 that for a long time no longer needed - https://github.com/dracutdevs/dracut/commit/5a4bbf1bda2a93452bba254f5adbb4c1c5276230
=> chore(udev-rules): remove obsolete code

modules.d/99base/dracut-lib.sh
remove duplicate implementation of `str_replace` to follow-up
commit 148e420be5b5809aa8d5033f47477573bbbf3e60
Fixes #
=> refactor(base): remove `str_replace` from `dracut-lib.sh`

test/TEST-20-NFS/dhcpd.conf, test/TEST-20-NFS/hosts, test/TEST-20-NFS/test.sh
Remove a workaround for systemd v230
Remove some more dead code.
Improve style and formatting.
Remove duplicated modules.
=> test(NFS): remove a workaround for systemd v230

test/TEST-16-DMSQUASH/create-root.sh, test/TEST-16-DMSQUASH/test.sh
Add a test for mounting root filesystem with overlay for /dev/sdb.
The existing test was testing mounting root filesystem with overlay
from a squashfs image file.
=> test(DMSQUASH): add test for overlay on top of a block device

dracut.sh, modules.d/01systemd-networkd/module-setup.sh, modules.d/01systemd-timesyncd/module-setup.sh, modules.d/35network-legacy/module-setup.sh, modules.d/35network-manager/module-setup.sh
`systemdsystemconfdir` usually expands to /etc/systemd/system, but the local
configuration of systemd-networkd, systemd-timesyncd, portablectl and systemd
users is saved into directories whose parent is /etc/systemd
(`systemdutilconfdir`).
This error went unnoticed because these four variables are not being used anywhere in the code.
=> fix(dracut.sh): correct wrong systemd variable paths

dracut-init.sh
The `_hostonly_install` variable is declared local in some `inst` functions that
check for the existance of the source files, but not in the `inst_multiple`
function because it is not needed.
=> fix(dracut-init.sh): add missing hostonly code in the inst_multiple function

test/TEST-01-BASIC/test.sh, test/TEST-02-SYSTEMD/test.sh, test/TEST-03-USR-MOUNT/test.sh, test/TEST-10-RAID/test.sh, test/TEST-11-LVM/test.sh, test/TEST-12-RAID-DEG/test.sh, test/TEST-13-ENC-RAID-LVM/test.sh, test/TEST-14-IMSM/test.sh, test/TEST-15-BTRFSRAID/test.sh, test/TEST-17-LVM-THIN/test.sh
Notice that TEST-04 does not bring up networking interface as
it is not needed. Apply the same principle for all local tests
that do not need networking.
This should make the tests run faster and slightly more reliable.
This change also brings us to a better place where network-legacy
files are only gets included via proper dracut module inclusion.
=> test: do not bring up the network interface if it is not needed

test/TEST-02-SYSTEMD/systemd-analyze.sh, test/TEST-02-SYSTEMD/test.sh
Document the reason of the existing workaround.
Move the existing logic to the initramfs.testing generation phase
and make the steps more generic.
=> test(SYSTEMD): make the man command succeed

.github/workflows/container.yml
After https://github.com/dracutdevs/dracut/commit/b96f1afa4de8d5e4892a96a5047ab7de1f70924d the scheduled container builds (CI jobs) are running under haraldh. I was expecting that these scheduled runs would run under "dracutdevs" as the github.actor instead of haraldh
CI jobs should login in and push containers as github.repository_owner instead of github.actor.
=> ci: login and push containers as repository_owner

man/dracut.cmdline.7.asc, modules.d/40network/net-lib.sh, modules.d/95nvmf/module-setup.sh, modules.d/95nvmf/parse-nvmf-boot-connections.sh
A series of minor (but important) changes for NVMeoF boot. Re-spin of the previous PR.
Antonio Alvarez Feijoo (1):
fix(nvmf): nvme list-subsys prints the address using commas as separator
Martin Wilck (12):
fix(nvmf): don't try to validate network connections in cmdline hook
fix(nvmf): no need to load the nvme module
fix(nvmf): don't create did-setup file
fix(nvmf): don't use "finished" queue for autoconnect
fix(nvmf): make sure "rd.nvmf.discover=fc,auto" takes precedence
fix(nvmf): avoid calling "exit" in a cmdline hook
fix(nvmf): run cmdline hook before parse-ip-opts.sh
fix(network): don't use same ifname multiple times
fix(man): dracut.cmdline(7): correct syntax for rd.nonvmf
feat(nvmf): set rd.neednet=1 if tcp records encountered
fix(network): avoid double brackets around IPv6 address …
=> Nvmf fixes

pkgbuild/dracut.spec
tpm2-tools dependency can be can be pulled in case tmp2-tss package is installed, using a soft conditional dependency.
https://bugzilla.redhat.com/show_bug.cgi?id=2077697
=> tpm2-tools is required for crypt module to work

.github/workflows/manualtest.yml, docs/HACKING.md, man/dracut.cmdline.7.asc, modules.d/90dmsquash-live-autooverlay/create-overlay-genrules.sh, modules.d/90dmsquash-live-autooverlay/create-overlay.sh, modules.d/90dmsquash-live-autooverlay/module-setup.sh, pkgbuild/dracut.spec, test/TEST-16-DMSQUASH/create-root.sh, test/TEST-16-DMSQUASH/test-init.sh, test/TEST-16-DMSQUASH/test.sh, test/container/Dockerfile-Arch, test/container/Dockerfile-Debian, test/container/Dockerfile-Fedora-latest, test/container/Dockerfile-Gentoo, test/container/Dockerfile-OpenSuse-latest
This pull request introduces a new module that creates a partition for overlayfs usage in the free space on the root filesystem's parent block device.
Ubuntu 20.04 (the `main` branch) and Fedora 36 (the `fedora-36` branch) Kiwi image descriptions that produce ISO images that demonstrate this feature are available in this repository:
https://github.com/iammattcoleman/overlay-test
=> Add new dmsquash-live-autooverlay module

man/dracut.cmdline.7.asc, modules.d/35network-legacy/dhcp-multi.sh, modules.d/35network-legacy/ifup.sh
It seems dhclient's `--timeout` option is not upstream [1], apparently it's RH-only [2]..., so a pre-check is needed before using it.
[1] https://github.com/isc-projects/dhcp
[2] https://github.com/landgraf/dhcp-fedora/commit/d171ac96
Some tests already take this into account:
https://github.com/dracutdevs/dracut/blob/fe8fa2b0cadbb33e27c8dd8b5851548dcd65835c/test/TEST-20-NFS/test.sh#L73-L75
https://github.com/dracutdevs/dracut/blob/fe8fa2b0cadbb33e27c8dd8b5851548dcd65835c/test/TEST-50-MULTINIC/test.sh#L73-L75
=> fix(network-legacy): check if dhclient has --timeout option

modules.d/99base/dracut-lib.sh, modules.d/99shutdown/shutdown.sh
dracut-lib.sh and the base module now does not have a knowledge
of oldroot and plymouth.
It improves the separation of concerns between the base module
and the shutdown module.
=> refactor(shutdown): move module specific code out of base module

dracut.sh, man/dracut.conf.5.asc
Replace invalid lzo command with `lzop` for LZO compression.
Fixes #1999
=> fix(dracut): replace invalid lzo command with lzop for LZO compression

.kateconfig, src/install/.kateconfig, src/skipcpio/.dir-locals.el, src/skipcpio/.kateconfig
I do not use Kate/KDE.
https://docs.kde.org/trunk5/en/kate/katepart/config-variables.html
says we can use MIME type.
Fixes #
=> chore: remove editor configuration files from subdirectories

modules.d/01systemd-portabled/module-setup.sh, modules.d/01systemd-tmpfiles/module-setup.sh, pkgbuild/dracut.spec
Introducing the `systemd-portabled` module.
It works with raw binary disk images contained in regular files, but it's not intended to work with directory trees, like the `systemd-sysext` module.
=> feat(systemd-portabled): introducing the systemd-portabled module

modules.d/90kernel-modules/module-setup.sh
Paraphrasing Debian#1017411:
In searching for low-hanging time fruit, I found that 90kernel-modules does
```bash
find_kernel_modules_external() {
local a
[[ -f "$srcmods/modules.dep" ]] || return 0
while IFS=: read -r a _ || [[ $a ]]; do
[[ $a =~ ^/ ]] && printf "%s\n" "$a"
done < "$srcmods/modules.dep"
}
find_kernel_modules_external | instmods
```
which after shedding the bashisms is
```sh
grep ^/ "$srcmods/modules.dep" 2> /dev/null | cut -d: -f1 | instmods
```
or
```sh
awk -F: '/^\// {print $1}'  "$srcmods/modules.dep" 2> /dev/null | instmods
```
so
```sh
$ find_kernel_modules_external() {
>     local a
> 
>     [[ -f "$srcmods/modules.dep" ]] || return 0
> 
>     while IFS=: read -r a _ || [[ $a ]]; do
>         [[ $a =~ ^/ ]] && printf "%s\n" "$a"
>     done < "$srcmods/modules.dep"
> …
```
=> perf(90kernel-modules): use AWK instead of shell monster

modules.d/90multipath/module-setup.sh
This pull request makes `90multipath` module install `multipathd.socket` from system paths along side with the systemd service unit (which lists the socket as a dependency). Without the socket unit file, systemctl invoked by dracut may report `failed to enable unit` during generation, and the resulting initrd will not have a usable multipathd at early boot.
Fixes #
=> 90multipath: install multipathd.socket

modules.d/99base/init.sh, modules.d/99base/module-setup.sh
RD_TIMESTAMP is no longer used.
systemd-timestamp is not used.
=> chore(base): remove dead code

modules.d/90dmsquash-live/dmsquash-generator.sh, modules.d/90dmsquash-live/dmsquash-live-root.sh, modules.d/90dmsquash-live/module-setup.sh, test/TEST-16-DMSQUASH/test.sh
Using dash instead of bash saves about 0.5M initramfs size.
Fixes #1897
=> feat(dmsquash-live): add support for dash

dracut-logger.sh
The /dev/log check was not correct, it would continue working if /dev/log was a broken symlink. This changes the logic to be more clear -- /dev/log needs to be a socket, and writable, and logger needs to be available. If any of those conditions fail, turn off syslog and only use console logging.
=> fix(dracut-logger.sh): fix check for /dev/log

dracut-functions.sh
When the rootfs of a virtual machine is virtiofs shared folder, the /etc/fstab file may not exist. As a result, the "findmnt --fstab" will complain "findmnt: can't read (null): No such file or directory" when trying to rebuild kdump initramfs within the vm.
This patch checks if /etc/fstab exist before calling "findmnt --fstab" to suppress the error message.
Before:
$ kdumpctl rebuild
kdump: Rebuilding /boot/initramfs-5.14.0-182.el9.x86_64kdump.img
findmnt: can't read (null): No such file or directory
findmnt: can't read (null): No such file or directory
findmnt: can't read (null): No such file or directory
After:
$ kdumpctl rebuild
kdump: Rebuilding /boot/initramfs-5.14.0-182.el9.x86_64kdump.img
Signed-off-by: Tao Liu <ltao@redhat.com>
- [Y] I have tested it locally
Fixes #
=> fix(dracut-functions.sh): suppress the findmnt error message when /etc/fstab not exist

modules.d/90multipath/module-setup.sh, modules.d/90multipath/multipathd-needshutdown.sh, modules.d/90multipath/multipathd-stop.sh, modules.d/90multipath/multipathd.sh
`dracut-lib.sh` provides a custom version of [pidof](https://github.com/dracutdevs/dracut/blob/master/modules.d/99base/dracut-lib.sh#L875), so there is no need to install the `pidof` binary. Also, source `dracut-lib.sh` in hook scripts when needed.
Fixes #2027
=> refactor(multipath): do not install the pidof binary

modules.d/90kernel-modules/module-setup.sh
The M1/etc hardware has an quirky NVMe disk controller that needs a dedicated NVMe driver. Rather than picking up just that bit of hardware pick up drivers that register NVMe controllers.
This also picks up NVMe-OF style drivers, but seems like a better long term solution on Arm platforms which tend to have a lot of odd hardware.
Signed-off-by: Jeremy Linton <jlinton@redhat.com>
Fixes #
=> fix(90kernel-modules): add (nonstandard) NVMe drivers

modules.d/90qemu/module-setup.sh
This adds a couple 'confidential computing' kernel modules to the qemu driver list. They have generic sounding names, but they are VM specific, and they are used in attestation flows which typical end with unlocking the luks encrypted rootfs, so they need to be available at boot time.
=> Add `efi-secret` to qemu driver list

modules.d/90dmsquash-live-ntfs/module-setup.sh
Remove unnecessary `command -v` called outside of any functions in dmsquash-live-ntfs/module-setup.sh.
=> fix(dmsquash-live-ntfs): remove unnecessary command

dracut-init.sh
It worked most of the time because `dracut-install -o` returns 0 in normal circumstances.
Fixes #
=> fix(dracut-init.sh): instmods: wrong variable name

test/container/Dockerfile-Gentoo
No need to rebuild the Gentoo kernel every day :-) . 
I wish I would have known about about this possibility earlier.
=> ci: use prebuilt Linux kernel binaries for Gentoo container

test/container/Dockerfile-Arch
packages should be installed with -Syu instead of -Sy.
Fixes #
=> ci: fix Arch container

modules.d/90kernel-modules/module-setup.sh
`dracut-systemd` module now will incorporate `sysctl` into initramfs so that modprobe configuration files that call sysctl will function properly.
=> fix(kernel-modules): Add sysctl to initramfs to handle modprobe files

.github/workflows/container.yml, .github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/pr.yml
It resolves the following warning:
Please update the following actions to use Node.js 16: actions/checkout
=> ci: upgrade to actions/checkout@v3

modules.d/98dracut-systemd/dracut-cmdline.sh
Dependencies to systemd .device unit files are marked as "hostonly" in the special file hostonly-files. These .device unit files can be removed using the `rd.hostonly=0` command line parameter. But, since systemd v252 (https://github.com/systemd/systemd/pull/24054), the initrd-parse-etc.service service does not run `systemctl daemon-reload`, so systemd keeps waiting for these .device units to show up.
This means that if a hostonly device is not available for any reason at boot time, using `rd.hostonly=0` has no effect and the system will not boot.
=> fix(base): run systemctl daemon-reload after remove_hostonly_files

man/dracut.usage.asc
There's a deprecated option `rdblacklist` but no `rd.blacklist` as far as I could tell, so this pull request changes the statement of the option name to match the examples given immediately after.
=> docs: correct "rd.blacklist"

test/container/Dockerfile-Arch, test/container/Dockerfile-Debian, test/container/Dockerfile-Fedora-latest, test/container/Dockerfile-Gentoo, test/container/Dockerfile-OpenSuse-latest
mkfs.ntfs is needed to test dmsquash-live-ntfs
=> ci: add ntfs tools to test containers

.github/workflows/container.yml
v2 has node 16 as default runtime.
=> chore(ci): bump docker/setup-buildx-action from 1 to 2

test/TEST-02-SYSTEMD/test.sh, test/TEST-04-FULL-SYSTEMD/test.sh
Dracut tests already do similar checks for test 40, 62, 63 and 98.
This is useful when the full testsuite is run and systemd is not available.
Run with this PR on Gentoo: https://github.com/LaszloGombos/dracut/actions/runs/3455893330/jobs/5768235202
make[1]: Entering directory '/__w/dracut/dracut/test/TEST-04-FULL-SYSTEMD'
TEST: Full systemd serialization/deserialization test with /usr mount   [SKIPPED] 
make[1]: Leaving directory '/__w/dracut/dracut/test/TEST-04-FULL-SYSTEMD'
=> test: explicitly check if systemctl is available for systemd tests

modules.d/99base/dracut-lib.sh
The base module requires `grep` with the `rd.memdebug=1` command line parameter. As this code is broken if `grep` is not added by other means and `grep` is only required for this, rewriting this code to avoid the dependency.
```
BOOT_IMAGE=/boot/vmlinuz-5.19.2-1-default root=UUID=7fc47d56-42d7-4f0e-9e31-58ea3e4d8158 splash=silent mitigations=auto quiet security=apparmor rd.memdebug=1
Nov 30 12:02:16 localhost dracut-pre-udev[297]: [debug_mem] hook pre-udev
Nov 30 12:02:16 localhost dracut-pre-udev[299]: /lib/dracut-lib.sh: line 1132: grep: command not found
--
Nov 30 12:02:16 localhost dracut-initqueue[340]: [debug_mem] hook initqueue
Nov 30 12:02:16 localhost dracut-initqueue[345]: /lib/dracut-lib.sh: line 1132: grep: command not found
--
Nov 30 12:02:17 localhost dracut-pre-mount[435]: …
```
=> fix(base): remove grep dependency

dracut.sh
DRACUT_ARCH overrides `uname -m` since https://github.com/dracutdevs/dracut/commit/a0120420
=> fix(dracut.sh): use DRACUT_ARCH instead of `uname -m`

modules.d/01systemd-coredump/module-setup.sh
This issue went unnoticed because the systemd module always installs the systemd-coredump binary using the right path.
https://github.com/dracutdevs/dracut/blob/fd9cd02cb21f25d32fec4cd9889457ea6361f45e/modules.d/00systemd/module-setup.sh#L35
=> fix(systemd-coredump): correct systemd-coredump binary path

modules.d/95debug/module-setup.sh, modules.d/98selinux/module-setup.sh, modules.d/99base/module-setup.sh
dracut can be invoked inside a chroot, but inside
the generated initramfs the chroot binary is not required.
Fixes #
=> fix(base): do not require chroot inside initramfs

docs/RELEASE.md
Release tarballs are only available on github from now on.
Fixes #1837
Somewhat related: https://github.com/dracutdevs/dracut/issues/1850
=> docs: document the new release process

test/container/Dockerfile-Fedora-latest, test/container/Dockerfile-OpenSuse-latest
The installed packaged dracut version from distributions can interfere with testing latest dracut from source, which is the primary goal of these containers.
I was not able to uninstall the full dracut package in the openSUSE container, as sadly would also uninstall the mdadm package. Fedora does not have this dependency.
=> ci: remove native dracut installation from the test containers

.github/workflows/integration.yml
GitHub Actions allow to opt-in to more debug logging both on web UI and on the command line.
When GitHub Action debug logging is enabled also enable additional dracut test debugging by setting DEBUGFAIL to rd.debug.
This is particularly useful when re-run failed jobs with debug logging enabled.
GiHub documentation for this: https://github.blog/changelog/2022-05-24-github-actions-re-run-jobs-with-debug-logging/
This is how the WebUI looks like for enabling debug logging for dracut:
=> ci: set DEBUGFAIL to rd.debug when debug logging is enabled

test/container/Dockerfile-Fedora-latest
Fixes regression caused by https://github.com/dracutdevs/dracut/commit/bf545567aba244b13eac08491b1fdc3e1bc42aa9 . Regression is only for Fedora container and only for networking tests.
=> ci: install procps-ng into Fedora container

modules.d/01fips/fips.sh, modules.d/01fips/module-setup.sh, modules.d/35connman/netroot.sh, modules.d/35network-legacy/dhcp-multi.sh, modules.d/35network-legacy/ifup.sh, modules.d/35network-legacy/net-genrules.sh, modules.d/40network/net-lib.sh, modules.d/40network/netroot.sh, modules.d/45ifcfg/write-ifcfg.sh, modules.d/80cms/cms-write-ifcfg.sh, modules.d/90dm/dm-shutdown.sh, modules.d/90dmsquash-live-autooverlay/create-overlay.sh, modules.d/95fcoe/fcoe-up.sh, modules.d/95iscsi/iscsiroot.sh, modules.d/95iscsi/module-setup.sh, modules.d/95lunmask/fc_transport_scan_lun.sh, modules.d/95lunmask/module-setup.sh, modules.d/95lunmask/sas_transport_scan_lun.sh, modules.d/95nfs/nfsroot-cleanup.sh, modules.d/95nvmf/module-setup.sh, modules.d/95rootfs-block/mount-root.sh, modules.d/97masterkey/masterkey.sh, modules.d/98ecryptfs/ecryptfs-mount.sh, modules.d/98integrity/evm-enable.sh, modules.d/98usrmount/mount-usr.sh, modules.d/99base/dracut-lib.sh
This pull request changes bad style `var=$(cat <file>)`. Replace by `read -r var < file`
Fixes #2093
=> refactor: use read -r instead of cat

test/container/Dockerfile-Arch, test/container/Dockerfile-Fedora-latest
Add systemd-networked to Fedora container.
Add connman to Arch container.
This change enables manual testing of various network configurations and also allows the ci to ensure that having additional networking packages installed does not break the network meta module.
=> ci: introduce more networking options into test containers

dracut-init.sh, dracut.sh
If the `DRACUT_INSTALL` environment variable contains arguments (e.g.: `DRACUT_INSTALL="/usr/lib/dracut/dracut-install --debug"`), its call cannot be enclosed in double quotes. E.g.:
```
> export DRACUT_INSTALL="/usr/lib/dracut/dracut-install"
> "$DRACUT_INSTALL" > /dev/null
dracut-install: No SOURCE argument given
> export DRACUT_INSTALL="/usr/lib/dracut/dracut-install --debug"
> "$DRACUT_INSTALL" > /dev/null
-bash: /usr/lib/dracut/dracut-install --debug: No such file or directory
> $DRACUT_INSTALL > /dev/null
dracut-install: No SOURCE argument given
```
=> fix(dracut): shellcheck regression in DRACUT_INSTALL calls

test/TEST-04-FULL-SYSTEMD/test.sh, test/TEST-20-NFS/test.sh, test/TEST-30-ISCSI/test.sh, test/TEST-35-ISCSI-MULTI/test.sh, test/TEST-40-NBD/test.sh, test/TEST-50-MULTINIC/test.sh
It should not be necessary to explicitly omit dash module during test runs. If this is needed, that would mean that bash is not marked as an explicit dependency for some modules.
=> test: do not omit dash module

test/TEST-20-NFS/test.sh, test/TEST-30-ISCSI/test.sh, test/TEST-35-ISCSI-MULTI/test.sh
This makes the the tests more consistent, run faster by default and less likely to timeout on the CI.
This is a follow-up to https://github.com/dracutdevs/dracut/commit/d0a5b039dd02400d4203717c4cfa45dcd369845c. Without these changes enabling debugging on Github does not really taken into effect as the test case itself overwrites the DEBUGFAIL variable.
=> test: disable debug logs by default

modules.d/90dm/module-setup.sh, modules.d/90lvm/module-setup.sh, test/TEST-17-LVM-THIN/create-root.sh
devicemapper in the initramfs built on at least Ubuntu 20.04 will currently warn about
libdevmapper-event-lvm2thin.so dlopen failed:
libdevmapper-event-lvm2.so.2.03:
cannot open shared object file: No such file or directory
libdevmapper-event-lvm2.so.2.03 does not have a .so link pointing to it, so it gets missed by the existing
'inst_libdir_file "libdevmapper-event-lvm*.so"'
liblvm2cmd.so.2.03 is a dependency of libdevmapper-event-lvm2.so.2.03. It must be added directly because dracut-install does not resolve library dependencies, it only works for executables. Since dm-eventd dlopen's everything there
is no executable that would cause dracut-install to resolve this.
Fixes #
=> Drop dmeventd from initramfs

modules.d/01systemd-timesyncd/module-setup.sh
System service and conf already installed above:
https://github.com/dracutdevs/dracut/blob/fd9cd02cb21f25d32fec4cd9889457ea6361f45e/modules.d/01systemd-timesyncd/module-setup.sh#L44-L45
=> fix(systemd-timesyncd): typo in systemd-time-wait-sync.service local conf path

dracut.sh
This directory is always needed to store files like `modules.txt` and `build-parameter.txt`, so always create it, but only in one place.
=> perf(dracut.sh): do not mkdir $initdir/lib/dracut within a loop

modules.d/90dmsquash-live-ntfs/module-setup.sh, modules.d/90dmsquash-live-ntfs/mount-ntfs-3g.sh, modules.d/90dmsquash-live/dmsquash-live-root.sh
Since the installation of ntfs-3g binary is in the
dmsquash-live-ntfs module, calling ntfs-3g from dmsquash-live fails
when dmsquash-live-ntfs module is not installed anyways.
=> refactor(dmsquash-live): move ntfs-3g code to dmsquash-live-ntfs

.github/workflows/integration.yml
This PR runs the local tests not only on fedora but on all 4 systemd enabled containers.
This PR increases the number of test runs from 32 to 71 (more than double).This sounds quite scary but tests do run in parallel, so it does not actually increases the time to finish running all the tests.
If this for some reason becomes a problem, we can always ration and discuss what is important to run and what gives the project most test coverage, but perhaps as a start we can try with the full "local" matrix.
All tests are passing except test 17 on debian. Test 17 on debian is fixed by https://github.com/dracutdevs/dracut/pull/2028 .
=> ci: run all local tests on systemd enabled containers

dracut.sh, man/dracut.8.asc, man/dracut.conf.5.asc
Currently, dracut only allows to configure the persistent policy to address
disks and partitions using any directory name found in `/dev/disk`, but there is
no defined way to set the default policy based on `/dev/mapper` device names. So,
for example, if the persistent policy is set by the distribution in any
configuration file, the user cannot set the default if he wants to.
The current workaround is to set `persistent_policy=""` in a conf file or pass
`--persistent-policy " "` (white space) as an argument. This patch aims to
establish a specific value for this case.
=> fix(dracut): allow to set persistent policy based on /dev/mapper device names

dracut-functions.sh, modules.d/91zipl/module-setup.sh
Trailing spaces are misleading blkid input after fixes for shellcheck were introduced in https://github.com/dracutdevs/dracut/commit/d75b029a
Test showing the wrong output:
```
localhost:~ # _boot_zipl=$(sed -n -e '/^[[:space:]]*#/d' -e 's/\(.*\)\w*\/boot\/zipl.*/\1/p' /etc/fstab)
localhost:~ # echo "[${_boot_zipl}]"
[/dev/disk/by-path/ccw-0.0.0000-part1  ]
localhost:~ # blkid -s TYPE -o udev "${_boot_zipl}"
localhost:~ # blkid -s TYPE -o udev ${_boot_zipl}
ID_FS_TYPE=ext2
```
Also, remove duplicate code by creating a function to get the zipl boot device, prepend `$dracutsysrootdir` to /etc/fstab and print cmdline properly: start with a space and do not print a newline.
=> fix(zipl): remove trailing spaces from zipl boot device name

modules.d/01systemd-hostnamed/systemd-hostname-dracut.conf
Lines of type 'g' don't take a GECOS field.
```
Dec 22 10:27:28 sd-net-test systemd-sysusers[198]: /usr/lib/sysusers.d/systemd-hostname-dracut.conf:2: Lines of type 'g' don't take a GECOS field.
```
=> fix(systemd-hostnamed): correct sysusers configuration

modules.d/06dbus-broker/module-setup.sh
If `dbus.socket` is not started automatically in the initrd, all binaries that require dbus to work fail.
E.g.:
```
sh-5.2# networkctl 
Failed to connect system bus: No such file or directory
sh-5.2# resolvectl 
sd_bus_open_system: No such file or directory
sh-5.2# systemctl status dbus.socket
○ dbus.socket - D-Bus System Message Bus Socket
Loaded: loaded (/usr/lib/systemd/system/dbus.socket; static)
Active: inactive (dead)
Triggers: ● dbus-broker.service
Listen: /run/dbus/system_bus_socket (Stream)
sh-5.2# systemctl start dbus.socket
sh-5.2# networkctl 
IDX LINK   TYPE     OPERATIONAL SETUP     
1 lo     loopback carrier     unmanaged
2 enp1s0 ether    routable    configured
2 links listed.
sh-5.2# resolvectl 
Global
Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf …
```
=> fix(dbus-broker): add missing sockets.target.wants/dbus.socket

modules.d/01systemd-hostnamed/module-setup.sh
Without this service, `hostnamectl` fails to run in the initrd.
```
sh-5.2# hostnamectl
Failed to query system properties: Could not activate remote peer: activation request failed: unknown unit.
sh-5.2# systemctl status dbus | grep hostname
Dec 22 11:07:56 sd-net-test dbus-broker-launch[216]: Activation request for 'org.freedesktop.hostname1' failed: The systemd unit 'dbus-org.freedesktop.hostname1.service' could not be found.
```
=> fix(systemd-hostnamed): add missing dbus-org.freedesktop.hostname1.service

modules.d/01systemd-timedated/module-setup.sh
Without this service, `timedatectl` fails to run in the initrd.
```
sh-5.2# timedatectl
Failed to query server: Could not activate remote peer: activation request failed: unknown unit.
sh-5.2# systemctl status dbus | grep timedate
Dec 22 13:57:03 sd-net-test dbus-broker-launch[219]: Activation request for 'org.freedesktop.timedate1' failed: The systemd unit 'dbus-org.freedesktop.timedate1.service' could not be found.
```
=> fix(systemd-timedated): add missing dbus-org.freedesktop.timedate1.service

modules.d/90dmsquash-live/parse-dmsquash-live.sh
fix a bug introduced in 71cfa2e22
make sure root is set correctly for both of the following cases
- "root=live:/dev/*"
- "rd.live.image root=/dev/*"
=> fix(dmsquash-live): live:/dev/*

modules.d/01fips/fips.sh, modules.d/35network-legacy/parse-ip-opts.sh, modules.d/90mdraid/parse-md.sh, modules.d/95nfs/nfs-lib.sh
Add missing fixes to pass shellcheck 0.8.0.
```
find . -name '*.sh' -print0 | xargs -0 shellcheck
0
```
=> fix: shellcheck 0.8.0

.github/workflows/integration.yml
Test 50 (MULTINIC) seems to be the only test that prevents the project from having an all passing continuous integration test suite.
=> ci: disable test 50 (MULTINIC)

test/container/Dockerfile-Gentoo
Started failing on Jan-9 - https://github.com/dracutdevs/dracut/actions/runs/3873354892/jobs/6603276560.
Jan-8 the container was building without any error - https://github.com/dracutdevs/dracut/actions/runs/3866857299/jobs/6591253021
This is a regression caused by Gentoo upstream changes and not Dracut commits.
=> ci: fix Gentoo container used for testing

modules.d/95virtiofs/mount-virtiofs.sh
The `die` function already ends with `exit 1`.
Spotted and missing in #2124
=> refactor(virtiofs): remove exit after die

dracut.sh
Both are valid options that cause regular program termination without errors, so dracut should return 0.
=> fix(dracut.sh): correct --help and --version exit codes

dracut-init.sh
=> fix(dracut-init.sh): correct typo in comment

modules.d/90lvm/module-setup.sh
This patch adds all the kernel modules that might be needed by LVM, to avoid having to rebuild the initrd in hostonly mode after a dynamic change that requires new drivers to boot.
For example, LVM allows to dynamically convert a linear logical volume to a RAID-1 type (`lvconvert --type raid1 vg/lv`), which, in hostonly mode, will require the user to manually rebuild the initrd again to include the new RAID drivers in use, otherwise the system will fail to boot.
Identified kernel modules used by LVM (CC: @zhaohem @teigland): all in `drivers/md/*`, excluding `bcache` directory and `md-cluster.ko`.
The size increase is approx. +1MB (using zstd compression):
```
localhost:~ # ls -l initrd-6.0.7-1-default-*
-rw------- 1 root root 22675622 Dec 13 14:43 initrd-6.0.7-1-default-before
-rw------- …
```
=> RFC: feat(lvm): always include all drivers that LVM can use

modules.d/98dracut-systemd/rootfs-generator.sh
The `generator_wait_for_dev` function of the dracut rootfs systemd generator only uses the first argument. Moreover, `RDRETRY` is unset at this point.
=> fix(dracut-systemd): remove unused argument

lsinitrd.sh
Printing and unpacking of specific files passed as arguments does not work if their filenames contain special characters with a hexadecimal character escape (`\x`), which is often the case with systemd device units.
E.g. before the patch:
```
-rw-r--r--   1 root     root           46 Dec 14 16:14 etc/systemd/system/dev-disk-by\x2duuid-52A8\x2dA0F6.device.d/timeout.conf
cat: 'etc/systemd/system/dev-disk-by\x2duuid-52A8\x2dA0F6.device.d/timeout.conf': No such file or directory
[Unit]
JobTimeoutSec=0
JobRunningTimeoutSec=0
```
After the patch:
```
drwxr-xr-x   2 root     root            0 Dec 14 16:14 etc/systemd/system/dev-disk-by\x2duuid-52A8\x2dA0F6.device.d
-rw-r--r--   1 root     root           46 Dec 14 16:14 etc/systemd/system/dev-disk-by\x2duuid-52A8\x2dA0F6.device.d/timeout.conf …
```
=> fix(lsinitrd.sh): handle filenames with special characters

dracut-init.sh
Do not print the same error message for both situations.
Also, remove redundant "dracut" from "dracut module" prints, similiar to "Including module" prints.
```
dracut: Module 'tpm2' cannot be found.
dracut: Module 'tpm2-tss' cannot be installed.
```
=> feat(dracut-init.sh): specify if a module cannot be found or cannot be installed

dracut.sh
When `$dracutsysrootdir` is set and references an existing directory, the internal global variables are never set, unless their value is assigned via configuration file (first reported in stalled PR #1975).
The simple fix would be turn all:
```sh
[[ -d $dracutsysrootdir$var ]] || var=value
```
into:
```sh
[[ -z $var || ! -d $dracutsysrootdir$var ]] && var=value
```
But this patch also includes a refactoring, removing duplicate code using the same `set_global_var` function to set and export global variables, and improving readability.
=> fix(dracut.sh): --sysroot option broken if global variables not set in conf

modules.d/90dmsquash-live/iso-scan.sh
Added a call to `udevadm trigger` needed on linux 5.19+ due to a change in how udev events are triggered when loop devices are added.
The exact line is taken from the [fips module](https://github.com/dracutdevs/dracut/blob/master/modules.d/01fips/fips.sh#L32) as suggested in #2183 
(I don't think documentation updates apply here)
Is this something that needs tests? Not sure how to go about creating tests
Fixes #2183
=> fix: make iso-scan trigger udev events

src/install/dracut-install.c
When the kernel is compiled without IA32_EMULATION and the glibc 32-bit library is installed on the system, `ldd` prints the following output:
```
> ldd /usr/lib64/libfido2.so.1.12.0
/bin/ldd: line 162: /lib/ld-linux.so.2: cannot execute binary file: Exec format error
linux-vdso.so.1 (0x00007ffd627fa000)
libcbor.so.0.9 => /lib64/libcbor.so.0.9 (0x00007f18d799f000)
libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f18d7400000)
libudev.so.1 => /lib64/libudev.so.1 (0x00007f18d7971000)
libhidapi-hidraw.so.0 => /lib64/libhidapi-hidraw.so.0 (0x00007f18d7968000)
libz.so.1 => /lib64/libz.so.1 (0x00007f18d794e000)
libc.so.6 => /lib64/libc.so.6 (0x00007f18d7205000)
/lib64/ld-linux-x86-64.so.2 (0x00007f18d79f9000)
> echo $?
0
```
The `ldd` script uses the following code to resolve dependencies:
``` …
```
=> fix(dracut-install): continue parsing if ldd prints "cannot execute binary file"

modules.d/91fido2/module-setup.sh
See https://github.com/Yubico/libfido2/blob/main/CMakeLists.txt#L404 and https://github.com/Yubico/libfido2/commit/bf7ea459cf5a805a36202d923c1be7c1140288bc
Fixes #2048
=> fix(fido2): libfido2.so depends on libz.so

modules.d/35network-manager/nm-initrd.service
During shutdown, there is no ordering dependency between the nm-initrd service and the D-Bus daemon, and so the latter can be stopped before. This causes issues to NetworkManager, especially when team interfaces are present because NM will see teamd dropping from the bus and will try to reactivate the connection.
Add a `After` dependency to make sure the D-Bus daemon is stopped after NM on shutdown.
=> fix(network-manager): add "After" dependency on dbus.service

modules.d/95resume/module-setup.sh
Instead of the strict `/sys/power/resume` requirement which is not met by some broken setups.
Don't consider noresume to disable, that's a single-boot debug flag
Closes #924
=> feat(resume): also consider resume= in the cmdline as enabling hibernation

modules.d/50plymouth/plymouth-populate-initrd.sh
/etc/*release files should not be managed in the plymouth module and more importantly dracut assumes /etc/os-release not /etc/system-release
CC @zboszor 
/etc/system-release got introduced in 2009 (in case this helps with the reviews) - https://github.com/dracutdevs/dracut/commit/0f46778162a373afa903f57c7518489dbafb87a7#diff-a8af7c75c2fa972878d519a2ba0e62870206416f73f627ae8414c5d8fb07501bR62
=> fix(plymouth): remove /etc/system-release dependency

dracut-init.sh, modules.d/90dm/59-persistent-storage-dm.rules, modules.d/90dm/module-setup.sh, modules.d/90mdraid/59-persistent-storage-md.rules, modules.d/90mdraid/module-setup.sh, modules.d/95udev-rules/59-persistent-storage.rules, modules.d/95udev-rules/61-persistent-storage.rules, modules.d/95udev-rules/module-setup.sh
This PR reverts 579238a3acd0317d7124a76dc489f19d9471fb63.
Udev 176 was released in 2012. I think it is safe to assume that dracut only supports going back 11 years and not more.
=> chore(base): remove support for <udev-176.

modules.d/01fips/fips-boot.sh, modules.d/01fips/fips-load-crypto.sh, modules.d/01fips/fips-noboot.sh, modules.d/01fips/fips.sh, modules.d/01fips/module-setup.sh
The `mount_boot` method called from fips-noboot.sh in the pre-pivot hook blindly
executes `rm -rf /boot` if there is no `boot=` command line parameter, without
first checking that /boot is not already mounted by other means.
We hit this issue in certain specific circumstances (s390x arch, separate /boot
partition, initrd built with `--mount` to mount /boot and incorrect user
configuration without the `boot=` command line parameter), but this part of the
code must be protected anyway.
```
[   29.932607] dracut-pre-pivot[922]: rm: cannot remove '/boot/boot.readme': Read-only file system
[   29.932814] dracut-pre-pivot[922]: rm: cannot remove '/boot/System.map-5.14.21-150500.34-default': Read-only file system
[   29.932909] dracut-pre-pivot[922]: rm: cannot remove …
```
=> fix(fips): do not blindly remove /boot

src/install/dracut-install.c
Dracut currently finds kernel module dependencies using two methods: depmod and softdeps. However, these are often insufficient on embedded systems where a lot of driver dependencies are only described in the device tree. This is often the case for low-level devices such as clocks, regulators, pinctrls, etc.
This patch series allows dracut to find those device tree dependencies, by parsing the sysfs supplier nodes populated by fw_devlink.
This slows dracut down a little bit, however. Depending on whether dracut is called with `--hostonly` or not, I measured 25-35% slowdown on the Raspberry Pi 4. According to gperftools, most of the extra time is spent in `kmod_module_new_from_lookup()`
v2. Addressed review comments
v3.
- walk the sysfs once
- make sure that if one of the suppliers in a …
=> feat(dracut-install) Add fw_devlink suppliers as module dependencies

modules.d/35network-legacy/module-setup.sh, modules.d/40network/net-lib.sh, modules.d/95iscsi/module-setup.sh
This pull request fixes a few issues I encountered while testing network boot with IPv6.
It prepares a final submission of #2184 (it contains the parts of #2184 which are not related to the nvmf module).
=> Fixes for iSCSI boot & IPv6

dracut.sh
- `sbsign` does not issue any error if there is not enough disk space to create
the signed file using its `--output` option. So, verify the signed image after
its creation using `sbverify`.
```
dracut: *** Creating image file '/tmp/tmp.YC4iYlF8UF/test.img' ***
dracut: Using UEFI kernel cmdline:
dracut: rd.driver.pre=btrfs  resume=UUID=3c21ec01-f8e7-4b9e-a7e7-26c050fee9ec  root=UUID=bc1664be-7f7e-48d1-8e99-25d9a98c8e3c rootfstype=btrfs rootflags=rw,relatime,discard=async,space_cache=v2,subvolid=266,subvol=/@/.snapshots/1/snapshot,subvol=@/.snapshots/1/snapshot 
warning: data remaining[88700416 vs 88712928]: gaps between PE/COFF sections?
Signing Unsigned original image
/bin/dracut: line 2676: 30903 Segmentation fault      (core dumped) sbverify --cert "${uefi_secureboot_cert}" "$outfile" > …
```
=> fix(dracut.sh): handle out of space error for UEFI builds

modules.d/35network-manager/nm-run.sh
This reverts commit 77630365aed201a729c73a9ffda0733a75f3fee4.
Its commit message states:
```
On EL8.3 the NetworkManager keep restarting even if it exits successfully
while waiting for Clevis to unlock. This patch ensures NetworkManager runs
only once in initrd.
```
Yes; NetworkManager is run multiple times, so that it's able to configure interfaces that haven't been seen previously (because bus was slow to scan or device took time to initialize).
It's not clear what problem was the original commit trying to fix. I suspect there was no problem, just a misunderstanding.
=> Revert "fix(35network-manager): avoid restarting NetworkManager"

modules.d/95udev-rules/module-setup.sh
**1./ Debian rules**
`50-udev.rules` `95-late.rules` added in [2009](https://github.com/dracutdevs/dracut/commit/f2b44e351bb181e3b2b689cdf42dd6314c11454f) .
`91-permissions.rules` added in [2013](https://github.com/dracutdevs/dracut/commit/5decf6d81362ee1903da1400744061b999263df9)
The last [Debian release](https://www.debian.org/releases/) that carried `91-permissions.rules` is [wheezy](https://www.apt-browse.org/browse/debian/wheezy/main/amd64/udev/175-7.2/file/lib/udev/rules.d/91-permissions.rules) it is it is no longer used by [jessie](https://www.apt-browse.org/browse/debian/jessie/main/amd64/udev/) .
These files are no longer used by [Debian stretch](https://packages.debian.org/stretch/amd64/udev/filelist), which already ended [LTS](https://wiki.debian.org/LTS) support on June 30, …
=> fix(udev-rules): remove old rules

modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh
The state of lvm thin pool may change into inactived state when kdump into 2nd kernel. As a result, lvextend will fail to extend its size. For example:
In 1st kernel:
$ lvs
LV       VG         Attr       LSize   Pool     Origin Data%  Meta%
vol      vg00       Vwi-a-tz-- 300.00m thinpool        70.54
thinpool vg00       twi-aotz-- 236.00m                 89.67  12.50
...
In 2nd kernel:
LV       VG         Attr       LSize   Pool     Origin Data%  Meta%
vol      vg00       Vwi-aotz-- 300.00m thinpool        70.54
thinpool vg00       twi---tz-- 236.00m                 89.67  12.50
...
And the lvextend failing log:
[  8.483878] start-thinpool-monitor[590]: lvextend using policy requires the thin pool to be active.
In this patch, we will first activate lvm thin pool before calling lvextend …
=> fix(lvmthinpool-monitor): activate lvm thin pool before extend its size

dracut-functions.sh, dracut.sh
* Uefi section are creating by `objcopy` with hardcoded sections offset. This patch allow to have a dynamic set of offsets between each part of the efi file, needed to create an UKI. Offsets are simply calculated so no sections overlap, see https://wiki.archlinux.org/title/Unified_kernel_image#Manually
Moreover, efi stub file's header is parsed to apply the correct offsets according to the section alignment factor. More information here: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#optional-header-windows-specific-fields-image-only
* Remove EFI_SECTION_VMA_INITRD, no need anymore as initrd section offset dynamically calculated.
Fixes #2275
=> fix(dracut.sh): use dynamically uefi's sections offset

modules.d/01systemd-ac-power/module-setup.sh
`systemd-ac-power` has been moved from `/usr/lib/systemd` to `/usr/bin/` since https://github.com/systemd/systemd/commit/251dc2f1
=> fix(systemd-ac-power): correct systemd-ac-power binary path

modules.d/99base/dracut-dev-lib.sh, modules.d/99base/init.sh
Use printf instead of echo in str_replace() to preserve escapes.
Find command paths while PATH includes `/usr/sbin`. (switch_root was
not found after the original environment is restored on Fedora.)
- [✔] I have tested it locally.
=> fix(99base): adjust to allow mksh as initrd shell

modules.d/90multipath/module-setup.sh, modules.d/90multipath/multipathd.service
This fixes a hang in the cleanup hook: running multipath binary triggers activation of `multipathd.service` after it is (and must remain) stopped as dracut prepares to switch root in `initrd-cleanup.service`.
An earlier fix from PR #2010 was based on an old systemd behavior where missing socket will prevent the service from being enabled. This does not seem to be the case anymore. For completeness, I'm disabling the socket alone after enabling service.
At the end of the day we should probably remove `Also=multipathd.socket` from `multipathd.service` and upsteam this change. The whole point of having a socket enabled separately from the service is that systemd can start the service as-needed. Binding enable/disable status together would not be very sane.
Fixes #2289, #2175
=> fix(multipath): enable service but disable socket

modules.d/01systemd-networkd/module-setup.sh
This pull request adds missing configuration files and services to the `systemd-networkd` module.
=> fix(systemd-networkd): add missing conf files and services

dracut-initramfs-restore.sh, dracut.sh, lsinitrd.sh
Handle the case where the user tries to generate the initrd after explicitly resetting the `/etc/machine-id` file.
Fixes #2267
=> fix(dracut.sh): handle /etc/machine-id empty or uninitialized

modules.d/99base/dracut-lib.sh
If some "finished" initscripts keep failing, dracut will start printing warnings after a while. But it will warn about all scripts in the finished initqueue, not only those that have failed. That makes it difficult to identify the script that has actually caused the failure.
Example: Here, all but the last script `net.nbft1.did-setup` had actually succeeded.
```
Apr 21 19:38:18 localhost dracut-initqueue[1515]: Warning: dracut-initqueue: timeout, still waiting for following initqueue hooks:
Apr 21 19:38:18 localhost dracut-initqueue[1515]: Warning: /lib/dracut/hooks/initqueue/finished/devexists-\x2fdev\x2fdisk\x2fby-uuid\x2f2EBB-2E90.sh: "[ -e "/dev/disk/by-uuid/2EBB-2E90" ]"
Apr 21 19:38:18 localhost dracut-initqueue[1515]: Warning: …
```
=> fix(dracut-lib.sh): remove successful finished initqueue scripts

src/install/dracut-install.c
Check for dependencies on the file actually installed, otherwise, such as when the shebang is a link not equal to the initramfs link, the wrong file may be tested.
This bug surfaced when testing with
`ln -sf mksh /bin/sh`
and, although dash had been specified and installed,
```shell
/usr/bin/dracut@1912(): module_install dash /usr/lib/dracut/modules.d/00dash
/usr/lib/dracut/dracut-init.sh@873(module_install): local _moddir=/usr/lib/dracut/modules.d/00dash
/usr/lib/dracut/dracut-init.sh@874(module_install): local _ret
/usr/lib/dracut/dracut-init.sh@875(module_install): [[ -z /usr/lib/dracut/modules.d/00dash ]]
/usr/lib/dracut/dracut-init.sh@876(module_install): [[ -d /usr/lib/dracut/modules.d/00dash ]]
/usr/lib/dracut/dracut-init.sh@877(module_install): [[ ! -f …
```
=> fix(resolve-deps): check the existing file—not the source

test/TEST-17-LVM-THIN/create-root.sh
Avoid the following warning by reducing thin pool size
> "Sum of all thin volume sizes exceeds the size of thin pool
> and the size of whole volume group.
=> test(LVM-THIN): avoid thin pool size warning

dracut.sh
systemd always installs the UEFI stub in ${prefix}/lib/systemd/boot/efi.
On split-usr systems, systemdutildir is ${rootprefix}/lib/systemd, which makes dracut look in the wrong place.
Instead, grab 'prefix' from systemd.pc and store it in 'systemd_prefix'.
Bug: https://bugs.gentoo.org/765208
=> fix(dracut.sh): correct path to UEFI stub on split-usr systems

modules.d/00systemd/module-setup.sh, modules.d/01systemd-journald/module-setup.sh, modules.d/01systemd-pcrphase/module-setup.sh, modules.d/01systemd-tmpfiles/module-setup.sh
Do not include in the initrd systemd units configured not to run there with `ConditionPathExists=!/etc/initrd-release`, as they just fill the log with entries like:
```
systemd[1]: <UNIT_DESCRIPTION> was skipped because of an unmet condition check (ConditionPathExists=!/etc/initrd-release).
```
References:
- https://github.com/systemd/systemd/commit/fe7f113c
- https://github.com/systemd/systemd/commit/7ef09e20
=> fix(systemd): do not include in the initrd units configured not to run there

test/container/Dockerfile-Gentoo
- Add cryptsetup, multipath-tools, open-scsi to Gentoo container
- Disabling initramfs generation saves installing 4 additional packages.
- re-enable lvm on Gentoo container
- conditionally add tgt to Gentoo container
=> ci: improve Gentoo container 

dracut-init.sh
Do not redirect `systemd-detect-virt` to /dev/null, otherwise, the `vm` variable is always empty. This function was working only thanks to the following /sys check.
=> fix(dracut-init.sh): correct check in `is_qemu_virtualized` function

modules.d/01systemd-networkd/module-setup.sh, modules.d/01systemd-resolved/module-setup.sh, modules.d/01systemd-timedated/module-setup.sh
Fix multiple typos in systemd override paths.
=> fix(systemd): correct typos in override paths

modules.d/62bluetooth/module-setup.sh
This PR is a rebase of #2234 and #2330 on top of latest default branch and resolves conflicts.
- Add missing org.bluez.service dbus system service and bluetooth.service override conf.
- Check if Appearance matches the value assigned for keyboard.
- Check if bluetooth kernel module is loaded
=> fix(bluetooth): add missing files

modules.d/90dmsquash-live/dmsquash-live-root.sh, test/TEST-16-DMSQUASH/create-root.sh, test/TEST-16-DMSQUASH/test.sh
This PR is a rebase of https://github.com/dracutdevs/dracut/pull/2130 on top of latest default branch and resolves conflicts.
This PR provides a test case that currently fails. It than fixes the dmsquash-live module which than make the test case to pass.
=> fix(dmsquash-live): allow other fstypes

dracut.sh, install.d/50-dracut.install, install.d/51-dracut-rescue.install
This pull request fixes installing a kernel with uefi=yes in dracut config and layout=uki in kernel/install.conf.
Before this change this would fail because dracut needs a `--kernel-image` argument if uefi=yes. Additionally, if `kernel-install` has defined a `KERNEL_INSTALL_STAGING_AREA` for us we put the generated initrd/uki.efi there so the actual install can be handled by the appropriate plugins. This simplifies the code, otherwise we would need some extra logic that is already present in `90-loaderentry.install` and `90-uki-copy-install`. 
If we are dealing with some unknown `KERNEL_INSTALL_LAYOUT` or `KERNEL_INSTALL_STAGING_AREA` is not defined we revert to the old behaviour for backwards compatibility. This can happen if we have defined some custom `KERNEL_INSTALL_LAYOUT` or if we …
=>  install.d/*.install: Fix kernel install with uefi=yes

man/dracut.cmdline.7.asc, modules.d/95nvmf/module-setup.sh, modules.d/95nvmf/nbftroot.sh, modules.d/95nvmf/nvmf-autoconnect.sh, modules.d/95nvmf/parse-nvmf-boot-connections.sh
Add support for booting from NVMe over Fabrics according to the [NVM Express Boot Specification v1.0](https://nvmexpress.org/developers/nvme-boot-specification/) to dracut. Note that this is orthogonal to boot from NVMeoF over Fibre Channel, which is already supported by dracut (using features exclusive of the FC transport). The NVMe-oF Boot Spec is designed to be transport-agnostic (but v1.0 contains support for the TCP transport only).
The spec defines an ACPI table called "NBFT", in which the system firmware stores information about network configuration and NVMe subsystems used for booting (similar to the iBFT table for iSCSI). The code in this PR reads the NBFT table (parsing JSON as printed by nvme-cli), transforms it into `ip=` parameters that dracut's network setup code …
=> NVMeoF / TCP boot support

man/dracut.cmdline.7.asc, modules.d/90dmsquash-live/dmsquash-live-root.sh, modules.d/90livenet/livenetroot.sh, modules.d/99base/dracut-lib.sh
For writeable live images, the memory must hold the complete image. That means it must be at least the size of the image plus some RAM necessary to run processes.
With too small RAM, the OOM Killer steps in and makes the boot hang. This patch lets the system go into the emergency shell instead.
The minimum RAM of 512Mb is just arbitrarily choosen. We could set any other number that appears appropriate instead. Alternatively, we could add a new parameter rd.min.ram or such.
livenet module
- [X ] I have tested it locally
- [X ] I have reviewed and updated any documentation if relevant
Fixes #
OOM in livenetboot with too low memory.
=> RFC: feat(livenet): add memory size check depending on live image size

dracut.sh
As stated in [1] it should work without literal backslash+linefeed.
[1] https://github.com/koalaman/shellcheck/issues/1246
Shellcheck warning should be mitigated.
=> fix(dracut.sh): shellcheck warning SC1004

test/container/Dockerfile-OpenSuse-latest
- `findmnt` is installed by `util-linux-systemd`. E.g.:
https://github.com/dracutdevs/dracut/actions/runs/5424796254/jobs/10097178325#step:4:53
- `/usr/lib/systemd/boot/efi/linuxx64.efi.stub` is installed by `systemd-boot`. E.g.:
https://github.com/dracutdevs/dracut/actions/runs/5424796254/jobs/10097178325#step:4:55
=> ci: install util-linux-systemd and systemd-boot into openSUSE container

src/install/dracut-install.c
When attempting to locate a firmware path under each of the firwaredirs parent directories, Dracut logs an error for every missing path. Instead, only log the error if the firmware path isn't found under any of the firmwaredirs.
=> refactor(install): log about missing firmware only once

.github/workflows/container.yml
Container GitHub Action runs daily for dracutdevs developers. Every time dracut repo get's forked this daily github action runs on all forked repo's.
Some people know (and remember) to disable this action manually, but for the most this is just wasting significant resources as currently there is at east [300+ forked version of dracut](https://github.com/dracutdevs/dracut/forks) on Github.
As suggested by @mwilck  at https://github.com/dracutdevs/dracut/issues/1865#issue-1293154830
> The workflow should be made conditional in some way.
Fixes #1865
=> ci: do not run test container generation on forked repos by default

test/container/Dockerfile-Gentoo
See https://www-cdn.gentoo.org/support/news-items/2022-04-19-systemd-utils.html
Gentoo test container started failing on Jul-31 - https://github.com/dracutdevs/dracut/actions/runs/5714136544
After  open-iscsi  2.1.8--> 2.1.9 upgrade open-iscsi for musl as it fails to compile, see https://bugs.gentoo.org/908587, so no longer include it.
=> ci: migrate from systemd-boot to systemd-utils in Gentoo container

.github/workflows/lint.yml
ci: change the order of lint jobs as lint_shell is more likely to fail..
Now the lint_shell test result is "above the scroll" on the page.
=> ci: change the order of lint jobs as lint_shell is more likely to fail

dracut.sh
We came across an issue where, when resolving executable dependencies, a call to a buggy glib function in `dracut-install` was causing a termination with SIGSEGV, but dracut didn't stop the build process, which resulted in an unbootable initrd, due to missing required libraries.
```
dracut: *** Resolving executable dependencies ***
xargs: /usr/lib/dracut/dracut-install: terminated by signal 11
dracut: *** Resolving executable dependencies done ***
```
Therefore, stop the initrd creation in this case.
=> fix(dracut.sh): exit if resolving executable dependencies fails

modules.d/01systemd-udevd/module-setup.sh
Fix override paths of `systemd-udevd-control.socket` and `systemd-udevd-kernel.socket`.
=> fix(systemd-udevd): add missing override paths

Makefile
To ease packaging dracut for Debian/Ubuntu, please support setting the dracut main/full version via environment variables:
```
$ DRACUT_MAIN_VERSION=007
$ export DRACUT_FULL_VERSION=007-bond
$ make dracut-version.sh
$ grep VERSION dracut-version.sh
DRACUT_VERSION=007-bond
```
=> feat(Makefile): allow setting dracut version via environment variables

.github/workflows/container.yml, .github/workflows/integration.yml, .github/workflows/manualtest.yml, test/container/Dockerfile-Ubuntu
Add a Dockerfile for Ubuntu (very similar to Debian) and run the integration tests also on Ubuntu.
I built the container locally and tested that the test cases from the integration test succeed there.
Fixes #
=> ci: also run integration test on Ubuntu

test/TEST-20-NFS/server-init.sh, test/TEST-20-NFS/test.sh, test/TEST-50-MULTINIC/server-init.sh, test/TEST-50-MULTINIC/test.sh
Test 20 - "NFSv3 root=dhcp DHCP IP:path" fails on Debian with following error message in `server.log`:
```
jobs -rp
/sbin/init: 105: jobs: Illegal option -r
```
The jobs parameter `-r` requires bash.
Partially fixes #1901
=> fix(test): use bash for jobs -r parameter

dracut-functions.sh, dracut-init.sh, dracut.sh, install.d/51-dracut-rescue.install, modules.d/90dmsquash-live-autooverlay/create-overlay-genrules.sh, modules.d/90dmsquash-live-autooverlay/module-setup.sh, modules.d/95cifs/cifsroot.sh, modules.d/95rootfs-block/block-genrules.sh, test/test-functions
Remove unnecessary shellcheck comments for [SC2154](https://www.shellcheck.net/wiki/SC2154) . The current version of shellcheck is smart enough to not require these opt-out comments.
This is a rebase from a PR closed earlier by the stale bot - https://github.com/dracutdevs/dracut/pull/2235
=> chore: remove unnecessary shellcheck disable for SC2154

docs/HACKING.md
Running the test suite in podman will most likely require setting `KVERSION` because the running Linux kernel version will most likely be different to the kernel version in the container.
=> docs: set KVERSION for running test suite

dracut.sh
`CONFIG_MICROCODE_AMD` and `CONFIG_MICROCODE_INTEL` are hidden since https://lore.kernel.org/all/20230810160805.081212701@linutronix.de/, therefore this check is wrong and early microcode is always disabled.
[Already merged into the tip tree](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=029ae99c8507db15adfae24a15dc44fd568b5f93), PR created as draft meanwhile it doesn't make it to the master branch.
=> fix(dracut.sh): remove microcode check based on CONFIG_MICROCODE_[AMD|INTEL]

modules.d/40network/net-lib.sh
SC1087 is not listed in shellcheckrc.
This is the only place in the code where SC1087 were silenced.
=> chore: remove unnecessary shellcheck disable for SC1087

modules.d/00systemd/module-setup.sh
In [0] systemd gained a new binary - systemd-executor - that's used to spawn processes forked off systemd. Let's copy it into the initrd if it's available.
[0] https://github.com/systemd/systemd/pull/27890
/cc @bluca
=> feat(systemd): install systemd-executor

modules.d/01systemd-journald/module-setup.sh
The `systemd-journald` module installs its own system group, so add the missing the dependency.
https://github.com/dracutdevs/dracut/blob/a804945f27a0ccc2f69ae694599b1afec2afe8b1/modules.d/01systemd-journald/module-setup.sh#L48
=> fix(systemd-journald): add systemd-sysusers dependency

.github/labeler.yml
Since we are using `actions/labeler@main`, its format changed, displaying the following error with every new PR:
```
Run actions/labeler@main
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Error: Error: found unexpected type for label 'repository' (should be array of config options)
Error: found unexpected type for label 'repository' (should be array of config options)
```
=> fix(github): update format of labeler

configure
While preparing a new system for development, `./configure` reaches a point where it fails with:
```
$ ./configure
dracut needs fts development files.
```
After installing the fts library, `./configure` keeps throwing the same error:
```
$ rpm -qf /usr/include/fts.h
glibc-devel-2.38-6.1.x86_64
$ ./configure
dracut needs fts development files.
```
The problem is `${CC} $CFLAGS $LDFLAGS conftest.c` can also fail if the compiler referenced by `$CC` is not installed.
=> fix(configure): misleading error if C compiler is not installed

modules.d/95zfcp_rules/parse-zfcp.sh
Fixes 032ecd95c94b77f3f08237e0f765b355dacb9573
=> fix(zfcp_rules): correct shellcheck regression when parsing ccw args
