dracutdevs/dracut

- dracut.sh
When reading the --include part of the script, we had the following
issues to make the code easy to read:
- src & tgt were extract for the original options
- i variable was a file or a directory from src
- s variable was the directory name in case $i was a directory
"s" sounds very close to "src" while "s" is on the "tgt" side. Very
confusing.
"s" was defined before the "if it's a directory" statement while it's
only used inside the "if".
"i" was commit from the "src" but wasn't really explicit.
Having some lines mixing "i" and "s" takes a little time to get read
properly.
This patch offer the following changes:
- "i" is renamed to "objectname" as we don't know if its a file or a
directory
- "s" is renamed to "object_destdir" as the object name becomes a
directory on the destdir
- …
> dracut: Ajusting variables name for --include

- dracut.sh
Like and for similar reasons as gzip/pigz
> Use lbzip2 instead of bzip2 if available

- modules.d/91crypt-loop/crypt-loop-lib.sh
When booting with 'rd.info', the 'info' statements in the crypt-loop
module's 'loop_decrypt' function are output to stdout along with the key
that gets piped into the 'cryptsetup' command, which causes the crypt
device unlocking to fail.
There are two possible simple solutions to this problem:
1. Redirect the info messages to stderr (just add '>&2' at the end of
the info statements)
OR
2. Remove the info statements altogether.
I have tested both and they both work, but this commit implements the second option.
The existing info messages are long (they overflow 80 characters
easily) and redundant (the password prompt clearly indicates what is
happening), and just generally not useful.  Given that no one has
reported or fixed this bug in the three years that this module has
existed, no one …
> crypt-loop: Fix decrypt when running at info log level

- modules.d/99base/dracut-lib.sh
Signed-off-by: Lidong Zhong <lzhong@suse.com>
> dracut-lib.sh: typo fix

- modules.d/90lvm/lvm_scan.sh
This reverts commit cfa365a32d47388c8476064b23d7d4684f1e591b.
> Revert "lvm: Don't activate LVs with activationskip set"

- dracut.sh
There is no way exit between the two places that call push_host_devs
> dracut.sh: remove duplicate call of push_host_devs

- dracut.sh
Handle module aliases correctly to not generate unbootable
initrds with different kernel versions when modules were renamed
or replaced.
Signed-off-by: Fabian Vogt <fvogt@suse.com>
> Correctly handle module aliases

- NEWS
- modules.d/03rescue/module-setup.sh
- modules.d/95debug/module-setup.sh
- modules.d/99fs-lib/fs-lib.sh
- modules.d/99fs-lib/module-setup.sh
Hi
i've added support to F2FS filesystem.
What is important i've tested this change on OpenMandriva Lx 3.0 running system with SSD disk with F2FS.
OpenMandriva Lx 3.0 have added support to F2FS
https://blog.openmandriva.org/2016/04/3244/
@haraldh Please merge.
> add support to F2FS filesystem (fsck)

- 50-dracut.install
This script utilizes several bash-specific constructs.
> 50-dracut.install: use /bin/bash shebang

- modules.d/40network/dhclient-script.sh
Currently dracut can fail to setup dhclient in a network where DHCP server provides multiple default gateways. See https://bugzilla.redhat.com/show_bug.cgi?id=1408249 for details
> Support multiple default gateways from DHCP server (rhbz#1408249)

- .gitignore
Also fixes ignores after systemd module split
> Ignore more generated files

- modules.d/40network/ifup.sh
https://bugzilla.redhat.com/show_bug.cgi?id=1416958
Thanks to martin.moore@hpe.com for the patch
> ifup: don't ifup team master indefinitely

- README.testsuite
- modules.d/40network/ifup.sh
- modules.d/40network/module-setup.sh
- test/TEST-01-BASIC/test.sh
- test/TEST-02-SYSTEMD/test.sh
- test/TEST-03-USR-MOUNT/test.sh
- test/TEST-04-FULL-SYSTEMD/test.sh
- test/TEST-10-RAID/test.sh
- test/TEST-11-LVM/test.sh
- test/TEST-12-RAID-DEG/test.sh
- test/TEST-13-ENC-RAID-LVM/test.sh
- test/TEST-14-IMSM/test.sh
- test/TEST-15-BTRFSRAID/test.sh
- test/TEST-16-DMSQUASH/test.sh
- test/TEST-17-LVM-THIN/test.sh
net-tools are not required anymore.
Tested on F25 with package removed.
> Remove obsolete test dependencies

- modules.d/90mdraid/module-setup.sh
> Allow booting from degraded MD RAID arrays

- modules.d/40network/ifup.sh
- modules.d/40network/parse-bond.sh
Signed-off-by: Imran Haider imran1008@gmail.com
> add 'mtu' parameter for bond options

- dracut.sh
This is intended for minimum host OSes where 36 MB used by binutils
are deemed too expensive. We only need "strip", which exists as eu-strip
in elfutils, which in turn is < 1 MB in size.
Note that the tests (TEST-04-FULL-SYSTEMD/test.sh) still depend on
strip from binutils. It could use sstrip in the future.
> Make binutils optional when elfutils are available

- dracut.cmdline.7.asc
- modules.d/95dasd/parse-dasd.sh
- modules.d/95dasd_rules/module-setup.sh
- modules.d/95dasd_rules/parse-dasd.sh
- modules.d/95zfcp_rules/module-setup.sh
- modules.d/95zfcp_rules/parse-zfcp.sh
Used in production RPMs for the last few months. //cc @hreinecke
> s390 changes that never went upstream

- modules.d/01fips/module-setup.sh
https://bugzilla.redhat.com/show_bug.cgi?id=1465946
> 01fips: add authenec module

- dracut.conf.5.asc
- dracut.sh
> Do generate error when hostonly_cmdline is set to "no"

- dracut-functions.sh
> Add early microcode support for AMD family 16h

- modules.d/91crypt-loop/crypt-loop-lib.sh
> Support crypto loop keys in initrd.

- modules.d/90multipath/module-setup.sh
> 95multipath: Pickup files in /etc/multipath/conf.d

- dracut-bash-completion.sh
- dracut-initramfs-restore.sh
- dracut.8.asc
- dracut.conf.5.asc
- dracut.sh
- lsinitrd.sh
- modules.d/99img-lib/img-lib.sh
- modules.d/99img-lib/module-setup.sh
This PR adds support for Zstandard (https://github.com/facebook/zstd)
@haraldh Please review it.
> add support for Zstandard

- modules.d/95fcoe/module-setup.sh
Some Combined Network Adapters(CNAs) implement DCB protocol
in firmware, it is recommended that do not run software-based
DCB or LLDP on CNAs that implement DCB, but we have to start
the lldpad service anyway(there might be other software DCB).
If the network interface provides hardware DCB/DCBX capabilities,
the field DCB_REQUIRED in "/etc/fcoe/cfg-xxx" is expected to
be set to "no".
We met an issue on "QLogic BCM57810" with DCB firmware support,
and found dracut still generated "fcoe=<mac>:dcb" which caused
kdump boot failure when using that fcoe dump target.
This patch parses /etc/fcoe/cfg-xxx to detect DCB_REQUIRED="no",
and force "nodcb" if it is the case.
Improved coding style in passing.
Signed-off-by: Xunlei Pang <xlpang@redhat.com>
> fcoe: handle CNAs with DCB firmware support

- modules.d/40network/parse-bond.sh
Signed-Off-By: Robert LeBlanc <robert@leblancnet.us>
> Fix a couple of typos.

- modules.d/90dmsquash-live/dmsquash-live-root.sh
Fix issue #279  supercede PR #299
Fix bug https://issues.openmandriva.org/show_bug.cgi?id=2219
Replace Bashisms in the boot message for a missing overlay.
Verify presence of plymouth before calling it.
(Rework of commit f1b65e92af5e3f9df79f99e55d5aa936c9bca940.)
> dmsquash-live-root: Replace incompatible shell syntax.

- dracut-functions.sh
Original-Patch-By: Tom Lendacky <thomas.lendacky@amd.com>
> Support Microcode Updates for AMD CPU Family 0x17

- dracut-functions.sh
Suggested by Tom Lendacky <thomas.lendacky@amd.com>
> Simplify microcode lookup for for AMD CPUs

- modules.d/90btrfs/module-setup.sh
> Include crc32c-intel module when using btrfs

- modules.d/10i18n/module-setup.sh
References: bsc#943312, bsc#932981
Signed-off-by: Fabian Vogt <fvogt@suse.com>
> 10i18n: Add correct fontmaps

- dracut.cmdline.7.asc
- modules.d/95fcoe/fcoe-genrules.sh
- modules.d/95fcoe/fcoe-up.sh
- modules.d/95fcoe/module-setup.sh
- modules.d/95fcoe/parse-fcoe.sh
- modules.d/95fcoe/stop-fcoe.sh
Mostly fixes. Some new features and command line/boot arguments.
> All FCOE-related SUSE patches, rebased on top of master

- configure
- dracut.spec
Follow-up for 2a0da60ed18b33e39fe8e36864800bbaaa0448b4.
> configure, kmod: bump kmod version to >= 23

- modules.d/90kernel-modules/module-setup.sh
> 90kernel-modules: Include Intel Volume Management Device support

- modules.d/99fs-lib/module-setup.sh
> fs-lib: install crc32 in no-hostonly

- modules.d/99img-lib/img-lib.sh
@haraldh Please merge. I've made a huge typo. Now zstd is correctly handled.
> fix zstd magic header

- modules.d/90stratis/module-setup.sh
- modules.d/90stratis/stratisd-init.service
- modules.d/90stratis/stratisd-start.sh
- modules.d/90stratis/stratisd-stop.sh
Ref. https://github.com/stratis-storage
Signed-off-by: Tony Asleson <tasleson@redhat.com>
> Initial Stratis support

- dracut.spec
Follow-up for c4f8329cc2b158c8d91ad9d9b7776b3970d3735a.
> spec: add stratis module

- modules.d/90crypt/parse-crypt.sh
Commit bf5c53a implements support for mounting LUKS devices with
detached headers; however, it assumes that the LUKS device sits on an
unpartitioned disk.
Mirroring the `rd.luks.serial` option, this commit implements the
`rd.luks.partuuid` cmdline option, supporting headless LUKS devices on
drive partitions.
> crypt: Implement cmdline rd.luks.partuuid

- modules.d/90kernel-modules/module-setup.sh
since kmod-25 keyword "external" was implemented in order to avoid
additional actions(like weak-modules) when kernel was updated, which
makes it more simple while kernels' kabi were compatible.
but if move some special modules such as megaraid_sas, mpt3sas and
so on, to a external path like /opt/modules, these modules will not
be install to initramfs by default, which make the initramfs can't
be used to boot for disk detection failure.
according to kmod's document, you must specify a absolute path with
"external" keyword, so scan the lines in modules.dep that begin with
"/" and install them, to make sure necessary modules in external path
can be installed to initramfs too.
Signed-off-by: Hui Wang <john.wanghui@huawei.com>
> dracut: scan and install external kernel modules

- install/dracut-install.c
Dracut uses the module deps to determine module dependencies
but that only works for modules with hard symbolic dependencies.
Some modules have dependencies created via callback API's or other
methods which aren't reflected in the modules.dep but rather in
modules.softdep through the use of "pre:" and "post:" commands
created in the kernel with MODULE_SOFTDEP().
Since in dracut we are only concerned about early boot, this patch
only looks at the pre: section of modules which are already being
inserted in the initrd under the assumption that the pre: section
lists dependencies required for the functionality of the module being
installed in the initrd.
Signed-off-by: Jeremy Linton <lintonrjeremy@gmail.com>
> dracut-install: Support modules.softdep

- dracut.cmdline.7.asc
- modules.d/90crypt/cryptroot-ask.sh
Please note that I did not test the feature with plymouth. If someone confirm
that it works I can update the pull-request accordingly.
> Add timeout option to crypt module

- modules.d/95iscsi/module-setup.sh
- modules.d/95iscsi/parse-iscsiroot.sh
> Add the qedi driver to driver list for iscsi boot

- lsinitrd.1.asc
- lsinitrd.sh
Hi, this pull request tries to make "--unpack" be able to unpack only certain files, and optimize performance when handling multiple files with lsinitrd.
> lsinitrd optimize

- modules.d/90stratis/module-setup.sh
Include all binaries that could be called by the daemon.
Signed-off-by: Tony Asleson <tasleson@redhat.com>
> stratis: Add additional binaries

- dracut.sh
The rest of the comments also have a space there.
> Added space in Resolving executable dependencies done as in the rest of the messages

- .travis.yml
...until Fedora 30 gets a fixed systemd, if ever.
> Run tests 13 and 14 with Fedora 29

- modules.d/01fips/module-setup.sh
> 01fips: add cfb cipher

- dracut-init.sh
- dracut.sh
Hi, This pull request contains several changes of squash module that will help reduce the memory usage even more, clean up the code a bit, and make it possible to do more optimize for kdump.
> squash: keep less unneeded things outside the squash image

- modules.d/95debug/module-setup.sh
When at it also deduplicate the list of installed utilities.
> debug: Add dd into debug module

- dracut-init.sh
When a module is compressed, uncompress it before packing into initrd.
Since initrd is already compressed, it makes no sense to put the
compressed module files.
The patch contains a slight refactoring and adds a helper function to
get the command for uncompressing a file per extension.
This issue came up in opensuse bugzilla:
https://bugzilla.suse.com/show_bug.cgi?id=1135854
> dracut-install: Add support for compressed kernel modules

- modules.d/99shutdown/shutdown.sh
C.f. https://github.com/systemd/systemd/issues/13332.
> shutdown: fix shutdown with console=null

- modules.d/99fs-lib/module-setup.sh
> Check /usr/sbin for fsck programs

- modules.d/00systemd/module-setup.sh
> added debug-shell to initrd in systemd version >= 240

- .travis.yml
- modules.d/40network/netroot.sh
- modules.d/95iscsi/module-setup.sh
- modules.d/98dracut-systemd/dracut-cmdline.sh
- modules.d/99base/init.sh
- modules.d/99fs-lib/fs-lib.sh
- test/TEST-01-BASIC/test.sh
- test/TEST-02-SYSTEMD/test.sh
- test/TEST-03-USR-MOUNT/test.sh
- test/TEST-04-FULL-SYSTEMD/test.sh
- test/TEST-10-RAID/create-root.sh
- test/TEST-10-RAID/test.sh
- test/TEST-11-LVM/test.sh
- test/TEST-12-RAID-DEG/test.sh
- test/TEST-13-ENC-RAID-LVM/create-root.sh
- test/TEST-13-ENC-RAID-LVM/test.sh
- test/TEST-14-IMSM/create-root.sh
- test/TEST-14-IMSM/test.sh
- test/TEST-15-BTRFSRAID/test.sh
- test/TEST-16-DMSQUASH/test.sh
- test/TEST-17-LVM-THIN/create-root.sh
- test/TEST-17-LVM-THIN/test.sh
- test/TEST-20-NFS/test.sh
- test/TEST-30-ISCSI/test.sh
- test/TEST-31-ISCSI-MULTI/test.sh
- test/TEST-40-NBD/test.sh
- test/TEST-50-MULTINIC/test.sh
- test/TEST-70-BONDBRIDGETEAMVLAN/test.sh
- test/test-functions
Let's see if we can fix the tests...
> [RHEL-8] Deal with the test failures

- modules.d/95debug/module-setup.sh
Added df and du for viewing filesystems
Added lsblk to improve readability of disk and filesystem layout from dracut.
> added additional useful filesystem tools

- dracut-functions.sh
- dracut-init.sh
> Remove dead code

- dracut.sh
> Only generate hostonly-kernel-modules list in strict mode

- dracut-init.sh
Fixes https://github.com/dracutdevs/dracut/issues/668
> Fix dealing with udevadm --version reporting sth unexpected

- Makefile
- configure
- modules.d/90dmraid/module-setup.sh
- modules.d/90multipath/module-setup.sh
The configure script change is used for VoidLinux. It may be too local. I can drop it if it's undesirable.
> Configure and requirement

- fedora-test.sh
- logtee.c
Travis cuts us short after 10 minutes of slience, giving us no chance to puke
out the output. Be faster.
> logtee: time out after a period of no output

- Makefile
- dracut.8.asc
- dracut.asc
- dracut.bootup.7.asc
- dracut.cmdline.7.asc
- dracut.conf.5.asc
- dracut.modules.7.asc
- lsinitrd.1.asc
- mkinitrd.8.asc
> Documentation: dynamically set current version

- modules.d/95resume/module-setup.sh
This also fixes swap-file handling.
Ref: https://github.com/dracutdevs/dracut/commit/34b56de12aad622d602d6e3bd434e02c840f1cd0
Fixes https://github.com/dracutdevs/dracut/issues/496
> Enable resume module if hibernation's enabled on the host

- dracut.spec
- modules.d/90kernel-modules/module-setup.sh
- modules.d/90nvdimm/module-setup.sh
This supersedes #747. 
Changes wrt #747:   
* rebase onto current master
* use `inst_multiple -o` for ndctl as suggested by  @haraldh 
* add new module to spec file
> Add module "90nvdimm" for NVDIMM support (new PR)

- modules.d/95zfcp_rules/parse-zfcp.sh
Reference: bsc#1008352
Original-Patch-By: Michal Suchanek <msuchanek@suse.com>
> 95zfcp_rules/parse-zfcp.sh: remove rule existence check

- mkinitrd-suse.sh
> mkinitrd-suse.sh: Fix i586 platform detection

- modules.d/98dracut-systemd/dracut-pre-pivot.sh
- modules.d/99base/init.sh
- modules.d/99memstrack/memstrack-report.sh
Fix two problem with memstrack module
> Fix issues with memstrack module

- dracut-functions.sh
- modules.d/05busybox/module-setup.sh
Fixes: a01204202b30
https://bugzilla.redhat.com/show_bug.cgi?id=1810504
https://bugs.gentoo.org/714838
> Fixes for find_binary() and busybox module

- dracut.conf.5.asc
Fixes: https://github.com/dracutdevs/dracut/issues/824
> dracut.conf.5.asc: document how to config --no-compress in the config

- README.md
- dracut.spec
While fixing the CI badges, I removed some old crufty README text.
> Fix CI badges in README.md and fix dracut description

- modules.d/35network-manager/module-setup.sh
- modules.d/35network-manager/nm-config.sh
- modules.d/35network-manager/nm-lib.sh
- modules.d/80cms/cmsifup.sh
Change the cms module to support operation with NetworkManager instead of network-legacy.
> Support NetworkManager in the cms module

- modules.d/90lvm/module-setup.sh
> 90lvm: do not add newline to cmdline

- dracut.sh
Command level inside conditional and tab/space usage.
> dracut.sh: fix some indentation.

- modules.d/06rngd/rngd.service
Host should take care of good entropy pool
#791
This PR replaces https://github.com/dracutdevs/dracut/pull/814 as i lost that branch...
> Do not start inside container

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/SECURITY.md
This pull request adds issue templates and security policy
Fixes #
> Issue templates and SECURITY.md

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
This pull request fixing hopefully unicode in templates
Fixes #
> Fix Unicode

- README.md
This pull request fixes incorrect CoC url in README
Fixes #
> Fix CoC URL

- dracut.spec
This pull request changes the default fedora spec file template.
Fixes #
> dracut.spec: remove fedora pre 30 quirks

- dracut.spec
https://fedoraproject.org/wiki/Changes/UseMakeBuildInstallMacro
Fixes #
> dracut.spec: Use make macros

- dracut-functions.sh
- dracut.sh
- modules.d/99squash/module-setup.sh
Make squash module installation covers more cases. Now it works when needed module is built-in, and fail earlier if there are missing modules. 
Fixes #
> Improve squash module installation

- install/dracut-install.c
> dracut-install: Globbing support for resolving "firmware:"

- dracut.cmdline.7.asc
From the current man page it's really hard to tell what will be output of this
command.
Fixes #
Documentation.
> Improve documentation of iso-scan/filename feature

- dracut-bash-completion.sh
- dracut.8.asc
- dracut.conf.5.asc
- dracut.sh
This reverts commit f8f3b0f3588273e69b345d6d0602d6d2a1c5a819.
Fixes #
> Revert "Add --uefi-output for custom output filename"

- .github/stale.yml
Given that we are all short on :watch: let's optimizing our workflow so we can spend more time drinking :beers: and less time doing work.
Stale bot for the win! :smile_cat:
> Adding stalebot file

- .github/workflows/pr.yml
To ease the creation of the release notes, enforce some style on the git
commit message titles with `Commisery`.
https://github.com/marketplace/actions/commisery
Using https://github.com/clog-tool/clog-cli later on these commits will
generate a pretty nice base for the release notes.
> test(conventional): add Conventional Commits PR github action

- .dir-locals.el
- .editorconfig
- .vimrc
This pull request updates emacs configuration for the repository and adds configuration for editors and vim.
> chore: update and add configuration for editors

- .github/CODEOWNERS
All CODEOWNERS are automatically added as reviewers.
> chore(github): add CODEOWNERS file

- dracut.spec
- modules.d/01systemd-sysusers/module-setup.sh
This pull request introduce the systemd-sysusers module which is a prerequisite for further module introduction, re-factoring and cleanup.
> feat(systemd-sysusers): introducing systemd-sysuser module

- test/TEST-35-ISCSI-MULTI/test.sh
> test: incr. disk size for TEST 35 ISCSI-MULTI

- dracut.sh
The kernel does not allow the cmdline to be overridden if one is defined
in the uefi image.  This means that bootloaders like systemd-boot or
grub cannot manage boot options (editing at boot for debug being a use
case).  This patchset allows for no cmdline to be set (instead of force
setting one if none is provided).
Closes: https://github.com/dracutdevs/dracut/issues/1012
Fixes #1012
> fix: do not set cmdline for uefi images unless asked

- modules.d/01systemd-coredump/module-setup.sh
- modules.d/01systemd-repart/module-setup.sh
- modules.d/01systemd-sysusers/module-setup.sh
- modules.d/06dbus-broker/module-setup.sh
- modules.d/06dbus-daemon/module-setup.sh
Comments will break bash line continuation.
Also added some missing line continuation here and there.
> fix: correct the line continuation

- dracut.spec
> fix: BuildRequiring git-core is enough in dracut.spec

- modules.d/01systemd-coredump/module-setup.sh
- modules.d/01systemd-initrd/module-setup.sh
- modules.d/01systemd-repart/module-setup.sh
- modules.d/01systemd-sysusers/module-setup.sh
- modules.d/02systemd-networkd/module-setup.sh
- modules.d/06dbus-broker/module-setup.sh
- modules.d/06dbus-daemon/module-setup.sh
- modules.d/06rngd/module-setup.sh
- modules.d/09dbus/module-setup.sh
- modules.d/40network/module-setup.sh
- modules.d/98dracut-systemd/module-setup.sh
- modules.d/99squash/module-setup.sh
1. no module checks for modules which are in depends()
2. no `derror` for optional (255) modules checking for dependencies
3. fix dbus meta module
> fix: revise all module checks

- dracut-initramfs-restore.sh
This pull request adds missing efi paths.
> fix: adding missing efi paths

- modules.d/01systemd-coredump/module-setup.sh
- modules.d/01systemd-repart/module-setup.sh
- modules.d/06dbus-broker/module-setup.sh
- modules.d/06dbus-daemon/module-setup.sh
This rephrases a comment in the check() as requested on another PR
and generalizes the install() section comments on par with other recent
module changes.
These are purely cosmetic comment fixes...
Fixes #
> fix: cosmetic comment fixes

- test/TEST-03-USR-MOUNT/create-root.sh
- test/TEST-04-FULL-SYSTEMD/create-root.sh
- test/TEST-10-RAID/create-root.sh
- test/TEST-11-LVM/create-root.sh
- test/TEST-13-ENC-RAID-LVM/create-root.sh
- test/TEST-14-IMSM/create-root.sh
- test/TEST-15-BTRFSRAID/create-root.sh
- test/TEST-17-LVM-THIN/create-root.sh
- test/TEST-20-NFS/create-root.sh
- test/TEST-30-ISCSI/create-client-root.sh
- test/TEST-30-ISCSI/create-server-root.sh
- test/TEST-35-ISCSI-MULTI/create-client-root.sh
- test/TEST-35-ISCSI-MULTI/create-server-root.sh
- test/TEST-40-NBD/create-client-root.sh
- test/TEST-40-NBD/create-encrypted-root.sh
- test/TEST-40-NBD/create-server-root.sh
- test/TEST-50-MULTINIC/create-root.sh
- test/TEST-60-BONDBRIDGEVLANIFCFG/create-root.sh
might be responsible for some flakiness
> ci: wait for udev before doing sfdisk

- docs/RELEASE.md
Let's get us started on #1071
This PR creates the /docs directory which will contain all project related
documentation and host the projects github based website
in the future.
It contains the RELEASE.md which is a document that is intended to outlines the steps 
required to conduct a successful.
@haraldh you should replace the included sample steps in the file with the actual 
steps you performed, while creating the new release after this has been merged.
Fixes #
> docs: RELEASE.md

- docs/RELEASE.md
> docs: update docs/RELEASE.md

- Makefile
> chore: add `CONTRIBUTORS` target to Makefile

- AUTHORS
- NEWS.md
> docs: update NEWS.md and AUTHORS

- .github/stale.yml
Let's exempt issues with the label bugs being processed by stalebot.
Fixes #
> fix(github): exempt issues with the label bug

- .mailmap
This pull request removes duplicated my email in AUTHORS files
- [] I am providing new code and test(s) for it
> chore: update authors in .mailmap

- dracut.sh
If SIGWHATEVER will be processed after fsfreeze -f, but before fsfreeze
-u we will end up with /boot/ never unfrozen, let's try to minimize risk of this.
Adds cleanup of freeze on exit.
- [ V ] I have tested it locally
Yes, i added `sleep 999` between `fsfreeze -f` and `fsfreeze -u` and did `kill`. Prior to fix result was - boot is frozen, after the fix - boot is fine.
- [ X ] I have reviewed and updated any documentation if relevant
I don't think it's applicalbe
- [ X ] I am providing new code and test(s) for it
I think it's not applicable.
> fix(dracut.sh): unfreeze /boot on exit

- skipcpio/skipcpio.c
Before:
```
Benchmark #1: ./skipcpio/skipcpio test-5.10.15-200.fc33.x86_64.img >/dev/null
Time (mean ± σ):     125.5 ms ±   0.9 ms    [User: 97.4 ms, System: 27.9 ms]
Range (min … max):   124.8 ms … 129.4 ms    23 runs
```
After:
```
Benchmark #1: ./skipcpio/skipcpio test-5.10.15-200.fc33.x86_64.img >/dev/null
Time (mean ± σ):      12.2 ms ±   0.3 ms    [User: 2.7 ms, System: 9.5 ms]
Range (min … max):    11.7 ms …  13.6 ms    212 runs
```
Besides the speedup, skipcpio now parses the cpio header and is not
falsely ending when the early cpio payload contains `TRAILER!!!`.
Fixes: https://github.com/dracutdevs/dracut/issues/1123
> feat(skipcpio): speed up and harden skipcpio

- modules.d/98dracut-systemd/dracut-cmdline.sh
A match for systemd https://github.com/systemd/systemd/pull/18847
- [ x ] I have tested it locally
Fixes #
> dracut: don't refuse root=tmpfs when systemd is used

- test/TEST-98-GETARG/test.sh
Fix a mis-replaced comparison.
> test: fix test 98 getarg

- .astylerc
- .github/workflows/lint.yml
- HACKING.md
- Makefile
- install/dracut-install.c
- install/hashmap.c
- install/hashmap.h
- install/macro.h
- install/strv.c
- install/util.c
- install/util.h
- logtee.c
Indent has its flaws, so use `astyle`.
> Use astyle for C formatting

- modules.d/99base/dracut-lib.sh
- modules.d/99base/init.sh
- modules.d/99base/initqueue.sh
- modules.d/99base/loginit.sh
- modules.d/99base/module-setup.sh
- modules.d/99base/parse-root-opts.sh
- modules.d/99base/rdsosreport.sh
Also remove some functions, which are not used and broken anyway.
> fix(base): shellcheck for modules.d/99base

- modules.d/00warpclock/warpclock.sh
> fix(warpclock): shellcheck for modules.d/00warpclock

- modules.d/01fips/fips-boot.sh
- modules.d/01fips/fips-load-crypto.sh
- modules.d/01fips/fips.sh
- modules.d/01fips/module-setup.sh
> fix(fips): shellcheck for modules.d/01fips

- modules.d/01systemd-coredump/module-setup.sh
> fix(systemd-coredump): shellcheck for modules.d/01systemd-coredump

- modules.d/01systemd-initrd/module-setup.sh
> fix(systemd-initrd): shellcheck for modules.d/01systemd-initrd

- modules.d/01systemd-repart/module-setup.sh
> fix(systemd-repart): shellcheck for modules.d/01systemd-repart

- modules.d/01systemd-sysctl/module-setup.sh
> fix(systemd-sysctl): shellcheck for modules.d/01systemd-sysctl

- modules.d/01systemd-sysusers/module-setup.sh
> fix(systemd-sysusers): shellcheck for modules.d/01systemd-sysusers

- modules.d/02caps/module-setup.sh
> fix(caps): shellcheck for modules.d/02caps

- modules.d/02systemd-networkd/module-setup.sh
> fix(systemd-networkd): shellcheck for modules.d/02systemd-networkd

- modules.d/03modsign/load-modsign-keys.sh
> fix(modsign): shellcheck for modules.d/03modsign

- modules.d/04watchdog-modules/module-setup.sh
> fix(watchdog-modules): shellcheck for modules.d/04watchdog-modules

- modules.d/06dbus-broker/module-setup.sh
> fix(dbus-broker): shellcheck for modules.d/06dbus-broker

- modules.d/04watchdog/watchdog.sh
> fix(watchdog): shellcheck for modules.d/04watchdog

- modules.d/06dbus-daemon/module-setup.sh
> fix(dbus-daemon): shellcheck for modules.d/06dbus-daemon

- modules.d/30convertfs/convertfs.sh
> fix(convertfs): shellcheck for modules.d/30convertfs

- modules.d/35network-manager/module-setup.sh
- modules.d/35network-manager/nm-config.sh
- modules.d/35network-manager/nm-lib.sh
- modules.d/35network-manager/nm-run.sh
> fix(network-manager): shellcheck for modules.d/35network-manager

- modules.d/00systemd/module-setup.sh
> fix(systemd): shellcheck for modules.d/00systemd

- docs/BASH.md
Add a little document providing help in common bash problems.
> docs: add docs/BASH.md

- .github/workflows/lint.yml
- dracut-functions.sh
- dracut-init.sh
- dracut-logger.sh
- dracut.sh
> fix: shellcheck for dracut*.sh

- modules.d/10i18n/console_init.sh
- modules.d/10i18n/module-setup.sh
> fix(i18n): shellcheck for modules.d/10i18n

- modules.d/35network-wicked/module-setup.sh
> fix(network-wicked): shellcheck for modules.d/35network-wicked

- modules.d/40network/dhcp-root.sh
- modules.d/40network/ifname-genrules.sh
- modules.d/40network/module-setup.sh
- modules.d/40network/net-lib.sh
- modules.d/40network/netroot.sh
> fix(network): shellcheck for modules.d/40network

- modules.d/90crypt/crypt-cleanup.sh
- modules.d/90crypt/crypt-lib.sh
- modules.d/90crypt/cryptroot-ask.sh
- modules.d/90crypt/module-setup.sh
- modules.d/90crypt/parse-crypt.sh
- modules.d/90crypt/parse-keydev.sh
> fix(crypt): shellcheck for modules.d/90crypt

- modules.d/90btrfs/module-setup.sh
> fix(btrfs): shellcheck for modules.d/90btrfs

- modules.d/81cio_ignore/module-setup.sh
- modules.d/81cio_ignore/parse-cio_accept.sh
> fix(cio_ignore): shellcheck for modules.d/81cio_ignore

- modules.d/80lvmmerge/lvmmerge.sh
> fix(lvmmerge): shellcheck for modules.d/80lvmmerge

- modules.d/45ifcfg/write-ifcfg.sh
> fix(ifcfg): shellcheck for modules.d/45ifcfg

- modules.d/45url-lib/module-setup.sh
- modules.d/45url-lib/url-lib.sh
> fix(url-lib): shellcheck for modules.d/45url-lib

- modules.d/50drm/module-setup.sh
> fix(drm): shellcheck for modules.d/50drm

- modules.d/50gensplash/gensplash-emergency.sh
- modules.d/50gensplash/gensplash-newroot.sh
- modules.d/50gensplash/gensplash-pretrigger.sh
- modules.d/50gensplash/module-setup.sh
> fix(gensplash): shellcheck for modules.d/50gensplash

- modules.d/50plymouth/module-setup.sh
- modules.d/50plymouth/plymouth-newroot.sh
- modules.d/50plymouth/plymouth-populate-initrd.sh
- modules.d/50plymouth/plymouth-pretrigger.sh
> fix(plymouth): shellcheck for modules.d/50plymouth

- modules.d/80cms/cms-write-ifcfg.sh
- modules.d/80cms/cmsifup.sh
- modules.d/80cms/cmssetup.sh
- modules.d/80cms/module-setup.sh
> fix(cms): shellcheck for modules.d/80cms

- modules.d/90dmraid/dmraid.sh
- modules.d/90dmraid/module-setup.sh
> fix(dmraid): shellcheck for modules.d/90dmraid

- modules.d/90kernel-modules/insmodpost.sh
- modules.d/90kernel-modules/module-setup.sh
- modules.d/90kernel-modules/parse-kernel.sh
> fix(kernel-modules): shellcheck for modules.d/90kernel-modules

- modules.d/90livenet/fetch-liveupdate.sh
- modules.d/90livenet/livenetroot.sh
- modules.d/90livenet/module-setup.sh
- modules.d/90livenet/parse-livenet.sh
> fix(livenet): shellcheck for modules.d/90livenet

- modules.d/90lvm/lvm_scan.sh
- modules.d/90lvm/module-setup.sh
> fix(lvm): shellcheck for modules.d/90lvm

- modules.d/90multipath/module-setup.sh
- modules.d/90multipath/multipath-shutdown.sh
- modules.d/90multipath/multipathd-needshutdown.sh
- modules.d/90multipath/multipathd-stop.sh
> fix(multipath): shellcheck for modules.d/90multipath

- modules.d/90nvdimm/module-setup.sh
> fix(nvdimm): shellcheck for modules.d/90nvdimm

- modules.d/90ppcmac/load-thermal.sh
- modules.d/90ppcmac/module-setup.sh
> fix(ppcmac): shellcheck for modules.d/90ppcmac

- modules.d/91crypt-loop/crypt-loop-lib.sh
> fix(crypt-loop): shellcheck for modules.d/91crypt-loop

- modules.d/91zipl/install_zipl_cmdline.sh
- modules.d/91zipl/module-setup.sh
- modules.d/91zipl/parse-zipl.sh
> fix(zipl): shellcheck for modules.d/91zipl

- modules.d/95dasd/parse-dasd.sh
> fix(dasd): shellcheck for modules.d/95dasd

- modules.d/95dasd_rules/module-setup.sh
- modules.d/95dasd_rules/parse-dasd.sh
> fix(dasd_rules): shellcheck for modules.d/95dasd_rules

- modules.d/95dcssblk/parse-dcssblk.sh
> fix(dcssblk): shellcheck for modules.d/95dcssblk

- modules.d/99uefi-lib/uefi-lib.sh
> fix(uefi-lib): shellcheck for modules.d/99uefi-lib

- modules.d/99fs-lib/fs-lib.sh
- modules.d/99fs-lib/module-setup.sh
> fix(fs-lib): shellcheck for modules.d/99fs-lib

- modules.d/98syslog/module-setup.sh
- modules.d/98syslog/parse-syslog-opts.sh
- modules.d/98syslog/rsyslogd-start.sh
- modules.d/98syslog/rsyslogd-stop.sh
- modules.d/98syslog/syslog-cleanup.sh
> fix(syslog): shellcheck for modules.d/98syslog

- modules.d/99shutdown/module-setup.sh
- modules.d/99shutdown/shutdown.sh
> fix(shutdown): shellcheck for modules.d/99shutdown

- modules.d/99memstrack/memstrack-report.sh
- modules.d/99memstrack/memstrack-start.sh
- modules.d/99memstrack/module-setup.sh
> fix(memstrack): shellcheck for modules.d/99memstrack

- modules.d/99img-lib/img-lib.sh
- modules.d/99img-lib/module-setup.sh
> fix(img-lib): shellcheck for modules.d/99img-lib

- modules.d/98selinux/selinux-loadpolicy.sh
> fix(selinux): shellcheck for modules.d/98selinux

- modules.d/98pollcdrom/pollcdrom.sh
> fix(pollcdrom): shellcheck for modules.d/98pollcdrom

- modules.d/98integrity/evm-enable.sh
- modules.d/98integrity/ima-keys-load.sh
- modules.d/98integrity/ima-policy-load.sh
> fix(integrity): shellcheck for modules.d/98integrity

- modules.d/98ecryptfs/ecryptfs-mount.sh
> fix(ecryptfs): shellcheck for modules.d/98ecryptfs

- modules.d/98dracut-systemd/dracut-cmdline-ask.sh
- modules.d/98dracut-systemd/dracut-cmdline.sh
- modules.d/98dracut-systemd/dracut-emergency.sh
- modules.d/98dracut-systemd/dracut-initqueue.sh
- modules.d/98dracut-systemd/dracut-mount.sh
- modules.d/98dracut-systemd/dracut-pre-udev.sh
- modules.d/98dracut-systemd/module-setup.sh
- modules.d/98dracut-systemd/rootfs-generator.sh
> fix(dracut-systemd): shellcheck for modules.d/98dracut-systemd

- modules.d/97masterkey/masterkey.sh
> fix(masterkey): shellcheck for modules.d/97masterkey

- modules.d/95znet/parse-ccw.sh
> fix(znet): shellcheck for modules.d/95znet

- modules.d/95zfcp_rules/module-setup.sh
- modules.d/95zfcp_rules/parse-zfcp.sh
> fix(zfcp_rules): shellcheck for modules.d/95zfcp_rules

- modules.d/95zfcp/parse-zfcp.sh
> fix(zfcp): shellcheck for modules.d/95zfcp

- modules.d/95virtfs/mount-virtfs.sh
- modules.d/95virtfs/parse-virtfs.sh
> fix(virtfs): shellcheck for modules.d/95virtfs

- modules.d/95udev-rules/module-setup.sh
> fix(udev-rules): shellcheck for modules.d/95udev-rules

- modules.d/95ssh-client/module-setup.sh
> fix(ssh-client): shellcheck for modules.d/95ssh-client

- modules.d/95rootfs-block/module-setup.sh
- modules.d/95rootfs-block/mount-root.sh
- modules.d/95rootfs-block/parse-block.sh
> fix(rootfs-block): shellcheck for modules.d/95rootfs-block

- modules.d/95resume/parse-resume.sh
- modules.d/95resume/resume.sh
> fix(resume): shellcheck for modules.d/95resume

- modules.d/95qeth_rules/module-setup.sh
> fix(qeth_rules): shellcheck for modules.d/95qeth_rules

- modules.d/95nvmf/module-setup.sh
- modules.d/95nvmf/parse-nvmf-boot-connections.sh
> fix(nvmf): shellcheck for modules.d/95nvmf

- modules.d/95nfs/nfs-lib.sh
- modules.d/95nfs/nfsroot-cleanup.sh
- modules.d/95nfs/nfsroot.sh
- modules.d/95nfs/parse-nfsroot.sh
> fix(nfs): shellcheck for modules.d/95nfs

- modules.d/95nbd/module-setup.sh
- modules.d/95nbd/nbdroot.sh
- modules.d/95nbd/parse-nbdroot.sh
> fix(nbd): shellcheck for modules.d/95nbd

- modules.d/95lunmask/fc_transport_scan_lun.sh
- modules.d/95lunmask/module-setup.sh
- modules.d/95lunmask/parse-lunmask.sh
- modules.d/95lunmask/sas_transport_scan_lun.sh
> fix(lunmask): shellcheck for modules.d/95lunmask

- modules.d/95fstab-sys/mount-sys.sh
> fix(fstab-sys): shellcheck for modules.d/95fstab-sys

- modules.d/95fcoe-uefi/module-setup.sh
- modules.d/95fcoe-uefi/parse-uefifcoe.sh
> fix(fcoe-uefi): shellcheck for modules.d/95fcoe-uefi

- modules.d/91crypt-gpg/crypt-gpg-lib.sh
- modules.d/91crypt-gpg/module-setup.sh
> fix(crypt-gpg): shellcheck for modules.d/91crypt-gpg

- modules.d/90dmsquash-live/dmsquash-live-root.sh
- modules.d/90dmsquash-live/dmsquash-liveiso-genrules.sh
- modules.d/90dmsquash-live/iso-scan.sh
- modules.d/90dmsquash-live/module-setup.sh
> fix(dmsquash-live): shellcheck for modules.d/90dmsquash-live

- test/TEST-04-FULL-SYSTEMD/test.sh
> test(FULL-SYSTEMD): add fuse kernel module in test root

- modules.d/95cifs/cifs-lib.sh
- modules.d/95cifs/parse-cifsroot.sh
> fix(cifs): shellcheck for modules.d/95cifs

- modules.d/90mdraid/md-shutdown.sh
- modules.d/90mdraid/mdmon-pre-shutdown.sh
- modules.d/90mdraid/mdraid-cleanup.sh
- modules.d/90mdraid/mdraid-waitclean.sh
- modules.d/90mdraid/mdraid_start.sh
- modules.d/90mdraid/module-setup.sh
- modules.d/90mdraid/parse-md.sh
> fix(mdraid): shellcheck for modules.d/90mdraid

- modules.d/95iscsi/iscsiroot.sh
- modules.d/95iscsi/module-setup.sh
- modules.d/95iscsi/mount-lun.sh
- modules.d/95iscsi/parse-iscsiroot.sh
> fix(iscsi): shellcheck for modules.d/95iscsi

- modules.d/35network-legacy/dhclient-script.sh
- modules.d/35network-legacy/dhcp-multi.sh
- modules.d/35network-legacy/ifup.sh
- modules.d/35network-legacy/kill-dhclient.sh
- modules.d/35network-legacy/module-setup.sh
- modules.d/35network-legacy/net-genrules.sh
- modules.d/35network-legacy/parse-bond.sh
- modules.d/35network-legacy/parse-bridge.sh
- modules.d/35network-legacy/parse-ifname.sh
- modules.d/35network-legacy/parse-ip-opts.sh
- modules.d/35network-legacy/parse-team.sh
- modules.d/35network-legacy/parse-vlan.sh
> fix(network-legacy): shellcheck for modules.d/35network-legacy

- modules.d/90dm/dm-shutdown.sh
> fix(dm): shellcheck for modules.d/90dm

- fedora-test.sh
> fix(fedora-test.sh): shellcheck for fedora-test.sh

- test/run-qemu
> fix(test/run-qemu): shellcheck for test/run-qemu

- test/test-functions
> fix(test/test-functions): shellcheck for test/test-functions

- lsinitrd.sh
> fix(lsinitrd.sh): shellcheck for lsinitrd.sh

- examples/yocto/postinst-intercepts/execute_dracut
> fix(examples/yocto): shellcheck

- test/TEST-99-RPM/test.sh
> fix(TEST RPM): shellcheck

- test/TEST-98-GETARG/test.sh
> fix(TEST GETARG): shellcheck

- test/TEST-60-BONDBRIDGEVLANIFCFG/client-init.sh
- test/TEST-60-BONDBRIDGEVLANIFCFG/create-root.sh
- test/TEST-60-BONDBRIDGEVLANIFCFG/server-init.sh
- test/TEST-60-BONDBRIDGEVLANIFCFG/test.sh
> fix(TEST BONDBRIDGEVLANIFCFG): shellcheck

- test/TEST-40-NBD/client-init.sh
- test/TEST-40-NBD/create-client-root.sh
- test/TEST-40-NBD/create-encrypted-root.sh
- test/TEST-40-NBD/create-server-root.sh
- test/TEST-40-NBD/cryptroot-ask.sh
- test/TEST-40-NBD/server-init.sh
- test/TEST-40-NBD/test.sh
> fix(TEST NBD): shellcheck

- test/TEST-35-ISCSI-MULTI/client-init.sh
- test/TEST-35-ISCSI-MULTI/create-client-root.sh
- test/TEST-35-ISCSI-MULTI/create-server-root.sh
- test/TEST-35-ISCSI-MULTI/server-init.sh
- test/TEST-35-ISCSI-MULTI/test.sh
> fix(TEST ISCSI-MULTI): shellcheck

- test/TEST-15-BTRFSRAID/create-root.sh
- test/TEST-15-BTRFSRAID/test.sh
> fix(TEST BTRFSRAID): shellcheck

- test/TEST-13-ENC-RAID-LVM/create-root.sh
- test/TEST-13-ENC-RAID-LVM/cryptroot-ask.sh
- test/TEST-13-ENC-RAID-LVM/test.sh
> fix(TEST ENC-RAID-LVM): shellcheck

- modules.d/95zfcp_rules/module-setup.sh
> fix(zfcp_rules): require bash

- test/TEST-20-NFS/client-init.sh
- test/TEST-20-NFS/create-root.sh
- test/TEST-20-NFS/server-init.sh
- test/TEST-20-NFS/test.sh
> fix(TEST NFS): shellcheck

- test/TEST-17-LVM-THIN/create-root.sh
- test/TEST-17-LVM-THIN/test-init.sh
- test/TEST-17-LVM-THIN/test.sh
> fix(TEST LVM-THIN): shellcheck

- test/TEST-16-DMSQUASH/test-init.sh
- test/TEST-16-DMSQUASH/test.sh
> fix(TEST DMSQUASH): shellcheck

- test/TEST-14-IMSM/create-root.sh
- test/TEST-14-IMSM/cryptroot-ask.sh
- test/TEST-14-IMSM/test-init.sh
- test/TEST-14-IMSM/test.sh
> fix(TEST IMSM): shellcheck

- test/TEST-12-RAID-DEG/create-root.sh
- test/TEST-12-RAID-DEG/cryptroot-ask.sh
- test/TEST-12-RAID-DEG/test-init.sh
- test/TEST-12-RAID-DEG/test.sh
> fix(TEST RAID-DEG): shellcheck

- test/TEST-11-LVM/create-root.sh
- test/TEST-11-LVM/test-init.sh
- test/TEST-11-LVM/test.sh
> fix(TEST LVM): shellcheck

- test/TEST-10-RAID/create-root.sh
- test/TEST-10-RAID/test-init.sh
- test/TEST-10-RAID/test.sh
> fix(TEST RAID): shellcheck

- test/TEST-04-FULL-SYSTEMD/create-root.sh
- test/TEST-04-FULL-SYSTEMD/test-init.sh
- test/TEST-04-FULL-SYSTEMD/test.sh
> fix(TEST FULL-SYSTEMD): shellcheck

- test/TEST-03-USR-MOUNT/create-root.sh
- test/TEST-03-USR-MOUNT/test-init.sh
- test/TEST-03-USR-MOUNT/test.sh
> fix(TEST USR-MOUNT): shellcheck

- test/TEST-02-SYSTEMD/create-root.sh
- test/TEST-02-SYSTEMD/systemd-analyze.sh
- test/TEST-02-SYSTEMD/test-init.sh
- test/TEST-02-SYSTEMD/test.sh
> fix(TEST SYSTEMD): shellcheck

- modules.d/95fcoe/lldpad.sh
- modules.d/95fcoe/stop-fcoe.sh
> fix(fcoe): remove needless bash dependency

- test/TEST-50-MULTINIC/client-init.sh
- test/TEST-50-MULTINIC/create-root.sh
- test/TEST-50-MULTINIC/server-init.sh
- test/TEST-50-MULTINIC/test.sh
> fix(TEST MULTINIC): shellcheck

- modules.d/95fcoe-uefi/module-setup.sh
> fix(fcoe-uefi): add bash dependency

- modules.d/02caps/module-setup.sh
> fix(caps): require bash

- modules.d/90multipath/module-setup.sh
`$_allow` should not have been quoted, because it can be multiple options.
Instead of unquoting it, convert it to an associative array with easy
deduplication and prefix every device with the `--allow` option.
Fixes: https://github.com/dracutdevs/dracut/issues/1274
> fix(multipath): shellcheck regression

- modules.d/80cms/module-setup.sh
> fix(cms): require bash

- modules.d/90livenet/fetch-liveupdate.sh
> fix(livenet): fetch-liveupdate.sh does not require bash

- modules.d/80lvmmerge/module-setup.sh
> fix(lvmmerge): depend on bash

- .packit.yml
remove the offending parameters, which cause errors described in
https://github.com/dracutdevs/dracut/issues/1346
until we found the correct config to be used.
Fixes #
> ci: remove packit config causing errors

- modules.d/62bluetooth/module-setup.sh
Don't install files from `/var` in the non-hostonly case.
Use fileglobs, instead of `find`.
> fix(bluetooth): shellcheck and hostonly corrections

- dracut.spec
- modules.d/01systemd-timesyncd/module-setup.sh
- modules.d/01systemd-timesyncd/timesyncd-tmpfile-dracut.conf
Introducing the systemd-timesyncd module
Fixes #
> feat(systemd-timesyncd): introducing the systemd-timesyncd module

- dracut.spec
- modules.d/01systemd-hostnamed/99-systemd-networkd-dracut.conf
- modules.d/01systemd-hostnamed/module-setup.sh
- modules.d/01systemd-hostnamed/org.freedesktop.hostname1_dracut.conf
- modules.d/01systemd-hostnamed/systemd-hostname-dracut.conf
Introducing the systemd-hostnamed module.
Fixes #
> feat(systemd-hostnamed): introducing the systemd-hostnamed module

- dracut.spec
- modules.d/01systemd-resolved/module-setup.sh
- modules.d/01systemd-resolved/resolved-tmpfile-dracut.conf
Introducing the systemd-resolved module
Fixes #
> feat(systemd-resolved): introducing the systemd-resolved module

- modules.d/01systemd-modules-load/module-setup.sh
- Removing dependency on the systemd meta module since it causes circular dependency,
prevents the existance of multiple systemd based meta modules and is redunant.
- Removing directory creation for modules-load since it should not be
necessary and if it turns out that it is, it will be re-introduced in the
form of a systemd tmpfile instead of inst_dir.
- Add a missing inclusion of configuration files placed in /usr/lib/modules-load.d
and /etc/modules-load.d ( hostonly ) directories.
- Fix a spelling error in the systemd type unit file conf directory overwrite
in the hostonly section.
Fixes #
> fix(systemd-modules-load): misc repairs

- dracut.spec
- modules.d/01systemd-timedated/module-setup.sh
Introducing the systemd-timedated module.
systemd-timesyncd will be introduced as a separated module.
Fixes #
> feat(systemd-timedated): introducing the systemd-timedated module

- modules.d/01systemd-hostnamed/module-setup.sh
We cant wait for response on #1384 and leave the linter broken so let's force merge this asap.
Fixes #
> fix(systemd-hostnamed): extra quote

- modules.d/01systemd-ask-password/module-setup.sh
- modules.d/01systemd-coredump/module-setup.sh
- modules.d/01systemd-hostnamed/module-setup.sh
- modules.d/01systemd-resolved/module-setup.sh
- modules.d/01systemd-timesyncd/module-setup.sh
Refactoring require_binaries in check() for systemd modules
Fixes #
> refactor: check() in systemd modules

- modules.d/01systemd-initrd/module-setup.sh
Adding a new systemd initrd-usr-fs.target to the systemd-initrd module
Fixes #
> feat(systemd-initrd): add initrd-usr-fs.target

- test/TEST-03-USR-MOUNT/create-root.sh
- test/TEST-04-FULL-SYSTEMD/create-root.sh
- test/TEST-15-BTRFSRAID/create-root.sh
> test: don't fail on modprobe btrfs in create-root.sh

- .github/workflows/fedora.yml
> ci: reorder the tests

- dracut.spec
- modules.d/01systemd-verity/module-setup.sh
Introducing the systemd-verity module.
Fixes #
> feat(systemd-verity): introducing the systemd-verity module

- .github/workflows/lint.yml
See also:
https://github.com/luizm/action-sh-checker/pull/40#issuecomment-829260125
> ci: switch to action-sh-checker v0.2.0

- dracut.spec
- modules.d/91tpm2-tss/module-setup.sh
Introducing the tpm2-tss module. 
Note this depends on the udev global var PR so dont merge until after we have merged it.
Fixes #
> feat(tpm2-tss): introducing the tpm2-tss module

- modules.d/98integrity/evm-enable.sh
The current EVM script does not handle the EVM setup properly when X509
certificates are involved. In this patch we extend the setup and add
the necessary flags for support of EVM activation that include
x509 certificates, possibly in conjunction with an HMAC key. We also
first try activating EVM for x509 certificates using
EVM_ALLOW_METADATA_WRITES for newer kernels, then without it for older
ones that did not support this flag.
We add support for additional EVM activation bits to be set, such
as EVM_SETUP_COMPLETE (0x80000000) via the config file and
EVM_ACTIVATION_BITS variable.
To avoid error messages related to unloading the HMAC key if none is
used, only attempt to unload the HMAC key if one was actually set.
We add documentation about the variables that can be set in the EVM
config …
> fix(integrity): Properly set up EVM when using an x509 cert

- modules.d/01systemd-udevd/module-setup.sh
Adding missing udev id program files
Fixes #
> fix(systemd-udevd): add udev id program files

- modules.d/00systemd/module-setup.sh
Include all nss libraries so other modules dont have to.
Fixes #
> fix(systemd): include all nss libraries

- modules.d/01systemd-resolved/module-setup.sh
Removing inclusion of nss libraries since they are part of
the systemd module now.
Fixes #
> fix(systemd-resolved): remove nss libraries

- modules.d/90mdraid/md-noddf.sh
- modules.d/90mdraid/md-noimsm.sh
- modules.d/90mdraid/module-setup.sh
mdadm 4.1 was released 2 years ago so it's safe to assume
that everyone are on 4.1.X branch now...
Fixes #
> fix(mdraid): remove dependency statements

- Makefile
> chore: fix indent-c path for src directory

- test/TEST-04-FULL-SYSTEMD/test.sh
If there is no `rpm`, try `pacman` to get a full list of systemd files
to install into the real test root.
Fixes #
> test(FULL SYSTEMD): try pacman rather than rpm on Arch

- docs/HACKING.md
> docs: document how to run the test suite in podman on Fedora and Arch

- docs/HACKING.md
> docs: install `which` in Arch container

- modules.d/01fips/module-setup.sh
This is needed to be able to claim these ciphers as approved.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1775692
> fix(fips): add dh and ecdh ciphers

- dracut.sh
- modules.d/01systemd-tmpfiles/module-setup.sh
- pkgbuild/dracut.spec
This pull request introduces the systemd-tmpfiles module and fixes a missing global variable which it uses.
Fixes #
> feat(systemd-tmpfiles): introducing the systemd-tmpfiles module

- modules.d/01systemd-ldconfig/module-setup.sh
- pkgbuild/dracut.spec
Introducing the systemd-ldconfig module
Fixes #
> feat(systemd-ldconfig): introducing the systemd-ldconfig module

- modules.d/01systemd-rfkill/module-setup.sh
- pkgbuild/dracut.spec
Introducing the systemd-rfkill module 
Fixes #
> feat(systemd-rfkill): introducing the systemd-rfkill module

- modules.d/01systemd-journald/initrd.conf
- modules.d/01systemd-journald/module-setup.sh
- pkgbuild/dracut.spec
Introducing the systemd-journald module
Fixes #
> feat(systemd-journald): introducing the systemd-journald module

- .github/workflows/container.yml
- test/container/Dockerfile-Arch
- test/container/Dockerfile-Fedora-33
- test/container/Dockerfile-Fedora-34
- test/container/Dockerfile-Fedora-latest
- test/container/Dockerfile-OpenSuse-latest
> ci: build container images and push to ghcr.io

- test/container/Dockerfile-Arch
> ci: cleanup the arch container

- test/container/Dockerfile-Arch
> ci: really, really cleanup the arch container

- test/container/Dockerfile-Arch
> ci: add cpio and pigz to arch container

- modules.d/91crypt-gpg/module-setup.sh
On Arch things are different for some reason.
Fixes #
> fix(crypt-gpg): cope with different scdaemon location

- modules.d/95iscsi/iscsiroot.sh
This removes a fork/exec and additionally gives more information in debug logs.
Fixes #
> fix(iscsi): replace sed call with bash internals

- modules.d/95nbd/nbdroot.sh
This reduces the quirks.
Fixes #
> fix(nbd): assume nbd version >= 3.8

- modules.d/95cifs/module-setup.sh
- modules.d/95nfs/module-setup.sh
- modules.d/95ssh-client/module-setup.sh
> fix: cope with distributions with `/usr/etc` files

- docs/HACKING.md
> docs: document testing with containers

- modules.d/01systemd-sysext/module-setup.sh
- pkgbuild/dracut.spec
Introducing the systemd-sysext module.
Fixes #
> feat(systemd-sysext): introducing the systemd-sysext module

- .github/workflows/container.yml
- test/container/Dockerfile-Fedora-rawhide
Remove Fedora 34 for now, as it is fedora:latest
Fixes #
> ci: create a fedora rawhide container

- .packit.yml
> fix(packit): downstream has renamed the master branch to main

- test/container/Dockerfile-Fedora-33
- test/container/Dockerfile-Fedora-34
- test/container/Dockerfile-Fedora-latest
- test/container/Dockerfile-Fedora-rawhide
> ci: add shfmt to Fedora containers

- modules.d/00bash/module-setup.sh
- Remove hard coded path to binary
- Add missing license header
- Document sections
- refactor install section
Fixes #
> fix(bash): minor cleanups

- modules.d/00mksh/module-setup.sh
- Remove hard coded path to binary
- Add missing license header
- Document sections
- refactor install section
Fixes #
> fix(mksh): minor cleanups

- modules.d/00dash/module-setup.sh
- Remove hard coded path to binary
- Add missing license header
- Document sections
- refactor install section
Fixes #
> fix(dash): minor cleanups

- modules.d/00warpclock/module-setup.sh
- modules.d/00warpclock/warpclock.sh
- Removing shell mode lines
- Remove uncessary file requirements
- Remove hard coded path to binary
- Add missing license header
- Document sections
- refactor install section
Fixes #
> fix(warpclock): minor cleanups

- modules.d/99fs-lib/module-setup.sh
This pull request fixes the installation of fsck programs which got broken by this commit https://github.com/dracutdevs/dracut/commit/82d9fbf193b0d8bd810c6cbee726a1f851e5ee75#diff-52b92d069b8698c8b6332b0357d1ffe1bec3f07f4a23406a3c697f11d2cb10ce
Fixes #1515
> fix install fsck utilities

- modules.d/00mksh/module-setup.sh
This pull request changes requirements on printf for mksh module
Fixes #1530
> fix(mksh): requires printf

- modules.d/98integrity/evm-enable.sh
Add support for loading EVM x509 certs from a directory that the user can
specify with the EVMKEYSDIR variable in the evm config file. By default
the additional certs are loaded from /etc/keys/evm.
Support for multiple EVM keys allows the usage in a system of files with
signed metadata from multiple parties.
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
Reviewed-by: Roberto Sassu <roberto.sassu@huawei.com>
Fixes #
> fix(integrity): add support for loading multiple EVM x509 certs

- src/install/dracut-install.c
- src/install/log.c
- src/install/macro.h
- src/install/util.c
- src/install/util.h
Implemented a simple wrapper for asprintf
log.c improvements
Fixes #
> Install fixes

- modules.d/95iscsi/iscsiroot.sh
- modules.d/95iscsi/module-setup.sh
- [x ] I have tested it locally
Fixes #
> fix(iscsi): several fixes for iscsi root

- src/install/dracut-install.c
This ensures that we install base libraries for alternative library implementations under [glibc-hwcaps subdirectory](https://sourceware.org/pipermail/libc-alpha/2020-June/115250.html).
> fix(install): extend hwcaps library handling to libraries under glibc-hwcaps

- dracut-functions.sh
**Preconditions**
- Host-only mode.
- Symlinks of all block devices needed to boot the system pointing to virtual subsystems.
**Issue**
The system does not boot because dracut does not install the kernel module of the block device that contains the root filesystem.
**Issue description**
The `get_dev_module` function uses `udevadm info -a` to get the corresponding kernel modules of a /sys/class/\*/\* or /dev/\* device. This function is called in modules.d/90kernel-modules/module-setup.sh ([line 20](https://github.com/dracutdevs/dracut/blob/master/modules.d/90kernel-modules/module-setup.sh#L20)) to detect if dracut must install block device drivers in host-only mode.
The symlinks in /sys/dev/block/ usually point to "real" devices in /sys/devices/pci*. But, we have come across some NVMe …
> fix(dracut-functions.sh): get block device driver if in a virtual subsystem

- dracut-initramfs-restore.sh
Adding missing default paths.
Fixes #1628
Fixes #
> fix(dracut-initramfs-restore.sh): add missing default paths

- dracut.sh
Dracut currently calls `eu-strip` or `strip` with -g, which only strips
out .debug_* sections. symtab and strtab are kept, but are not required
for runtime, and people will rarely need to do binary level debugging
work in initramfs.
So introduce a --aggresive-strip options, try strip out all sections
that are not required for runtime. This can help reduce the binary size
by a lot.
For example, the size of libc.so is reduced by a lot when stripped
with no option than with -g.
3014184 libc-2.28.orig.so
2970920 libc-2.28.strip-g.so
1460904 libc-2.28.strip.so
Signed-off-by: Kairui Song <kasong@tencent.com>
> feat(dracut.sh): add --aggresive-strip option

- dracut-init.sh
A dreadful copy & paste or kill-ring-save & yank error, most surely.
- [ x ] I have tested it locally
- [ x ] I have reviewed and updated any documentation if relevant
- [ :( ] I am providing new code and test(s) for it
> dracut-init: fix a comment

- modules.d/90crypt/module-setup.sh
- modules.d/91pkcs11/module-setup.sh
- pkgbuild/dracut.spec
Add a pkcs11 ( library ) module which should ( in theory ) work with systemd + pkcs11. 
If people have the time and hw to test this feel free to do so and provide feedback how that went. 
Fixes #
> Introducing pkcs11 module

- dracut-functions.sh
This fixes an embarrassing bug in my own code.
Fix route parsing
Fixes #857
> fix route parsing

- modules.d/91pcsc/module-setup.sh
- modules.d/91pcsc/pcscd.service
- modules.d/91pcsc/pcscd.socket
- pkgbuild/dracut.spec
Introducing the pcsc module.
Since I lack the required hw for this it would be nice if someone who has the time and the hw ( like nitrokey ) could try to unlock a LUKS2 partition using X509 certificate to test this and provide feedback how that went.
Fixes #
> feat(pcsc): introducing the pcsc module

- src/dracut-cpio/src/main.rs
This pull request fixes dracut-cpio's `dev_t` -> `rmajor` / `rminor` mapping so that block devices, etc. are correctly encoded in the cpio archive.
Fixes #1695
> fix(cpio): test and fix dev_t -> rmajor / rminor mapping

- configure
- src/install/util.c
Signed-off-by: Shreenidhi Shedi <sshedi@vmware.com>
Check for SYS_gettid during configure stage
Fixes #
> fix(configure): check for SYS-gettid during configure

- man/dracut.cmdline.7.asc
> specify, what action to execute in case of a critical failure. rd.shell=0 also be specified.
> dracut.cmdline.7: {=> must} also be specified

- pkgbuild/dracut.spec
Add the connman module to the spec file
Fixes #
> fix(dracut.spec): add connman module

- .github/workflows/container.yml
- .github/workflows/integration.yml
- test/container/Dockerfile-Debian
> ci: add Debian Linux to limited tests

- test/Makefile
- test/container/Dockerfile-Debian
> ci: on debian, default shell is not bash

- test/TEST-04-FULL-SYSTEMD/test.sh
> fix(test): add support for dpkg to pass the test on debian

- test/TEST-01-BASIC/test.sh
- test/TEST-02-SYSTEMD/test.sh
- test/TEST-03-USR-MOUNT/test.sh
Not sure if these comments are still useful.
> fix(test): remove stale comment

- modules.d/98integrity/evm-enable.sh
- modules.d/98integrity/ima-keys-load.sh
* Drop unused variable
* Do not enable EVM if there are no key in the system
Fixes #1847
> Fix ima evm

- src/install/dracut-install.c
- src/install/util.c
- src/install/util.h
@dtardon
@lnykryn
Can you have a look?
> fix(dracut-install): do not try to copy files from the root directory

- modules.d/90multipath/multipathd-configure.service
- modules.d/90multipath/multipathd.sh
Noticed these while perusing this code. I don't think it's currently causing any issues, other than added confusion. :)
See individual commits.
> 90multipath: minor tweaks to multipathd-configure.service

- README.md
Point to the github wiki. Add link to News.
Remove broken badge links.
> docs(README.md): update wiki link

- test/TEST-16-DMSQUASH/test.sh
- test/container/Dockerfile-Arch
Include additional kernel drivers and install squashfs-tools
into the arch container.
> test(16-DMSQUASH): make it pass on arch

- modules.d/95virtiofs/module-setup.sh
- modules.d/95virtiofs/mount-virtiofs.sh
- modules.d/95virtiofs/parse-virtiofs.sh
Fixes: c29325a982013a315418cdb2318e90cf77e387b5
> fix(virtiofs): make shebangs work on split-usr systems

- CONTRIBUTING.md
- docs/HACKING.md
Note down some commonly agreed, but not yet documented guidelines
to have a baseline that can be improved later.
> docs: create CONTRIBUTING.md

- test/dracut.conf.test
Empty file and it is not used. Has not been used for over a decade :-)
Fixes #
> test: remove dracut.conf.test

- man/dracut.cmdline.7.asc
- modules.d/98dracut-systemd/dracut-mount.sh
- modules.d/98dracut-systemd/dracut-pre-mount.sh
- modules.d/98dracut-systemd/dracut-pre-pivot.sh
- modules.d/98dracut-systemd/dracut-pre-trigger.sh
- modules.d/98dracut-systemd/dracut-pre-udev.sh
- modules.d/99base/init.sh
Align man page and script messages.
> docs: clarify that rd.break stops before the breakpoint starts

- modules.d/01systemd-pstore/module-setup.sh
- modules.d/01systemd-tmpfiles/module-setup.sh
- pkgbuild/dracut.spec
Introducing the systemd-pstore module.
> feat(systemd-pstore): introducing the systemd-pstore module

- .github/workflows/container.yml
- .github/workflows/manualtest.yml
- test/container/Dockerfile-Gentoo
> ci: add Gentoo Linux container

- src/install/dracut-install.c
Prefix + error description at the end.
stale bot closed my previous PR #1855
> refactor(dracut-install): resolve_deps: improve error message

- .github/dependabot.yml
> feat(github): automating dependency updates

- dracut.conf.d/suse.conf.example
This pull request updates SUSE-specific config.
- Remove reference to mkinitrd.
- Update compression parameters.
- Remove explanatory code that is currently shipped in its own config file on SUSE.
> ci(suse.conf.example): update SUSE-specific config

- .github/workflows/integration.yml
> ci: integration test for openrc and musl

- dracut.sh
- test/TEST-01-BASIC/test.sh
> fix(dracut.sh): make omit-drivers option do exact match for names

- modules.d/01systemd-pcrphase/module-setup.sh
- pkgbuild/dracut.spec
> feat(systemd-pcrphase): introducing the systemd-pcrphase module

- modules.d/90multipath/module-setup.sh
Recent multipath-tools (0.9.2) added a tmpfiles.d template. Install it
if present.
> feat(multipath): install tmpfiles.d config file

- test/TEST-01-BASIC/finished-false.sh
- test/TEST-01-BASIC/hard-off.sh
- test/TEST-01-BASIC/test.sh
- test/TEST-02-SYSTEMD/finished-false.sh
- test/TEST-02-SYSTEMD/hard-off.sh
- test/TEST-02-SYSTEMD/test.sh
- test/TEST-03-USR-MOUNT/test.sh
- test/TEST-20-NFS/test.sh
- test/TEST-50-MULTINIC/test.sh
- test/TEST-60-BONDBRIDGEVLANIFCFG/test.sh
- test/TEST-63-DRACUT-CPIO/test.sh
make test 01 and 02 use the test dracut modules
> test: make test 01 and 02 use the test dracut modules

- test/TEST-16-DMSQUASH/finished-false.sh
- test/TEST-16-DMSQUASH/hard-off.sh
- test/TEST-16-DMSQUASH/test.sh
> test(16): make test 16 use the test dracut modules

- modules.d/99fs-lib/fs-lib.sh
> feat(fs-lib): make gentoo container pass test-01

- tools/test-github.sh
Test 99 has been removed from the repo - https://github.com/dracutdevs/dracut/pull/2055
> tests: remove dead code regarding special handling of test 99

- .github/workflows/manualtest.yml
Timesaver for running tests during development and reviews.
> ci: teach manual test workflow to run several tests

- test/container/Dockerfile-Debian
- test/container/Dockerfile-Gentoo
- test/container/Dockerfile-OpenSuse-latest
Add more packages to enable running more tests
> ci: improve test containers and make tests 14 and 17 pass on debian

- lsinitrd.sh
Signed-off-by: Kenneth D'souza <kennethdsouza94@gmail.com>
Fixes #
> fix(lsinitrd.sh):  add a missing path to image

- pkgbuild/dracut.spec
This is a follow-up to 40dd5c90e0efcb9ebaa9abb42a38c7316e9706bd
> feat(overlayfs): add new overlayfs module to dracut.spec

- NEWS.md
> fix(NEWS.md): add missing entries

- test/TEST-20-NFS/test.sh
- test/TEST-50-MULTINIC/client-init.sh
- test/TEST-50-MULTINIC/test.sh
- test/TEST-60-BONDBRIDGEVLANIFCFG/test.sh
This pull request hopefully fixes the 50-multinic test that used to randomly fail with the network-manager module.
> Improvements for multinic test with NetworkManager

- dracut-init.sh
- modules.d/00systemd/module-setup.sh
- modules.d/90kernel-modules-extra/module-setup.sh
- modules.d/90livenet/parse-livenet.sh
- modules.d/95zfcp_rules/parse-zfcp.sh
> chore(shfmt): update the code to pass with version 3.5.1

- dracut-functions.sh
- modules.d/90kernel-modules/module-setup.sh
This pull request contains fixes to properly handle UFS storage.
> fix(kernel-modules): fixes for UFS

- src/install/dracut-install.c
During search for fw_devlink suppliers, it's possible to encounter a situation where supplier A depends on supplier B, and supplier B has a parent node that depends on supplier A. This leads to an infinite recursion.
To fix this, make sure suppliers are only processed once.
> fix(dracut-install): fix possible infinite recursion with suppliers

- modules.d/90dmsquash-live/dmsquash-live-root.sh
Follow-up to https://github.com/dracutdevs/dracut/pull/1934
Fixes #2232
CC @FGrose @Conan-Kudo @AdamWill
> fix(dmsquash-live): restore compatibility with earlier releases

- dracut-functions.sh
In some x86_64 platforms such as Intel Elkhartlake, an issue of missing
necessary modules due to udevadm drivers field unmatch the real kernel module
name is found:
$ udevadm info -a /dev/block/179:1
looking at parent device '/devices/pci0000:00/0000:00:1a.0/mmc_host/mmc0/mmc0:0001':
KERNELS=="mmc0:0001"
SUBSYSTEMS=="mmc"
DRIVERS=="mmcblk"
....
The DRIVERS field, aka mmcblk will be given to instmods to install the
corresponding mmc_block.ko kernel module. However mmc_block.ko cannot be
selected by string mmcblk, as a result, mmc_block.ko cannot be installed
in hostonly-mode strict, which will fail to bootup the machine such as in
kdump cases:
$ /usr/lib/dracut/dracut-install -D /var/tmp --kerneldir /lib/modules/$(uname -r)/ -m mmcblk
dracut-install: Failed to find module 'mmcblk'
In this …
> fix(dracut-functions.sh): convert mmcblk to the real kernel module name

- modules.d/01systemd-creds/module-setup.sh
Introducing the `systemd-creds` module.
Refs:
- https://systemd.io/CREDENTIALS/
- https://www.freedesktop.org/software/systemd/man/systemd.system-credentials.html
- https://www.freedesktop.org/software/systemd/man/systemd-creds.html
> feat(systemd-creds): introducing the systemd-creds module

- test/container/Dockerfile-OpenSuse-latest
> ci: install multipath-tools into openSuse container

- .github/stale.yml
> fix(github): exempt issues in a milestone

- dracut.sh
> fix(dracut.sh): silence the output of hardlinking files by default

- man/dracut.asc
- man/dracut.cmdline.7.asc
- man/dracut.usage.asc
Promote ext4 instead of ext3 in the manual.
> docs: change ext3 to ext4

- test/container/Dockerfile-Arch
- test/container/Dockerfile-Debian
- test/container/Dockerfile-Fedora-latest
- test/container/Dockerfile-Gentoo
- test/container/Dockerfile-OpenSuse-latest
Remove /etc/profile.d/dracut-test.sh from test containers
Fixes #2369
> ci: cleanup containers

- modules.d/80test-makeroot/module-setup.sh
- test/TEST-01-BASIC/test.sh
- test/TEST-02-SYSTEMD/test.sh
- test/TEST-03-USR-MOUNT/test.sh
- test/TEST-04-FULL-SYSTEMD/test.sh
- test/TEST-16-DMSQUASH/test.sh
Improve test-makeroot module
Fixes #2351
> test: move more makeroot dependencies into test-makeroot dracut module

- modules.d/35network-legacy/parse-ip-opts.sh
Signed-off-by: lilinjie lilinjie@uniontech.com
fix: a typo fix
Fixes #
> fix(parse-ip-opts.sh): fix typo

- test/container/Dockerfile-Debian
> ci: add dependencies to Debian container

- .github/workflows/integration.yml
> ci: switching the musl test to 18 (uefi)

- .github/workflows/integration.yml
> ci: run all local tests on all containers (including Gentoo)
