modules.d/90crypt/crypt-lib.sh

If `crypt-lib.sh` is sourced from any `#!/bin/sh` script, a POSIX shell quirk is in effect that causes variable assignments to "special builtins" (such as `shift`) to leak to their context. So the buggy code works even despite the missing semicolons.
But if it is sourced by "bash acting under its own name", i.e. from any `#!/bin/bash` script, the quirk is disabled, `tty_cmd`/`tty_prompt` are undefined, and `ask_for_password` doesn't do anything if plymouth is not present.

Fix ask_for_password bug breaking bash without plymouth

---

modules.d/50plymouth/module-setup.sh

plymouth-set-default-theme is not shipped with ubuntu and therefore
causes errors.

Add plymouth-set-default-theme to the plymouth dependencies

---

dracut.cmdline.7.asc
modules.d/90lvm/lvm_scan.sh

One of the two patches will skip the activation of LVs which have the activationskip bit set.
https://bugzilla.redhat.com/show_bug.cgi?id=1186854

Respect LVM activationskip

---

modules.d/40network/dhclient-script.sh

When current dracut receives an ip with netmask of 255.255.255.255 via DHCP,
setting the also supplied default gateway fails (because it is obviously not
within the netmask).
The setup with a netmask of /32 is quite common in colocation datacenters
where you don't want the machines of two different customers to directly talk
to each other. At least two of the biggest colocation providers in Germany
(1&1 and Strato) do it that way. NetworkManager supports this kind of setup
and the dhclient-scripts of several distributions too.
In this patch I have implemented a simple approach very similar to what is
found in Debian. The dhclient-script from Fedora uses a more sophisticated
approach, but that relies on the ipcalc utility which would introduce a
dependency on Fedora-initscripts for dracut. …

Add support for ethernet point-to-point connections configured via DHCP

---

modules.d/91crypt-loop/module-setup.sh

When the 'loop' kernel module isn't loaded in a running system, it gets
excluded from the hostonly initrd.  Given that the crypt-loop dracut
module has to be included explicitly anyway, it makes sense to always
include the requisite loop kernel module.

crypt-loop: Always include 'loop' kernel module

---

dracut.sh

There is a bug that kdump-initrd contains entry requesting nfs dump
filesystem to get filesystemchecked. And there is an erro message said
that nfs need be checked. But there's no fsck for nfs utility, e.g
fsck.nfs like other file system. Whatever fs_passno 0 or 2 are passed,
no fsck is executed at all for nfs mount.But in dracut, set it to be 2
always, so the erro message appear and it should be set to 0.
In the fstab,the sixth variable fs_passno stands for that the device need
checked or not,and dracut set it to "2".To fix this issue, it should
be "0" when the device is nfs.The third variable stands for the type of
the filesystem and we can use it to judge whether the device is nfs.
So when the third variable of fstab contains "nfs", the sixth variable
fs_passno should be set to "0". …

Change the fs_passno of nfs to 0

---

dracut.sh

Test that /lib is not a symlink, before using split-usr paths.

Fix default udev & systemd dir detection, in usr-merge configurations.

---

modules.d/90multipath/module-setup.sh

For large machine, suppose there's a lot of multipath devices, multipath layer
will use a lot of memory. For kdump kernel memory is very limited thus it causes
oom. To avoid oom, we only add necessary multipath devices in kdump kernel
multipath.conf.
This is done by use mpathconf --allow, a new option which is like whitelist.
Signed-off-by: Dave Young <dyoung@redhat.com>

90multipath: add hostonly multipath.conf in case hostonly mode

---

modules.d/40network/net-lib.sh

Only place this function is currently called seems from line 28 in modules.d/95nfs/nfs-lib.sh. Potential bug fix.

40network/net-lib.sh: get_ip() Add missing echo to output the result

---

modules.d/40network/net-lib.sh

Some hosting providers need a static route set in order to be
able to reach the default gateway. Be sure to retry adding
the default gateway after setting the static routes.

The default gateway might need a static route

---

dracut-initramfs-restore.sh

Script enables errexit option (set -e). So if /boot is not a mount point
or is already mounted, then script dies after unsuccessful mount
command. Fix this by always returning successful result.

dracut-initramfs-restore: make mount error nonfatal

---

.dir-locals.el

Emacs has a whitelist of "safe" variables, using `setq` overrides
that and causes it to warn when opening any file by default.
Dropping the `setq` makes Emacs do the right thing.

dir-locals: Avoid use of setq which triggers Emacs warning

---

modules.d/90dmsquash-live/dmsquash-live-root.sh

With kernel 4.3, we can take advantage of the Persistence with Overflow snapshot store type.
https://git.kernel.org/cgit/linux/kernel/git/device-mapper/linux-dm.git/commit/?h=dm-4.3&id=b0d3cc011e532d8c9db76cf717bcafa53c135595

dmsquash-live-root: Request overflow support for persistent snapshot.

---

modules.d/90dmsquash-live/dmsquash-live-root.sh

Transient snapshots can take advantage of smaller,
non-persistent metadata structures.
Make the --readonly option explicit rather than inferred
for the readonly_overlay target.
Assure that the live-base target is on the BASE_LOOPDEV.

dmsquash-live-root: Use non-persistent metadata snapshots.

---

lsinitrd.sh

On systemd, SIGPIPE is ignored by default; see man 5 systemd.exec for
IgnoreSIGPIPE=. As a result, lsinitrd.sh under a systemd service
outputs "cat: write error: Broken pipe" in the processing of
determining a compression format of a given initramfs file using cat
command in the write part of a pipeline processing.
For example, this is a log message of kdump.service in RHEL7.1,
-- Logs begin at Wed 2015-11-04 09:57:33 JST, end at Wed 2015-11-04 09:58:28 JST. --
Nov 04 09:57:33 localhost systemd[1]: Stopping Crash recovery kernel arming...
Nov 04 09:57:33 localhost kdumpctl[22545]: kexec: unloaded kdump kernel
Nov 04 09:57:33 localhost kdumpctl[22545]: Stopping kdump: [OK]
Nov 04 09:57:33 localhost systemd[1]: Starting Crash recovery kernel arming...
Nov 04 09:57:36 localhost …

lsinitrd: Suppress "cat: write error: Broken pipe"

---

modules.d/90qemu/module-setup.sh

Without this module following scenario does not work:
1. Install the guest with virtio-scsi-pci as system disk and no other
data disk.
2. Change the system disk from virtio-scsi to spapr-vscsi.

90qemu: also add ibmvscsi on qemu

---

dracut.sh

If the directory where the .img file is saved has no enough space, or in
other wrong conditions, dracut will get an incomplete file xxx.img. But
sometimes this .img file will be loaded when rebooting the system. And then
some bugs will happen because this .img file is wrong.
So I think dracut should remove the incomplete file because this .img file
with problems was made by dracut. And then the wrong file will not be loaded
anymore.
Signed-off-by: Chao Fan <cfan@redhat.com>

remove the incomplete .img file

---

modules.d/90livenet/livenet-generator.sh
modules.d/90livenet/module-setup.sh

Resolves issues where systemd attempts to boot a live URL as an NFS mount.
This patch uses systemd's generator arg[2] to generate an early sysroot.mount
that preempts systemd-fstab-generator.
See https://bugzilla.redhat.com/show_bug.cgi?id=1280103

livenet: add livenet-generator

---

dracut.cmdline.7.asc

Add descriptions for the rd.live.overlay.readonly,
rd.live.overlay.size, rd.live.overlay.reset,
rd.live.squashimg, and rd.live.overlay=none options.
Mention the Invalid mark on exhausted overlays.
Clarify the rd.writable.fsimg option.
Repunctuate the rd.live.overlay.thin option description.

dracut.cmdline:  Update Booting live images section

---

modules.d/90dmsquash-live/dmsquash-live-root.sh

dmsquash-live-root: Use non-persistent metadata snapshots for transient overlays.
Temporary snapshots can take advantage of smaller, non-persistent metadata structures.
Make the --readonly option explicit rather than inferred for the readonly_overlay target.
Assure that the live-base target is on the BASE_LOOPDEV.

dmsquash-live-root:  Persistence without overlay for uncompressed live installations

---

modules.d/99base/dracut-lib.sh

crypt/parse-crypt.sh generate initqueue job which always call
dev_unit_name() with an argument beginning with "-". This results
in the following error:
dracut-initqueue[307]: + systemd-escape -p -cfb4aa43-2f02-4c6b-a313-60ea99288087
dracut-initqueue[307]: systemd-escape: invalid option -- 'c'

base/dracut-lib.sh:dev_unit_name() guard against $dev beginning with "-"

---

modules.d/90multipath/module-setup.sh

* Multipath device names only start with the mpath-prefix if the option `user_friendly_names` is set true in `/etc/multipath.conf` and if the user has not set any aliases in the said file. Thus the for-loop should go through all files in `/dev/mapper/`, not just ones starting with 'mpath'
* Bash is perfectly capable to extend `/dev/mapper/*` notation without a need to pass it to an external ls command
* Changed the function to use a local variable $_dev instead of the global $dev, which seemed to be the original intention as the local _dev was defined but not used

multipath: fix majmin_to_mpath_dev()

---

modules.d/98dracut-systemd/dracut-cmdline-ask.service
modules.d/98dracut-systemd/dracut-cmdline-ask.sh

How to reproduce:
```
host# dracut --kernel-cmdline='rd.cmdline=ask' initramfs.img
host# qemu-system-x86_64 -initrd initramfs.img ... -append root=/dev/sda1 ...
...
qemu-host# journalctl -b | grep dracut-cmdline-ask
...
Feb 15 08:45:36 localhost systemd[1]: dracut-cmdline-ask.service: Installed new job dracut-cmdline-ask.service/start as 42
Feb 15 08:45:36 localhost systemd[1]: dracut-cmdline-ask.service: ConditionKernelCommandLine=rd.cmdline=ask failed.
Feb 15 08:45:36 localhost systemd[1]: dracut-cmdline-ask.service: Starting requested but condition failed. Not starting unit.
Feb 15 08:45:36 localhost systemd[1]: dracut-cmdline-ask.service: Job dracut-cmdline-ask.service/start finished, result=done
...
```

dracut-systemd/dracut-cmdline-ask: fix dracut --kernel-cmdline=rd.cmdline=ask

---

modules.d/99base/init.sh

How to reproduce:
```
host# ./dracut.sh -o 'dracut-systemd systemd systemd-initrd' --local -f ./initramfs.img
host# qemu-system-x86_64 -initrd ./initramfs.img \
-append 'root=/dev/sda1 rd.cmdline=ask rd.hostonly=0' \
...
Enter additional kernel command line parameter (end with ctrl-d or .)
> rd.break
> .
...
There is no "Break before switch_root"
...
```

base/init.sh: don't remove 99-cmdline-ask on 'hostonly' cleanup

---

modules.d/04watchdog/module-setup.sh

On behalf of  Pratyush Anand
Changes since V4:
-- Renamed 04watchdog.conf to 00watchdog.conf
Changes since V3:
-- Incorporated changes suggested by Harald for V2 patches
Changes since V2:
-- Added one more patch to update rd.driver.pre with watchdog module name,
so that they are loaded into kernel as early as possible.
-- Removed creation of tmp/active-watchdogs. modinfo will be helpful for
kexec-tools.
-- Now we add modules for active watchdog in hostonly mode and modules for
all watchdog in no-hostonly mode.
Changes since RFC:
-- Added one more patch to take care that dracut does not add watchdog
hooks when systemd module is included. In that case systemd daemon will
manage watchdog for kicking.
-- Removed --nowdt argument. User can use -o or --omit when wathdog module
is not needed. …

 Install kernel module for active watchdog

---

modules.d/99base/module-setup.sh

```
/usr/lib/dracut/modules.d/99base/module-setup.sh: line 15: 
/var/tmp/dracut.vkZlVJ/initramfs/usr/lib/initrd-release: No such file or directory
ln: failed to create symbolic link 
'/var/tmp/dracut.vkZlVJ/initramfs/usr/lib/os-release': No such file or directory
```
example of full output:
http://lists.pld-linux.org/mailman/pipermail/pld-devel-en/2016-April/024854.html

ensure parent dir for /usr/lib/initrd-release exists

---

modules.d/00systemd/module-setup.sh

If journald.conf already contains Storage=persistent, journald will
write to /var/log/journal/, which ends up at /run/initramfs/log/journal/
after switching root. We want to make sure early boot logs are written
to /run/log/journal/ so they can be flushed to /var/log/journal/ after
switching root.

systemd: ensure journal is volatile

---

modules.d/00systemd/module-setup.sh

This simply installs `/etc/systemd/journal.conf.d/*.conf` and `/etc/systemd/system.conf.d/*.conf` in host-only mode.

systemd: install missing drop-in configs

---

modules.d/04watchdog/module-setup.sh

These patches are necessary in order to enable kexec-tools to recognize change in active watchdog states.
Patches have been cherry-picked from mainline's master branch [1] without any conflict.
[1] git://git.kernel.org/pub/scm/boot/dracut/dracut.git:master

RHEL7: Install module for active watchdog

---

modules.d/90livenet/livenet-generator.sh

This is a further improvement on PR #105 which re-adds support for nfs:// urls to root=live:nfs://... Symptoms prior to applying this patch are that sysroot.mount times out when following the nfs:// syntax for the path to the live image. An additional case is added to livenet-generator to support the nfs protocol.

livenet: support nfs:// urls in livenet-generator

---

modules.d/90qemu/module-setup.sh

This adds support for /sys/firmware/qemu_fw_cfg on QEMU guests started with the -fw_cfg option.

qemu: include the qemu_fw_cfg kernel module

---

modules.d/98integrity/ima-policy-load.sh

IMA validates file signatures based on the security.ima xattr. As of
Linux-4.7, instead of cat'ing the IMA policy into the securityfs policy,
the IMA policy pathname can be written, allowing the IMA policy file
signature to be validated.
This patch first attempts to write the pathname, but on failure falls
back to cat'ing the IMA policy contents .
Signed-off-by: Stefan Berger <stefanb@linux.vnet.ibm.com>
Signed-off-by: Mimi Zohar <zohar@linux.vnet.ibm.com>

98integrity: support validating the IMA policy file signature

---

51-dracut-rescue.install

If ESP is mounted on /boot/efi, which is Fedora's default I think, 51-dracut-rescue.install fails to create ${MACHINE_ID}-0-rescue.conf. This PR fixes the problem by using the proper mounted point of ESP.

rescue: use proper path for 0-rescue.conf

---

modules.d/90kernel-network-modules/module-setup.sh

This makes dracut boot from NFS in a xen instance.
bnc#896464, bnc#896259
Signed-off-by: Thomas Renninger <trenn@suse.de>

network: Try to load xennet

---

install/dracut-install.c

Preserve extended attributes when copying files using dracut-install.
The copying of extended attributes avoids file execution denials when
the Linux Integrity Measurement's Appraisal mode is active. In that mode
executables need their file signatures copied. In particular, this patch
solves the problem that dependent libaries are not included in the
initramfs since the copied programs could not be executed due to missing
signatures. The following audit record shows the type of failure that
is now prevented:
type=INTEGRITY_DATA msg=audit(1477409025.492:30065): pid=922 uid=0
auid=4294967295 ses=4294967295
subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
op="appraise_data" cause="IMA-signature-required"
comm="ld-linux-x86-64" …

dracut-install: preserve extended attributes when copying files

---

modules.d/95ssh-client/module-setup.sh

Bug related to this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1360131
Now dracut only attempts to copy GlobalKnownHostsFile while generating kdump's
initramfs. This method will cause kdump's failure if users set customized
UserKnownHostsFile in /etc/ssh/ssh_config. This patch simply attempts to copy
those files too while going through /etc/ssh/ssh_config. Note that we need to
make sure ~/foo will be copied as /root/foo in kdump's initramfs.

95ssh-client: attempt to copy UserKnownHostsFile to kdump's initramfs

---

dracut.cmdline.7.asc
modules.d/98dracut-systemd/dracut-cmdline.sh
modules.d/98dracut-systemd/dracut-pre-mount.sh
modules.d/98dracut-systemd/dracut-pre-pivot.sh
modules.d/98dracut-systemd/dracut-pre-trigger.sh
modules.d/99base/dracut-lib.sh
modules.d/99base/init.sh
modules.d/99base/memtrace-ko.sh
modules.d/99base/module-setup.sh
test/TEST-01-BASIC/test.sh

1. Add memtrace-ko.sh to debug kernel module large memory consumption, installed as an
executable named "tracekomem".
2. Extend "rd.memdebug" to "4", and "make_trace_mem" to "4+:komem".
3. Update the dracut.cmdline manpage.
4. Add test for rd.memdebug.

Introduce "rd.memdebug=4" to test kernel module memory consumption

---

dracut.sh

Dracut changes working directory before attempting to output files under
$DRACUT_TMPDIR , resulting in an IO failure if $DRACUT_TMPDIR is a path
relative to the working directory when dracut was started.
Fixes: https://github.com/dracutdevs/dracut/issues/156
Signed-off-by: David Disseldorp ddiss@suse.de

dracut.sh: support --tmpdir as a relative path

---

modules.d/90kernel-modules/module-setup.sh

Add some extra kernel modules for ARM generic host initrd generation to ensure we have all modules to install/boot on ARM SBCs and related platforms.

Some fixes for ARM hardware generic host initrd generation

---

dracut-init.sh

The variable is called "_silent", not "silent". Just stumbled over this by accident.

dracut-init.sh: fix typo

---

modules.d/45ifcfg/write-ifcfg.sh

If MTU is specified, we write it for every type of device in the
beginning. There is not point writing it again for Type=ethernet
devices.

write-ifcfg: do't write MTU twice for regular eth devices

---

modules.d/40network/ifup.sh

Commit cf376023e6d0d4abd9816fa954bb917fc2557713 moved writing .resolv.conf and .override
after dhcp_do, because dhcp_do was overwriting .resolv.conf. But .override does not have
such problem and on the contrary dhcp_do reads .override file if it is present. So let's
move it back.
https://bugzilla.redhat.com/show_bug.cgi?id=1415004

network/ifup: write override file before dhcp_do

---

modules.d/50drm/module-setup.sh
modules.d/90kernel-modules/module-setup.sh

These add aarch64 to the modules where we specify ARM specifics as well as we need the same extras on the vast majority of aarch64 platforms too
Signed-off-by: Peter Robinson <pbrobinson@gmail.com>

Aarch64 fixes

---

mkinitrd-suse.8.asc

For example under x86, someone maybe missunderstand that the vmlinuz
is the link /boot/vmlinuz points to a specific kernel image and use
the following command directly.
mkinitrd -k vmlinuz

man: make the -k option clear using mkinitrd

---

modules.d/95cifs/module-setup.sh

Some crashkernel targets still use legacy NTLM auth, which
require those (bsc#869496). This patch enumerates all dependent
hash algorithems, because even though most of them are probably
compiled in, older ones (e.g. md4 and arc4) usually aren't.

Add md4 and arc4 modules for ntlm

---

dracut.cmdline.7.asc
modules.d/90dm/dm-shutdown.sh
modules.d/90dmsquash-live/apply-live-updates.sh
modules.d/90dmsquash-live/dmsquash-generator.sh
modules.d/90dmsquash-live/dmsquash-live-root.sh
modules.d/90dmsquash-live/module-setup.sh
modules.d/90dmsquash-live/parse-dmsquash-live.sh

Integrate the option to use an OverlayFS as the root filesystem
into the 90dmsquash-live module for testing purposes.
The rd.live.overlay.overlayfs option allows one to request an
OverlayFS overlay.  If a persistent overlay is detected at the
standard LiveOS path, the overlay & type detected will be used.
Tested primarily with transient in-RAM overlay boots on vfat-
formatted Live USB devices, with persistent overlay directories
on ext4-formatted Live USB devices, and with embedded, persistent
overlay directories on vfat-formatted devices. (Persistent overlay
directories on a vfat-formatted device must be in an embedded
filesystem that supports the creation of trusted.\* extended attributes,
and must provide valid d_type in readdir responses.)
The rd.live.overlay.readonly option, which …

Enable the use of the OverlayFS for the LiveOS root filesystem.

---

modules.d/90kernel-modules/module-setup.sh

Contrary to previous intel pinctrl drivers, the cherryview driver can be
and usually is built as a module. However, it sets up the SDIO pinout
so sdhci can make use of the SD card reader, which may subsequently
hold a root file system on a card  (bsc#998440).

Always try to add pinctrl-cherryview

---

modules.d/90kernel-modules/module-setup.sh

The phy and power modules are needed by some of the recent ARM
devices that have appeared like CHIP and some exynos devices.
Signed-off-by: Peter Robinson pbrobinson@gmail.com

modules: kernel: add phy and power modules to generic initrd

---

modules.d/10i18n/module-setup.sh

For MAP=lt, dracut would choose lt.std.map instead of lt.map.
Signed-off-by: Fabian Vogt fvogt@suse.com

Fix wrong keymap inclusion

---

modules.d/00systemd/module-setup.sh

Both 'utmp' and 'root' groups are mentioned in tmpfiles.d/systemd.conf
and as such should be included.
It's probably better to have something equiv to inst_rule_group_owner()
for udev rules which parses out users and groups and adds them to the
passwd/group db respectively.
Could also rely on sysusers but as the initramfs is static in this
sense, it's more efficient to pre-define the users IMO.

systemd: add more groups to deal with tmpfiles handling.

---

modules.d/90crypt/crypt-lib.sh
modules.d/90crypt/parse-keydev.sh

To have a self-contained, signed kernel ready for SecureBoot I need to be able to embed a keyfile (which is GnuPG encrypted, of course) into the initramfs. I'm not sure if this is the best way, but it seemed to be the simplest:
If the kernel commandline contains a luks key option `rd.luks.key=keypath:keydev:luksdev`, then keydev can now be the single character `/`, which signals dracut that instead of probing for the keypath it shall assume that the keypath resides inside the initramfs itself (e.g. added via `install_items+="keypath"` in dracut's configuration file).

crypt: Support keyfiles embedded in the initramfs

---

Makefile

it seems `rpmbuild` result RPMs are not put inside a `$$(arch)` subdirectory. so the `mv` command that is supposed to move the RPMs into `$(DESTDIR)` is failing. getting rid of arch fixes the problem.

remove $$arch() from rpm target in Makefile

---

modules.d/90dmsquash-live/dmsquash-live-root.sh

The newer mount utilities are more strict about directly shared
devices. For OverlayFS boots, which mount $BASE_LOOPDEV directly,
avoid a mount error by indirectly sharing the read-only base
filesystem through a second, over-attached $BASE_LOOPDEV for
the DM live-base target.
(Tested on Fedora 26 Alpha.)

dmsquash-live-root: Avoid mount source conflict on $BASE_LOOPDEV.

---

modules.d/40network/ifup.sh
modules.d/40network/net-lib.sh

As per title, you need to wait for default route to be set, this is needed before downloading Anaconda's `squashfs.img` when installing from the network.
Here I am adding the same logic we have in wait_for_ipv6_auto into the other two functions (`wait_for_ipv6_dad`, `wait_for_ipv6_dad_link`).
Also enabling RA acceptance in the `do_static` function...

Look for IPv6 RA in wait_for_ipv6_dad, wait_for_ipv6_dad_link and wait_for_ipv6_auto

---

modules.d/91crypt-gpg/README
modules.d/91crypt-gpg/crypt-gpg-lib.sh
modules.d/91crypt-gpg/module-setup.sh

crypt-gpg: For GnuPG >= 2.1 support gpg keyfile decryption via a OpenPGP smartcard in a CCID reader

---

Makefile

This prevents to fail build when your distro have own CFLAGS env already
@haraldh Please merge
+ CC=/usr/bin/clang
+ export CC
+ CXX=/usr/bin/clang++
+ export CXX
+ CFLAGS='-Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fstack-protector-all -fPIC -flto -fPIE'
+ export CFLAGS
+ CXXFLAGS='-Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fstack-protector-all -fPIC -flto -fPIE'
+ export CXXFLAGS
+ FFLAGS='-Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fstack-protector-all -fPIC -flto'
+ export FFLAGS
+ LDFLAGS='-Os -gdwarf-4 …

fix build with KMOD

---

mkinitrd-suse.sh

The previous algorithm was incorrect and would return
incorrect results e.g. for a /20 mask. Also gets rid
of an undocumented depencency on bc(1).
Reference: bsc#1035743

mkinitrd-suse.sh: Fix prefix calculation

---

modules.d/45url-lib/module-setup.sh

curl in Fedora recently changed its default CA trust store. The
Fedora package no longer specifies an OpenSSL-format bundle file
during build, and curl itself has been patched to use an NSS
plugin called libnssckbi when no bundle file or directory is
specified. This appears to use a trust bundle in p11-kit format
stored in /usr/share/pki/ca-trust-source .
Unfortunately neither libcurl.so nor libnssckbi.so includes a
string specifying the exact trust store filename, as is the case
for the old approach (which dracut takes advantage of to find
the file). libnssckbi.so contains a string that seems to list the
*directories* it will look for a trust bundle in, but not the
filenames it will look for (I think it will actually use any file
of an appropriate format in the specified dirs, but not …

Handle curl using libnssckbi for TLS (RHBZ #1447777)

---

modules.d/50drm/module-setup.sh

At least on x86 on Bay and Cherry Trail devices the pmw-lpss modules must
be in the initrd too, otherwise the i915 driver will still load, but
it will report the following error:
[drm:pwm_setup_backlight [i915]] *ERROR* Failed to own the pwm chip
And not register /sys/class/backlight/intel_backlight and users will
not be able to control their backlight.
Signed-off-by: Hans de Goede <hdegoede@redhat.com>

drm: Install pwm modules on all architectures

---

modules.d/00systemd/module-setup.sh

... because otherwise nothing will actually
apply configuration from tmpfiles snippets

systemd: include systemd-tmpfiles-setup.service

---

modules.d/95udev-rules/module-setup.sh

Cpu hotplug policy was split off to separate file. Let's pull in the new
rules file by default.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1266322
Resolves: #1460707

udev-rules: pull in 40-redhat-cpu-hotplug.rules (#1460707)

---

modules.d/01fips/module-setup.sh

cmac is now marked as fips_allowed
Resolves: rhbz#1460865

fips: add cmac kernel module

---

modules.d/98dracut-systemd/dracut-pre-udev.service

This used to work only when specified via the command line
or if systemd was not being used. However, the exisistence of
20_force_driver.conf also requires dracut-pre-udev.service
to be run.
Reference: bsc#986216

98dracut-systemd: Fix module force loading with systemd

---

modules.d/40network/dhclient-script.sh

Previously our dhclient-script expected that $new_classless_static_routes
will have all values separated by a whitespace. But at least on F25
dhclient will put there the destination descriptor in the same format
as it is used by ISC dhcp-server.
For example:
new_classless_static_routes=32.10.198.122.47 192.168.78.4
while our current code expects
new_classless_static_routes=32 10 198 122 47 192 168 78 4
So let's just accept both of these formats by adding "." to IFS.
For details plesse see https://tools.ietf.org/html/rfc3442
"Classless Route Option Format"

network/dhclient-script: also parse dot separated $new_classless_static_routes

---

modules.d/90crypt/crypt-lib.sh
modules.d/90crypt/module-setup.sh

blkid is not available when this function is called, so block_uuid.map is put into
the initrd, mapping block devices from /etc/crypttab to UUIDs.
This fixes a bug where udev rules were created by mistake as crypttab_contains()
returned false for devices specified by path in /etc/crypttab which resulted in
error messages during boot.
Signed-off-by: Julian Wolf <juwolf@suse.de>

90crypt: Fixed crypttab_contains() to also work with device path in /etc/crypttab

---

modules.d/90dmsquash-live-ntfs/module-setup.sh
modules.d/90dmsquash-live/dmsquash-live-root.sh

Support booting from USB media with NTFS filesystem (optionally), which removes the FAT32 related 4 GB file size limit for LiveOS/squashfs.img (and any other file on the same USB media)
Note: I am aware that my patch is not great, but it would be awesome if you could help to make it proper.

Add NTFS support to 90dmsquash-live module

---

50-dracut.install
51-dracut-rescue.install

From systemd-234, kernel-install plugins are called even if /etc/machine-id
is missing or empty, and in that case BOOT_DIR_ABS is a fake directory.
So, let's skip to create initrd in that case.
C.f. https://github.com/systemd/systemd/commit/9d8813b3b4f69d9428e7759ed8a2956d8846b0fb.
Fixes #231.

kernel-install: Skip to create initrd if /etc/machine-id is missing or empty

---

modules.d/40network/dhclient.conf

Forcing dhclient to use hardware address (chaddr) instead of DUID to make it
predictable and allows system installation in whitelist based networks.
By default dhclient can send DUID (LL,LLT or UUID) as client-identifier and server may reject such clients.
https://www.net.princeton.edu/announcements/dhcp-cliid-must-match-chaddr.html

dhclient: send client-identifier matching hardware address

---

modules.d/90crypt/crypt-lib.sh
modules.d/91crypt-loop/crypt-loop-lib.sh

Using initqueue --finished to cleanup stuff is not what the
initqueue/finished hook was meant for.
Move stuff to the real cleanup hook.

crypt-loop: cleanup cleanup procedures

---

modules.d/90kernel-modules/module-setup.sh

A number of the newer more complex devices have some extra requirements for drivers in early boot.

A few ARM fixes for a number of newer devices which have some wider deps

---

modules.d/40network/net-genrules.sh

The dracut network module is only supposed to be used for wired interfaces
but if driver modules for wireless devices are wrongly copied, these will
be loaded and the available interfaces brought up.
If the rd.neednet=1 command line parameter is used, dhclient will attempt
to request an IP address for the interfaces and these requests will fail.
But other dracut modules that depend on the network to be settled, will
have to wait for the DHCP requests to timeout. Which can be a lot of time
since the dhclient default timeout value is 60 seconds.
Instead of trying to blacklist all possible kernel modules for wireless
devices, only bring up network interfaces if these are for wired devices.
Suggested-by: Harald Hoyer <harald@redhat.com>
Signed-off-by: Javier Martinez Canillas …

network: Only bring up wired network interfaces

---

modules.d/95ssh-client/module-setup.sh

SSH uses passwd database and thus need various NSS plugin libraries,
depending upon setting in nsswitch.conf.
SSH binary fails within the dracut environment without the libraries:
#:/ ssh
No user exist for uid 0

ssh-client: Include nss_ libraries

---

dracut.8.asc
dracut.sh
modules.d/95rootfs-block/module-setup.sh

In some cases, we do not want the default host devices like root, swap, fstab, etc.
We can use this new argument to skip those devices, and use "--mount" or "--add-device" to explicitly add the wanted devices as needed.
This is useful for kdump which only cares about its dump target.

introduce new "--no-hostonly-default-device"  argument

---

dracut.sh

Currently in Fedora/RedHat dracut installs its fedora.conf.example
as the default config file, in which sysloglvl is set 5. This leads
to maxloglvl=5 in dracut calls, making unnecessary lsinitrd calls
during initramfs builds by kdump.
This patch disables lsinitrd logging when --quiet option is given,
which is controlled by maxloglvl only before. This will speed up
dracut image building as the following if --quiet is used in kdump:
1) Before this patch
$ kdumpctl stop; touch /etc/kdump.conf; time kdumpctl start
kexec: unloaded kdump kernel
Stopping kdump: [OK]
Detected change(s) in the following file(s):
/etc/kdump.conf
Rebuilding /boot/initramfs-4.13.0-0.rc1.git4.1.fc27.x86_64kdump.img
kexec: loaded kdump kernel
Starting kdump: [OK]
real    0m26.824s
user    0m9.958s
sys     0m15.106s
2) …

dracut.sh: disable lsinitrd logging when quiet

---

modules.d/00systemd/module-setup.sh

systemd sets /proc/sys/kernel/core_pattern to use systemd-coredump.
However, systemd-coredump is missing from initrd, making dumping
the core in initrd impossible by default.

Enable core dumps with systemd from initrd

---

modules.d/90dmsquash-live/dmsquash-generator.sh
modules.d/90livenet/livenet-generator.sh
modules.d/98dracut-systemd/rootfs-generator.sh
modules.d/99base/dracut-lib.sh

JobRunningTimeoutSec now affects how long can start jobs for device
units stay in the "running" state. Disabling default job timeout via
JobTimeoutSec=0 doesn't disable running state timeout. We need to set
running state timeout as well.
Note that doing this the other way around has effect on generic timeout,
i.e. disabling running state timeout disables generic timeout. But doing
it this way we would create implicit dependency on fairly new
systemd-234. However, by setting both options we don't create dependency
on specific systemd version.

systemd: fix setting of timeouts for device units

---

modules.d/40network/ifup.sh

Prior to this commit, the MTU setting was applied to a bond slave
interface.  In older versions of the Linux kernel, this setting
propagated to the bond master and the other bond slaves associated with
the master.  In recent versions of the kernel (observed in Linux 4.12),
increasing the MTU of a slave does not automatically increase the MTU of
the master.  This allows for more flexibility but requires the MTU of
the master to be changed manually.
Ideally, the MTU setting should be applied to the bond master and the
setting will propagate to the bond slaves, since the slaves are required
to have a MTU that is greater than or equal to the bond master.

Set MTU on bond master as opposed to a bond slave

---

modules.d/90crypt/cryptroot-ask.sh
modules.d/90crypt/module-setup.sh
modules.d/90crypt/parse-crypt.sh

A LUKS root volume with a detached header on a device without partitioning will not have a UUID and will not have an attribute ENV{ID_FS_TYPE}=="crypto_LUKS".
Therefore, several areas need to be addressed: identification of the LUKS device, inclusion of entries within crypttab, and provision of the detached header file.
- Added support for an option (4th column: "force") in /etc/crypttab to force the inclusion of the entry in the initramfs version (avoiding the fs type test).
- Added support for an option (4th column: "header=/path/to/file") in /etc/crypttab to provide a path to a detached header file embedded within the initramfs.
- Added ID and PARTUUID support to the device (2nd column) in /etc/crypttab (complementing the existing UUID functionality).
- Added cmdline support to …

Add basic LUKS detached header support

---

modules.d/40network/ifup.sh

The MTU is only being set on the slave devices and the MTU of the
bonding master is not being updated. This updates the bonding master and
also changes the MTU on the slaves as expected.
Signed-Off-By: Robert LeBlanc <robert@leblancnet.us>

Fix MTU on bond interface.

---

install/dracut-install.c

kerneldirlen is used to modify absolute path returned by
kmod_module_get_path() while it is calculated on user-supplied
--kerneldir argument which can be a relative path.
Use kmod_get_dirname() to convert user-supplied path to the same format
as used by kmod_module_get_path().
This also allows to get rid of now useless strcmp checks that seem to
imply that /lib and /usr/lib are linked which is not always true.

dracut-install: fix relative paths in --kerneldir

---

dracut.sh

If we trigger crash just after creating initramfs, sometimes it is
observed that initramfs is not written to disk causing the subsequent
boot to fail. A sync should resolve this.
Signed-off-by: Ankit Kumar <ankit@linux.vnet.ibm.com>

Sync initramfs after creation

---

modules.d/90lvm/lvm_scan.sh

The --ignoreactivationskip/-K switch was added to LVM2 in 2.02.99
(July 2013) and is used to control the activation of volumes with
the activation skip flag set: without -K these volumes will be
ignored when 'lvchange -ay $LV' is issued.
This prevents an LVM2 thin-privisioned snapshot from being used
as the root device when booting with "rd.lvm.lv=vg/lv" since the
activation skip flag is set for these snapshots by default (the
legacy non-thinp snapshots do not set this flag and can already
be activated and used as a root device by specifying appropriate
values for rd.lvm.lv).
This is only used in the rd.lvm.lv case since in that situation
we are activating one or more named LVs specified by the user:
the flag is not given when calling 'vgchange' since this may
cause many unwanted volumes …

lvm_scan.sh: use -K when calling lvchange

---

modules.d/95iscsi/iscsiroot.sh

If no iscsi session information can be retrieved from the firmware
then skip the iscsi attachment and allow the boot process to continue.
Ensure the timeout scripts don't hit their timeout waiting for
/tmp/iscsistarted-firmware to be created.
This will allow a common image to be used for servers with both a
local and iscsi root with rd.iscsi.firmware set.

Skip iscsi attachment if no info

---

modules.d/90dmsquash-live/dmsquash-generator.sh

We need an actual bashslash in the filename on disk.
https://bugzilla.redhat.com/show_bug.cgi?id=1508794
Tested by doing 'systemctl cat /dev/mapper/live-rw' after rd.break.

dmsquash-generator.sh: properly escape backslash in path

---

modules.d/10i18n/module-setup.sh

Previously, dracut would only copy the first one found. However,
with legacy maps for some locales around, there is a chance we
pick the wrong one. Pick all matching keymaps instead
Reference: boo#1065058

10i18n: Load all keymaps for a given locale

---

modules.d/90multipath/module-setup.sh

Although no device uses multipath, the module checks
for presence of the multipath binary first, printing a
warning if not present. This patch fixes the wrong ordering.

Fix warning about multipath if not needed

---

dracut-functions.sh

The caller of "for_each_host_xx func" needs to tell three cases:
func success/ fail / not be called.
E.g, in kdump case, host_devs can be empty, and we want to know it.
Signed-off-by: Pingfan Liu <piliu@redhat.com>

dracut.sh: for_each_host_xx() function should indicate the empty case

---

modules.d/40network/module-setup.sh

since version 046 40network/net-lib.sh uses grep but the module does not install grep

40network: install grep

---

modules.d/00systemd/module-setup.sh

With hostonly enabled, only modules that are currently
loaded are included in the initrd. Modules which are
explicitly listed in modules-load.d do not need to
be filtered that way. Fix for boo#962224.

Fix loading of modules in modules-load.d

---

modules.d/95nfs/module-setup.sh

Patch-By: Thomas Renninger <trenn@suse.de>

Do not pass ifname for bonding devices (bsc#995812)

---

modules.d/95fcoe-uefi/module-setup.sh

References: boo#965477
fcoe-uefi gets included by default on EFI systems,
as it does not do the same check that fcoe does,
therefore needlessly pulling in network modules.
This patch copies the check from fcoe to fcoe-uefi.

fcoe-uefi: Add check for usage

---

modules.d/98dracut-systemd/dracut-emergency.service

Certain rescue/recovery operations, e.g. xfs_repair need
that liberty (bsc#1019938).

Set TaskMax=inifinite for the emergency shell

---

modules.d/90dmraid/61-dmraid-imsm.rules

There is no point trying to delete partitions; dmraid works
happily even with them. On the contrary trying to delete partitions
can even be harmful when eg dmraid should _not_ be started.
References: bsc#998860
Signed-off-by: Hannes Reinecke <hare@suse.com>

90dmraid: do not delete partitions

---

modules.d/95dasd_mod/parse-dasd-mod.sh

We're now parsing the 'rd.dasd' parameter from 95dasd_rules, so
setting the 'dasd_mod' module parameter should be dropped here.

95dasd_mod: do not set module parameters if dasd_cio_free is not present

---

modules.d/99fs-lib/fs-lib.sh

The needle argument in this specific case is a pattern, which cannot be
matched by the "literal" string matcher strstr.
This can result in fsck calls like:
e2fsck -a -y /dev/sda1
Which will then exit with an error like:
e2fsck: Only one of the options -p/-a, -n or -y may be specified.
Hence, it is necessary to use the strglobin function to correctly match
the pattern.

Use pattern matching function

---

modules.d/01fips/fips.sh

Old code did not work for two most common use-cases.
On most machines BOOT_IMAGE is set to something like
/vmlinuz-4.11.3-202.fc25.x86_64. So if we just add prefix "/boot/."
it won't work. Also on machines without /boot on separate partition
BOOT_IMAGE already has the /boot/ prefix (/boot/vmlinuz-3.10.0-799.el7.x86_64).
So let's strip it in such case.
https://bugzilla.redhat.com/show_bug.cgi?id=1415032

01fips: Fix creating path to .hmac of kernel based on BOOT_IMAGE

---

dracut.sh

- Caused by add_drivers+=" " in dracut.conf (bsc#923116)
Signed-off-by: Fabian Vogt <fvogt@suse.com>

Fix possible hang in dracut

---

modules.d/95lunmask/fc_transport_scan_lun.sh
modules.d/95lunmask/module-setup.sh
modules.d/95lunmask/parse-lunmask.sh
modules.d/95lunmask/sas_transport_scan_lun.sh

Using the module option 'scsi_mod.scan=manual' this implements LUN masking by
selectively enable only those devices required for booting.
References: bsc#954600,FATE#319786

95lunmask: Add module to handle LUN masking

---

dracut.sh

If /boot is a journaling file system, the only guarantee after sync(1) is that data has been written to the disk media, but not metadata.
It is necessary to either umount the filesystem or call fsfreeze(8) for metadata to be written to stable disk media (elsewhere than the journal).
As grub2 does not know how to handle a journaled filesystem, e316ae0e4309726b2c067a70ac41f7b22011c063 alone does not ensure consistency.
Note that I explicitly avoided using fsfreeze(8) if /boot and / belong to the same file system - I think this would be wrong for many reasons.
This is related to https://github.com/rhboot/grubby/pull/28 and part of an on-going effort to fix https://bugzilla.redhat.com/show_bug.cgi?id=1227736 .

call fsfreeze(8) on /boot to flush initramfs data & metadata to media

---

mkinitrd-suse.sh

- Without this patch, -A sets host_only=0,
but host_only wasn't used
- Translates into --no-host-only now

mkinitrd-suse.sh: Implement functionality of -A option

---

modules.d/90multipath/module-setup.sh
modules.d/90multipath/multipath-shutdown.sh
modules.d/90multipath/multipathd-needshutdown.sh
modules.d/90multipath/multipathd.service

Amongst others, this adds support for legacy commandline
options multipath=off. I'd like to maintain this upstream.
If not acceptable, I'll drop this one off the stack and keep it a distro patch.

SUSE fixes for 90multipath

---

modules.d/01fips/fips.sh

8f5c5 broke the case where BOOT_IMAGE is not set at all.
This code should handle following:
1) BOOT_IMAGE not set
2) BOOT_IMAGE set to something unrelated (s390)
3) BOOT_IMAGE=vmlinuz-4.14.7-300.fc27.x86_64
4) BOOT_IMAGE=/vmlinuz-4.14.7-300.fc27.x86_64
5) BOOT_IMAGE=/boot/vmlinuz-4.14.7-300.fc27.x86_64
6) BOOT_IMAGE=subdir/vmlinuz-4.14.7-300.fc27.x86_64
7) BOOT_IMAGE=/subdir/vmlinuz-4.14.7-300.fc27.x86_64
8) BOOT_IMAGE=/boot/subdir/vmlinuz-4.14.7-300.fc27.x86_64
https://bugzilla.redhat.com/show_bug.cgi?id=1415032

01fips: Properly creating path to .hmac of kernel based on BOOT_IMAGE

---

dracut.sh

- dracut replaced every instance of "-i" in the cmdline,
even if it was part of a kernel image name, e.g. "vmlinuz-i"
- Fixes boo#908452
Signed-off-by: Fabian Vogt <fvogt@suse.com>

Fix parsing of "-i" and "--include"

---

dracut-init.sh
modules.d/98dracut-systemd/dracut-emergency.sh

Allow filesystem modules to install a fs-specific text file with instructions
on what to do when mount fails. This is printed when we go into an emergency
shell.
Signed-off-by: Mark Fasheh <mfasheh@suse.de>

dracut-emergency: optionally print fs help

---

dracut.spec

Follow-up for 68cbbae33adc65452ee234940f668151f65cc043.

spec: use if-undefined instead of empty if-defined block

---

dracut.sh

When the system boots with EFI, then initrd image is stored on EFI System Partition. Thus dracut always warn about the failure to invoke `fsfreeze` on the partition.
This prevents to run `fsfreeze` on ESP and suppress the warning.

dracut.sh: do not invoke fsfreeze on EFI System Partition

---

modules.d/95dcssblk/module-setup.sh
modules.d/95dcssblk/parse-dcssblk.sh

Add s390 dcssblk driver and introduce rd.dcssblk= to pass mounts
that should get activated at initrd stage.
References: FATE#308263

95dcssblk: Add new module for DCSS block devices

---

modules.d/90dmsquash-live-ntfs/module-setup.sh

Dependencies should not include module number.

90dmsquash-live-ntfs: fix depends()

---

dracut.cmdline.7.asc
dracut.sh
modules.d/91zipl/install_zipl_cmdline.sh
modules.d/91zipl/module-setup.sh
modules.d/91zipl/parse-zipl.sh

The s390 zipl bootloader is not capable of reading from certain
more advanced filesystems such as btrfs. We therefore need an indirect
chaining process to boot systems like SLES. This works by letting ZIPL
boot a kernel from an ext partition, which loads a dracut-generated initrd
containing an ELF-based GRUB. This grub then loads the effective kernel
and userland via kexec.

Add 91zipl, which adds support for indirect booting on s390.

---

dracut.cmdline.7.asc
modules.d/81cio_ignore/module-setup.sh
modules.d/81cio_ignore/parse-cio_accept.sh

References: bnc#874902
Incorporates following on-top patches/fixes:
----------------------------
Subject: 81cio_ignore: skip module if cio_ignore is not active
When cio_ignore is not active we should skip the entire module
during boot; otherwise it'll lead to adverse effects.
References: bnc#882685
----------------------------
Subject: 81cio_ignore: rewrite module
Rewrite cio_ignore module to rely on the dracut commandline
parameter 'rd.cio_accept', which takes a comma-separated list
of CCW IDs. Each of those IDs are being removed from the
list of devices from cio_ignore.
The default values for rd.cio_accept are taken from
/boot/zipl/active_devices.txt.
References: bnc#882685
-----------------------------
Subject: More empty cmdline fixes
This fixes up some more modules which might print …

81cio_ignore: handle cio_ignore commandline

---

AUTHORS
dracut.spec

Follow-up for b925f7f5d97259dd81e9d562fd1c6433e4b04f30.

spec: remove 81cio_ignore module from non-s390 arch

---

modules.d/90multipath/module-setup.sh

As the 'multipath' program will be triggered directly from
udev events it will be called before the multipath service
unit has started up. Which means we cannot rely on the
service unit to load the module for us, but we rather
have to do it early before udev is started.
References: bsc#986734
Signed-off-by: Hannes Reinecke <hare@suse.com>

90multipath: load dm_multipath module during startup

---

modules.d/90dmraid/dmraid.sh
modules.d/90dmraid/module-setup.sh

Use udev rules to create dmraid /dev/mapper/ devices
https://bugzilla.opensuse.org/show_bug.cgi?id=905746

0202-dracut_dmraid_use_udev

---

modules.d/50drm/module-setup.sh

The recently upstreamed virtualbox video driver (vboxvideo) is shipped
in the staging directory. We need to probe it before Xorg is loaded to
avoid a corrupted X.
In general it is a good practice to look also in the staging directory
for DRM drivers.
Signed-off-by: Carlo Caione <carlo@endlessm.com>

drm: Look for DRM drivers in the staging directory

---

dracut-functions.sh

There is currently no way to override dracut's preference for
/dev/mapper device names. But using these is problematic in
different scenarios: For example, if a user has a multipath-
enabled system but wants to disable multipath, or if the
names of multipath maps change because of configuration changes
(e.g. toggling user_friendly_names in /etc/multipath.conf).
This patch makes dracut prefer the user-specified
--persistent_policy names over /dev/mapper names.
It might be worthwhile to discuss why dracut prefers /dev/mapper
of /dev/disk/by-uuid at all. This preference was introduced
in 9037b63e with the argument "dm devices maintain /dev/mapper/* as
persistent names", but that's wrong for the scenarios mentioned
above, and is not a compelling reason for preferring /dev/mapper
over …

Give --persistent_policy precedence over /dev/mapper names

---

modules.d/90multipath/multipathd.service

Don't fail if modprobe fails to load a module, the kernel could have it
statically compiled in.
Signed-off-by: Matthew Thode <mthode@mthode.org>

support kernels with built-in modules

---

modules.d/50plymouth/module-setup.sh
modules.d/50plymouth/plymouth-populate-initrd.sh

The existence of dpkg-achitecture is not indicative of a debian
installation. It may well be installed on systems of people who
package for both distros. The previous code path did not take
that into account.
We now traverse all known plymouth directories, locking on the first
existing one, and try to work with it.
At the same time, we do not include the module if the plymouth directory
could not be found.
This obsoletes 0300-dracut_dont_use_dpkg_defaults_on_SUSE.patch.
Also: 90plymouth: logo file is optional and may not exist

50plymouth: improve distro compatibility

---

modules.d/40network/net-genrules.sh

If no network related params are specific, but rd.neednet=1 is set,
the default initqueue action is to wait until one of the network
interfaces is marked as setup properly.
This also help with initqueue's race condition when the network interface
shows up late
References: bnc#866771

40network: Fix race condition when wait for networks

---

modules.d/90crypt/crypt-lib.sh
modules.d/90crypt/module-setup.sh

Also change path to /etc/block_uuid.map.
Fixes: c3b6970394ad677f05a42bef420bf34b1d0652e0
I hope /etc/block_uuid.map will not clash with any standard config files.

crypt: actually put block_uuid.map into initramfs

---

modules.d/99base/dracut-lib.sh

It seems that on systems using _systemd_ in the initrd emergency hooks are executed twice, which is probably not the desired behavior.
* Create directory _/usr/lib/dracut/modules.d/50emergency-test_
* Add the file _module-setup.sh_ with the following contents:
```
#!/bin/sh
install () {
inst_hook emergency 50 "$moddir"/emergency-test.sh
inst date
}
```
* Add the file _emergency-test.sh_ with the following contents:
```
#!/bin/sh
warn "`date +%s%N`"
warn "$0"
```
* Rebuild initrd
* Reboot and add `rd.break` as a kernel boot parameter
* You can see the date **twice** with **different** timestamps and a different parent: Once on the command line and once in the output of _/run/initramfs/rdsosreport.txt_.
It seems that emergency hooks are executed twice if the initrd is using systemd: First …

Avoid executing emergency hooks twice

---

50-dracut.install
51-dracut-rescue.install

The GRUB 2 bootloaders expect the initrd to be installed in /boot instead
of /boot/$MACHINE_ID/$KERNEL_VERSION/{linux,initrd}, so if that directory
doesn't exists, install the initramfs images on the /boot directory.
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>

5?-dracut*.install: Allow scripts to install the initramfs in /boot dir

---

dracut-init.sh
modules.d/90crypt/crypt-lib.sh
modules.d/98syslog/parse-syslog-opts.sh

Error: SHELLCHECK_WARNING:
/usr/lib/dracut/dracut-init.sh:939:20: error: Argument to implicit -n is always true due to literal strings. [SC2157]
937|   dracut_kernel_post() {
938|       for _f in modules.builtin.bin modules.builtin modules.order; do
939|->         [[ $srcmods/$_f ]] && inst_simple "$srcmods/$_f" "/lib/modules/$kernel/$_f"
940|       done
941|
Error: SHELLCHECK_WARNING:
/usr/lib/dracut/modules.d/98syslog/parse-syslog-opts.sh:18:12: error: This expression is constant. Did you forget a $ somewhere? [SC2078]
16|       elif [ -e /sbin/syslogd ]; then
17|           syslogtype="syslogd"
18|->     elif [ /sbin/syslog-ng ]; then
19|           syslogtype="syslog-ng"
20|       else
Error: SHELLCHECK_WARNING:
/usr/lib/dracut/modules.d/90crypt/crypt-lib.sh:15:29: error: Since you …

all: fix issues found by shellcheck

---

51-dracut-rescue.install

Commit 5e574046e76e ("5?-dracut*.install: Allow scripts to install
the initramfs in /boot dir") added support to generate initramfs
images in the /boot directory and copy the respective BLS files.
Unfortunately, it broke the rescue initramfs generation when it's
not installed on /boot due checking for wrong conditions. Fix it.
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>

51-dracut-rescue.install: fix for initramfs not generated in /boot

---

modules.d/50plymouth/module-setup.sh

Some distros have both /usr/lib/plymouth and /usr/libexec/plymouth
directorirs, so we should check the existance of plymouth-populate-initrd
script.
Fixes: 421b46f8ae89cfe2b62e880a8a5079ee8c1b3aae

plymouth: fix detection of plymouth directory

---

modules.d/50drm/module-setup.sh

During dracut runs users of VoidLinux reported ERROR messages. After some investigation I concluded that those errors are non-fatal and can be ignored. Nontheless, to prevent further confusion, let's make the installation of those drm modules optional so no error is occuring.

make failing installation of drm modules nonfatal

---

modules.d/90crypt/module-setup.sh

Convert the s390x into s390 to also include s390-specific crypto
modules, for example, aes_s390 into the initramfs.
Signed-off-by: Hendrik Brueckner <brueckner@linux.ibm.com>

crypt: correct s390 arch to include arch-specific crypto modules

---

dracut.sh

It's possible for e.g. `kernel` to be installed as an RPM BuildRequires or equivalent,
and there's no reason to sync, and *definitely* no reason to fsfreeze.
Another case where this happens is rpm-ostree, which performs its own sync/fsfreeze
globally.  See e.g. https://github.com/ostreedev/ostree/commit/8642ef5ab3fec3ac8eb8f193054852f83a8bc4d0

Suppress sync/fsfreeze if not running on a live system

---

dracut.cmdline.7.asc
modules.d/40network/ifup.sh
modules.d/40network/net-lib.sh
modules.d/40network/parse-ip-opts.sh

In kdump, if dump-target is ssh on ipv6, we need to sync until ipv6 addr
is ready. Currently ip=auto6/dhcp6 provides such function. But in 1st kernel,
it is hard to know whether the ipv6 addr is got by dhcpv6 or SLAAC.
E.g ifcfg-eth* contains DHCPV6C=yes direction, but there is no dhcpv6
server in the network, and then after the system is up, the user
echo 1 > /proc/sys/net/ipv6/conf/eth0/autoconf && accept_ra by manual
to obtain a ipv6 addr. Or vice.
So this patch suggests to make dhcpv6 as auto6 fallback
Signed-off-by: Pingfan Liu <piliu@redhat.com>

40network: introduce ip=either6 option

---

modules.d/01fips/module-setup.sh

SHA-3 and SM3 have been added to the tcrypt module recently, so without
them the 'modprobe tcrypt' step causes a kernel panic.

fips: add sha3_generic and sm3_generic modules

---

dracut.sh

When dracut silently produces a broken initramfs, then the system will
likely not boot and this can be very problematic. Typical use case is
after the kernel has been updated.
It appears that dracut is not protected against the **BASH_ENV** variable,
causing various scripts called by dracut to possibly fail or provide
wrong output (e.g. `ldd` is one of these).
Having a broken output for `ldd` makes the generated initramfs be not
usable, typically because vital binaries will be missing (e.g.
`awk`, `udevadm`, ...).
Note: because the shebang line cannot contain more than one argument,
the `--norc` option had to be removed. IMHO, it was useless anyway.
Signed-off-by: Renaud Métrich <rmetrich@redhat.com>

Harden dracut against BASH_ENV environment variable

---

51-dracut-rescue.install

After the $COMMAND case statement, the exit status of the last executed
command is added to the $ret variable.
But for the "add" pattern, this last executed command is an arithmetic
expression that also adds the exit status $? to the $ret variable. If
both $? and $ret are 0, then the arithmetic expression evaluates to 0
so is considered false and has an exit status of 1.
This makes the script to wrongly exit with an status code of 1 when it
should had been 0.
case "$COMMAND" in
add)
...
((ret+=$?))
;;
...
esac
((ret+=$?))
exit $ret
Since $ret is set in the case statement, just exit with that status code
and remove the last arithmetic expression that wrongly sets $ret to 1.
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>

51-dracut-rescue.install: fix exit status code

---

modules.d/01fips/module-setup.sh

This patchset adds `crypto_user` to the list of FIPS modules (needed by sha512hmac in Fedora 28+) and also cleans up the list of modules. See individual commit messages for more details.

fips: Add new required module + cleanup

---

modules.d/50drm/module-setup.sh

The code in 50drm which tries to include all DRM drivers for
hardware attached to the system did not look for virtio devices.
So if the system is a VM using the 'virtio' graphics adapter,
the 'virtio-gpu' module which should be included is not. This
extends the code to also look for virtio devices.
https://bugzilla.redhat.com/show_bug.cgi?id=1593028
Signed-off-by: Adam Williamson <awilliam@redhat.com>

Include virtio DRM drivers in hostonly initramfs

---

dracut-init.sh
dracut.sh
modules.d/90kernel-modules/module-setup.sh

Now --hostonly accept a optional <mode> parameter, so we have
a tri-state hostonly mode:
* generic (non-hostonly): by passing "--no-hostonly" or not
passing anything
* sloppy: by passing "--hostonly sloppy" or just "--hostonly"
* strict: by passing "--hostonly strict"
Sloppy mode is the original hostonly mode, the new introduced strict
mode will allow modules to ignore more drivers or do some extra job to
save memory and disk space, while making the image less portable.
Also introduced a helper function "optional_hostonly" to make it
easier for modules to leverage new hostonly mode.
To force install modules only in sloppy hostonly mode, use the form:
hostonly="$(optional_hostonly)" instmods <modules>

Introduce tri-state hostonly mode

---

modules.d/95qeth_rules/module-setup.sh

Only pick rules for interfaces which have a carrier in the running
system. Those interfaces will be assembled by udev to allow booting
from those devices (i.e. iSCSI).
Reference: FATE#323440

95qeth_rules: Add new module to copy qeth rules

---

modules.d/40network/ifup.sh

when set the kernel parameter ```ip=<client-IP>:[<peer>]:<gateway-IP>:<netmask>:<client_hostname>:<interface>:{none|off|dhcp|on|any|dhcp6|auto6|ibft}[:[<mtu>][:<macaddr>]]```, ```iface_has_carrier``` is skipped. And then fail curl fetch for ```root=live:<url>```.
fix check interface linkup (and delayed) by ```iface_has_carrier``` always.

ifup.sh: don't wait linkup when set static ip explicitly

---

dracut.sh

Check for a common binary in systemdutildir. This resolves an issue on
split-usr systems, where it is common to have both /lib/systemd[/system]
and /usr/lib/systemd[/user] present.
Check for systemd-udevd specifically, since some distros (Gentoo) allow
udev to be installed without the rest of the systemd stack.
Similar logic is applied to udevdir simply for consistency.

dracut.sh: improve udevdir and systemdutildir fallback logic

---

dracut-functions.sh
dracut.sh

A hostonly image will not include every possibly required kernel module,
so if any hardware or configuration changed, the image may fail to boot.
One way to know if there are any hardware change or configuration change
that will require an image rebuild or not is to check the loaded kernel
module list. If the loaded kernel module list differs from last build
time, then the image may require to be rebuilt.
This commit will let dracut record the loaded kernel module list when
the image is being built, so other tools or services can compare this
list with currently loaded kernel modules to decide if dracut should be
called to rebuild the image.
To retrieve the loaded kernel modules list when an image is built, use
lsinitrd command:
`lsinitrd $image -f */lib/dracut/loaded-kernel-modules.txt`

Record loaded kernel modules when hostonly mode is enabled

---

modules.d/00warpclock/module-setup.sh
modules.d/00warpclock/warpclock.sh

Add module for setting correct timezone.
References: bnc#830060
For now, this module will not be included automatically due to different
expectations (see e.g. https://bugzilla.redhat.com/show_bug.cgi?id=981617).
Signed-off-by: Daniel Molkentin <daniel.molkentin@suse.com>

00warpclock: Set correct timezone

---

modules.d/90kernel-modules/module-setup.sh

This is needed since few gpio/pinctrl can be built as modules and are
useful on early boot.
One example is jetson-tx1 where sata and external mmc can work only
after loading pinctrl-max77620 and gpio-max77620 modules.
Having theses kind of drivers bundled into the initramfs will also
avoid some deferred probes.
Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>

Add gpio and pinctrl drivers for arm*/aarch64

---

dracut-functions.sh

I have no idea why, but on Fedora the original code works just fine, but on rhel7 the loop is only executed for the first line. The double apostrophe seems to fix it.

dracut-functions: fix the word splitting

---

modules.d/45ifcfg/module-setup.sh
modules.d/45ifcfg/write-ifcfg.sh

The old code used /tmp/net.$netif.resolv.conf with $netif being randomly
chosen.
As it is not known which nameserver have which priority, just sort them
and deduplicate.
Fixes https://github.com/dracutdevs/dracut/issues/410

ifcfg/write-ifcfg.sh: aggregate resolv.conf

---

dracut.cmdline.7.asc
modules.d/90dmsquash-live/dmsquash-live-root.sh
modules.d/90dmsquash-live/parse-dmsquash-live.sh
modules.d/90livenet/livenet-generator.sh

Adjust sysroot.mount configuration for rd.live.overlay.overlayfs option.
Use link at /dev/root as a consitent flag for wait_for_dev.
Adjust documentation.
Addresses Issue #432.
Tested by: @GigabyteProductions see https://github.com/dracutdevs/dracut/issues/432#issuecomment-409811868.

livenet: Enable OverlayFS overlay in sysroot.mount generator.

---

dracut.cmdline.7.asc
modules.d/90dmsquash-live/dmsquash-generator.sh
modules.d/90dmsquash-live/dmsquash-live-root.sh
modules.d/90livenet/livenet-generator.sh

~~~~txt
A simplified root filesystem structure may be provided for OverlayFS
overlays by squashing the root filesystem directly instead of squashing
an embedded image file at /LiveOS/rootfs.img.  Detect and configure
such a squashed root filesystem for live booting.
For OverlayFS boots, avoid the read-only Device-mapper linear device
at /dev/mapper/live-base.
Create a consistent device link at /dev/live-base for the read-only
base loop device for all overlayed live root filesystems.
Consistently provide a link at /dev/root for wait_for_dev.
Update documentation.
Also,
dmsquash-live, livenet: Simplify OverlayFS read-only overlay setup.
Use multiple lower layer directories in a single OverlayFS mount with
a transient overlay directory.
Tolerate a command line with rd.live.overlay.readonly …

dmsquash-live: Support a flattened squashfs.img 

---

modules.d/99base/module-setup.sh

When extra devices are added, initqueue should be enabled to make sure
those devices are present, so following services and routines could
use those devices.
See PR #442 for more detail.

99base: enable initqueue if extra devices are added

---

modules.d/90kernel-modules/module-setup.sh

Include "nfit" module so that pmem device could work.

Make dracut work well with pmem device

---

dracut.cmdline.7.asc
dracut.modules.7.asc
dracut.usage.asc
mkinitrd-suse.8.asc

Also remove some trailing whitespaces from the same files.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

Fix misspellings in man pages and usage

---

modules.d/90dmsquash-live/apply-live-updates.sh
modules.d/90dmsquash-live/dmsquash-generator.sh
modules.d/90dmsquash-live/dmsquash-live-root.sh
modules.d/90dmsquash-live/module-setup.sh
modules.d/90dmsquash-live/parse-dmsquash-live.sh

die when required; systemctl reload otherwise.
Also:
strstr and variable string manipulations suffice.
Also:
Update flag link to /dev/root as required by commit
789668d.
This should fix issue #455

dmsquash-live-root: Manage absent overlayfs module better.

---

modules.d/01systemd-initrd/module-setup.sh
modules.d/99base/module-setup.sh

Prevent environment leaking into initrd-release
On my system the following initrd-release is generated:
...
VERSION="4 dracut-048 dracut-048"
...
VERSION is not defined in /etc/os-release, so the variable is
concatenated with its previous value:
* "4" comes from the kernel build system since dracut is called from the
kernel install hook ("4" is a major kernel version);
* first "dracut-048" comes from the "systemd-initrd" module;
* second "dracut-048" comes from the "base" module.

Prevent environment leaking into initrd-release

---

install/util.h

Lets not unnecessarily rely on __WORDSIZE, which is not clearly specified
by any spec. Use explicit size comparisons if we're not interested in the
WORDSIZE, anyway.
Patch ported from systemd.
(commit https://github.com/systemd/systemd/commit/8507eb20b64010b26f23822cbf442bb0bf96511c)
Original-patch-by: Emil Renner Berthing <systemd@esmil.dk>
Bug: https://bugs.gentoo.org/602122

install: avoid non-portable __WORDSIZE

---

modules.d/99base/dracut-lib.sh

"type -P" doesn't work in dash

base/dracut-lib.sh: use "command -v" in pidof()

---

dracut.sh
dracut.spec
modules.d/99squash/clear-squash.sh
modules.d/99squash/init.sh
modules.d/99squash/module-setup.sh
modules.d/99squash/setup-squash.sh
modules.d/99squash/shutdown.sh
modules.d/99squash/squash-mnt-clear.service

With all files stored in ramfs, and most of them are not compressed,
the initramfs will take up a lot of memory. Besides, if the file number
is large, each file will waste some memory due to page fragmetation.
This is due to ramfs' design, at least one page will be allocated for
one file however small the file is. On machine with large page size,
this will become worse and waste too many memory.
One approach to reducing the memory usage is to reduce the number of
files that got directly loaded into the root ramfs, and compress files
by put most files will into a read-only squash image and keep a minimum
set of executable and libraries outside as the loader for the squash
image. After the squash image is mounted, the real 'init' will be
executed and then everything behaves as usual.
This …

Add support for building a squashed initramfs

---

modules.d/40network/ifup.sh

If the network module obtained a lease using dhclient, NetworkManager
must be configured to use it too, otherwise it would obtain a different
lease (and could potentially break a connection to the network volume).

network: configure NetworkManager to use dhclient

---

dracut.spec
modules.d/90kernel-modules-extra/module-setup.sh

It parses depmod configuration and scans modules.dep for kernel modules
present in directories supplied in "overrides", "external", and "search"
depmod configuration options.  The resulting list of (absolute) kernel
module paths is then supplied to instmods.
* modules.d/90kernel-modules-extra/module-setup.sh: New file.
Signed-off-by: Eugene Syromiatnikov <esyr@redhat.com>

modules.d: Add a module for handling additional depmod kernel module directories

---

install/dracut-install.c

The previous logic would not handle absolute paths on the left side of
the "=>" properly. For example, on Gentoo ARM64, ldd outputs this:
/lib/ld-linux-aarch64.so.1 => /lib64/ld-linux-aarch64.so.1
At runtime, the kernel tries to load the file from /lib, and fails if we
only provide it in /lib64.
Instead of looking for the first slash after the "=>", just look for the
first slash, period. This would fail if we somehow had a relative path
on the left side (foo/libbar.so), but I'm not aware of any binaries that
would contain such an entry in DT_NEEDED.
Bug: https://bugs.gentoo.org/667752
Signed-off-by: Mike Gilbert

dracut-install: simplify ldd parsing logic

---

dracut.spec

70291e0 ('dracut.spec: Add dracut-squash package') introduced a new
dracut-squash package, but by accident it overrided some other package
spec and the dependency name is wrong. This patch will fix it.

dracut.spec: Fix error introduced by 70291ed

---

modules.d/40network/module-setup.sh

commit 7347391 ('network-legacy: split off from network module')
splitted network function to network-legacy and removed check() function
of 40network. This caused 40network to be included even if network is
not needed.

40network: Don't include 40network by default

---

modules.d/99squash/squash-mnt-clear.service

The only time we need to cleanup squahfs manually is on switch root, to
release resource and memory. We've covered that by setting
"Conflicts=initrd-switch-root.target" for squash cleanup service.
On shutdown systemd will take care of squahfs mounts. But for other
isolate, files in initramfs are most likely still required, so don't
clean up squahfs. For example, kdump's emergency handler will isolate
into its own target, if squahfs is cleaned up it will fail.

99squash: Don't clean up squahfs on isolate

---

modules.d/01fips/module-setup.sh

When booting a system with **/** and **/boot** on iSCSI, mounting /boot early in the initramfs (`x-initrd.mount`) and enabling FIPS, the system cannot boot because `fips.sh` doesn't find the `.hmac` file for the kernel.
The root cause is `01-fips-noboot.sh` runs in `pre-pivot`, which happens after `systemd-mount.service` was executed.
Due to having `x-initrd.mount` for **/boot**, systemd mounts the partition to **/sysroot/boot**.
Then in `pre-pivot`, `01-fips-noboot.sh` mounts the partition to **/boot** which fails since it is already mounted on **/sysroot/boot**.
Additionally, 20 seconds are lost during boot because `pre-trigger/01-fips-boot.sh` tries to mount **/boot** but at this step, there is no network and no iscsi yet.
I don't understand why FIPS check runs at this step, I do not …

fips: check fips integrity just before mounting local filesystems in /sysroot

---

modules.d/95dasd_rules/module-setup.sh
modules.d/99base/dracut-lib.sh

Triggered on 390x, but the backslash read fix
is useful on all platforms.

Two fixes related to host_only behavior

---

modules.d/95iscsi/module-setup.sh

These dependencies cause an odd issue where swap devices specified
by resume= on the kernel command line will cause systemd device
timeouts to occur on boot. According to @haraldh these lines aren't
needed because the socket activiation will take care of it for us.
Removing these lines now as it fixes the resume= device timeout issue.
Fixes #480
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1641268

95iscsi: drop systemd dracut service dependencies for iscsid

---

50-dracut.install
51-dracut-rescue.install

The kernel-install is called even if you run make install.
Since we don't call dracut with -f a second make install will fail
because initrd with same version is already there.
This makes kernel developers feel miserable.
https://bugzilla.redhat.com/show_bug.cgi?id=1642402

dracut.install: call dracut with --force

---

dracut-initramfs-restore.sh
dracut.sh
modules.d/99squash/shutdown.sh

When building squash image, squash module forgot to install the new
shutdown.sh, and the shutdown hooks are always skipped on ordinary
shutdown if squash module is enabled.
The new shutdown.sh will remount the squash image and then everything
will just work, but currently re-mounting the squash image on shutdown
may have selinux problem and make the system hang, and there is no
easy way to fix it.
So skip fixing the shutdown.sh not being install problem, instead
just drop the new shutdown.sh, and unsquash the image on ordinary
shutdown, which is safer and should always work.

squash: unsquash the root image instead of mounting it on shutdown

---

modules.d/99shutdown/shutdown.sh

Arguments "-f -d -n" fails with "invalid number -n", because -d delay expects number of seconds.

Delay argument "-d" requires number

---

modules.d/01fips/fips.sh

When booting a RHEL7.6 system with FIPS, the journal records the following messages:
~~~
Nov 14 13:14:05 vm-fips7 dracut-pre-trigger[241]: modprobe: FATAL: Module sha1 not found.
Nov 14 13:14:05 vm-fips7 dracut-pre-trigger[241]: modprobe: FATAL: Module sha256 not found.
~~~
These are due to the initramfs not containing the **sha1** and **sha256** modules because they are blacklisted in `/lib/modprobe.d/dist-blacklist.conf`:
~~~
blacklist sha1-mb
blacklist sha256-mb
~~~
This causes dracut's **instmods** to just ignore these.
Because the kernel provides a generic algo for these, there is no need to output these misleading and confusing messages.

fips: removed false-positive 'FATAL: Module xxx not found' error message when kernel provides a generic algo for module

---

modules.d/05busybox/module-setup.sh

should have been killed in commit 4a855e6bebed956c108865823bcc131ebea2841a

cleaning busybox module (kill bogus comment)

---

dracut.modules.7.asc

Correct simple typo in .7 manpage for dracut.
Signed-off-by: Bruno E. O. Meneguele <bmeneg@redhat.com>

dracut.modules.7.asc: typo correction

---

modules.d/40network/net-lib.sh
modules.d/95iscsi/mount-lun.sh
modules.d/95virtfs/mount-virtfs.sh
modules.d/99base/dracut-lib.sh

as this breaks busybox hush shell.
offending functions can be found with
grep -r '${[^}]*"[^}]*}'

remove superfluous quotes in parameter expansion

---

dracut.sh

Normally copying files to staging area the modification time is preserved. However, when the strip_cmd is "strip" and not "eu-strip", the strip command changes the modification time of the objects and executables even when there are no debug variables to strip out from the original file.

the strip command should avoid changing the file modification time

---

modules.d/90crypt/crypt-lib.sh
modules.d/90crypt/parse-keydev.sh
modules.d/91crypt-gpg/crypt-gpg-lib.sh
modules.d/95dcssblk/parse-dcssblk.sh
modules.d/98syslog/rsyslogd-start.sh

When using dash as initramfs shell, the boot process is broken.
Signed-off-by: Đoàn Trần Công Danh <congdanhqx@gmail.com>

remove bashism in various boot scripts

---

modules.d/98dracut-systemd/dracut-emergency.sh
modules.d/98dracut-systemd/module-setup.sh
modules.d/99base/module-setup.sh

- allow emergency login on every console
specified in the kernel cmdline
- require password for hostonly images
- emergency mode: Manually multiplex emergency infos
This will bring all vital information to all ttys specified
as console devices, regardless of wether they hold the C flag.
Reference: FATE#325386
Reference: #449

emergency mode: use sulogin

---

lsinitrd.sh

When the initramfs is built with squash module enabled, the content
inside squash image will be invisible from the lsinitrd tool. This
commit make lsinitrd detect and list the content of the squash image as
well to avoid possible confusion.

lsinitrd: list squash content as well

---

modules.d/95iscsi/module-setup.sh

I don't think that 765b203 was a correct fix for the issues we saw in https://github.com/dracutdevs/dracut/issues/480. You would still hit that issue, if you have a swap on the iscsi disk (but probably nobody uses such setup).
The original fix removed the systemd dependency there, but the ordering is more or less still the same. I think that a bigger issue is that iscsi sockets have a default dependency on sysinit.target, which is pretty late (after local-fs.target). So I think we should break the cycle there.

[wip] fix weird issues around iscsid dependencies

---

dracut.conf.d/gentoo.conf.example
dracut.conf.d/suse.conf.example

It has
omit_drivers+=" i2o_scsi"
which would break the next omit_drivers+="foo " if it's
missing a space at the beginning.
Reference: boo#1121251

Fix a missing space in example configs

---

modules.d/10i18n/module-setup.sh

Eliminate erroneous substring matches when looking up already processed keymaps to prevent necessary keymaps not getting added to the initramfs sometimes e.g. if there are the files *'compose.latin1'* and *'compose.latin1.add'* the unfixed version would skip processing *'compose.latin1'* if **'find'** returned *'compose.latin1.add'* first due to the directory listing not being in sorted order.

10i18n: Fix keymaps not getting included sometimes

---

modules.d/00systemd/module-setup.sh

The recent systemd upstream introduced a slightly modified version
string which included information about a git commit, which however
broke the version check in dracut. Unfortunately, the (( )) bash syntax
went along with it in certain cases and introduced a pretty nasty issue,
when the systemd would boot up but with slightly changed environment.
To prevent this from happening in the future, let's at least check if
the version parsed from the `systemd --version` output is a comparable
number.
---
Few days ago, a certain commit in systemd introduced change into the systemd version schema, which changed `systemd 240` to `systemd 240-63-g4199f68+`. This change was merged, as the CIs, including the CentOS CI with dracut, were passing.
Moving two days forward, the CentOS CI started suddenly …

00systemd: check if systemd version is a number

---

modules.d/91zipl/module-setup.sh

Comment lines should be ignored. They should not be used for determining
the /boot/zipl device

91zipl: Don't use contents of commented lines

---

modules.d/98dracut-systemd/dracut-emergency.sh

/dev/consoles does not exist. It's /proc/consoles.
Signed-off-by: Böszörményi Zoltán <zboszor@pr.hu>

Fix 98dracut-systemd/dracut-emergency.sh

---

install/dracut-install.c

If kmod_module_get_path returns NULL, we should skip that entry,
the hash function does not like NULL pointers.

install: string_hash_func should not be fed with NULL

---

modules.d/95iscsi/module-setup.sh

When `iscsi-initiator-utils` package is installed but there is no iscsi device, trying to create a initramfs with manually including some file into the initramfs fails to include the file, but includes an empty directory instead:
~~~
Arguments: --force --include './myfile' '/mydir/myfile'
drwxr-xr-x   2 root     root            0 Mar  1 11:53 mydir/myfile
~~~
We can see that **myfile** is now an empty directory.
If we uninstall the `iscsi-initiator-utils` package, then it works because the **95iscsi** module is skipped:
~~~
Arguments: --force --include './myfile' '/mydir/myfile'
-rw-r--r--   1 root     root            7 Mar  1 11:55 mydir/myfile
~~~
This is due to a missing `popd` instruction.

iscsi: always popd, even if there is no iscsi device

---

modules.d/01fips/module-setup.sh

When using dracut with  --hostonly and --no-hostonly-default-device,
/boot will be inaccessible as dracut will most fs modules unless
specified. But FIPS require /boot to be accessible, and it will try
to mount it on boot. It will fail if corresponding fs module is missing.
For most case /boot will be a simple partition, include the fs module
will be enough for FIPS to mount it. For other cases users have to pass
extra parameters by themselves.
Suggested-by: Kenneth Dsouza <kdsouza@redhat.com>

fips: ensure fs module for /boot is installed

---

dracut-init.sh

The upcoming kernel will have a support for loading compressed
firmware files, and this patch corresponds to that kernel change.
When a firmware file with the extra .xz extension is found, dracut
copies to initrd as fallback.  Since initrd itself is compressed, the
file is uncompressed in initrd beforehand.

dracut-install: Add support for compressed firmware files

---

modules.d/95nfs/module-setup.sh

There is no reason why the network setup of an nfs client needs to be static.
We should rather use the BOOTPROTO setting from the ifcfg file and only fall back to a static setup, if this information is not available.

nfsroot follow ifcfg settings for boot protocol

---

modules.d/35network-legacy/ifup.sh

modules.d/35network-legacy/dhclient-script.sh takes over the task of calling netroot when using dhclient for network setup.
This is not the case when wicked is used.
Hence we need an explicit call to the netroot script for the wicked case.

call netroot on wicked dhcp setup

---

modules.d/95fcoe/parse-fcoe.sh

The parse-fcoe.sh hook is sourced, and hence must not contain
exit 0 calls. Otherwise, the cmdline sequence will be interupted,
and no error will be reported to systemd. Use return instead.
Reference: boo#1136977

95fcoe: Fix startup when fcoe module is included

---

mkinitrd-suse.sh

This generalizes the naming and provides a workaround for compressed
kernels on s390.
Reference: bsc#1139939

mkinitrd-suse.sh: simplify get_kernel_version

---

dracut.sh

In commit [9d1b81c dracut.sh: improve udevdir and systemdutildir
fallback logic] , it checked a common binary `collect' to location
udevdir.
But upstream systemd drop binary `collect' since systemd v240
[https://github.com/systemd/systemd/commit/a168792c2d95695fd30c0371d4b3890a9df1eafb]
So check binary `ata_id' to instead.
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>

dracut.sh: Fix udevdir detection

---

modules.d/99squash/module-setup.sh

insmods will consider all arguments as optional modules by default, but
for squash module, all listed modules are required, if any of them is
missing the initramfs won't boot. So pass the '-c' argument to let instmos
know all those modules are mandatory, it will fail and give an error if
it failed to install any of those modules.

99squash: fail early if can't install require modules in initramfs

---

dracut-functions.sh
dracut.sh

Previous in commit 7047294, dracut will include the loaded kernel module
list in initramfs, so other tools could check if the loaded kernel
module is changed and rebuild the host only initramfs in case some
module required to boot the machine is missing due to host only install.
It's better to use modalias list generated by dracut-install, that
list includes the device modalias list combined with current loaded
kernel module list. In this way, if any kernel module is yet to be
loaded when the initramfs is built, or got unloaded by accident the
module list will not change. This make the list more stable over
initramfs builds.

dracut.sh: record the actual host only module for hostonly mode

---

dracut-init.sh
dracut.sh

Let the caller pass in the module path instead of try to find the module
path everytime. This helps optimize the overall runtime.
Test results (3 rounds) on Fedora 30 in KVM VM with 8 CPUs, 2G memory, HDD:
$ time ./dracut.sh --local --quiet --hostonly --hostonly-cmdline --hostonly-i18n --hostonly-mode 'strict' -o 'plymouth dash resume ifcfg' --mount '/dev/mapper/fedora-root /sysroot xfs defaults' --no-hostonly-default-device -f initramfs.img
Before the commit:
real    0m11.782s  |  real    0m11.505s  |  real    0m11.958s
user    0m9.169s   |  user    0m9.218s   |  user    0m9.327s
sys     0m10.839s  |  sys     0m10.829s  |  sys     0m10.925s
After this commit:
real    0m9.866s  |  real    0m9.580s  |  real    0m9.638s
user    0m9.048s  |  user    0m9.142s  |  user    0m9.120s
sys …

dracut: let module handling function accept optional path option

---

modules.d/99base/module-setup.sh

…n time
Recently, we have encountered some kdump failures of virtual machines.
Although the device driver has been added to kdump initrd, the driver
is not loaded because the device isn't present yet, it's not brought up
in time. Which causes the kdump failure.
Therefore, the initqueue mechanism is still necessary for all devices
that need to be brought up in time.
Signed-off-by: Lianbo Jiang <lijiang@redhat.com>

99base: enable the initqueue in both 'dracut --add-device' and 'dracut --mount' cases

---

test/TEST-17-LVM-THIN/create-root.sh
test/TEST-17-LVM-THIN/test.sh

This condition is rather difficult to detect -- the writes will just remain
queued and get lost on shutdown, resulting in a corrupt filesystem.

test/TEST-17-LVM-THIN: fail setup if we run out of space in the thin pool

---

lsinitrd.sh

This patch enables `lsinitrd` to inspect UEFI images created with `dracut --uefi`

add support in lsinitrd.sh for UEFI images

---

modules.d/90crypt/cryptroot-ask.sh

This fixes a problem I had on my systems where the password stored in a keyfile was not correct. `cryptsetup` produced an error message and could not open the root device. In such a case shouldn't the user be asked for a password instead in order to recover the system?

ask for a password on readkey failure

---

dracut.conf.5.asc
dracut.sh

This adds configuration parameters `uefi_secureboot_cert` and `uefi_secureboot_key`.
In dracut's `--uefi` mode, provided `sbsign` is installed, the resulting UEFI executable is signed with the key.

Add support for creating signed UEFI images

---

test/TEST-14-IMSM/create-root.sh

The dracut-root-block-created line should not be created if we fail to copy
in the required files to sysroot. Let's turn on -e to trap failures and
poweroff on them, like some other tests do.
Also remove the &&. Not only it is unnecessary with -e, but defeats it.
From bash(1):
The shell does not exit if the command that fails is [...] part of any
command executed in a && or || list except the command following the
final && or || [...]

test/TEST-14-IMSM: detect failure to compose the test setup root

---

test/TEST-01-BASIC/test.sh
test/TEST-02-SYSTEMD/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-04-FULL-SYSTEMD/test.sh
test/TEST-10-RAID/test.sh
test/TEST-11-LVM/test.sh
test/TEST-12-RAID-DEG/test.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/test.sh
test/TEST-15-BTRFSRAID/test.sh
test/TEST-16-DMSQUASH/test.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-20-NFS/test.sh
test/TEST-30-ISCSI/test.sh
test/TEST-31-ISCSI-MULTI/test.sh
test/TEST-40-NBD/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-70-BONDBRIDGETEAMVLAN/test.sh

Otherwise systemd would freeze execution, causing the test to time out
instead of failing fast.

test: tell systemd to reboot on fatal errors

---

modules.d/95iscsi/module-setup.sh

There are multiple problems with network setup code in 95iscsi:
- The network script and config is in "/etc/sysconfig/network-scripts".
So fix the look up path.
- The regex used for sed is not working, so fix it too.

95iscsi: Fix network setup

---

modules.d/99fs-lib/fs-lib.sh

Bash 5 apparently longer propagates variable assignments to local variables
in front of function calls when in POSIX mode:
[lkundrak@demiurge ~]$ cat feh.sh
print_VAR () {
echo "$VAR";
}
testfunc () {
local VAR="OLD"
VAR=NEW print_VAR
}
testfunc
[lkundrak@demiurge ~]$ bash4 --posix feh.sh
NEW
[lkundrak@demiurge ~]$ bash5 --posix feh.sh
OLD
[lkundrak@demiurge ~]$ bash5 feh.sh
NEW
[lkundrak@demiurge ~]$
It works the way it did in Bash 4 in non-POSIX mode, for external programs,
or for non-local variables. Don't ask me why -- it's probably some
compatibility thing for some sad old people.
However, this precisely happens when fsck_single() is calling into the
fsck_drv_com(), assigned to _drv by fsck_able(). That ruins the
TEST-70-BONDBRIDGETEAMVLAN test's server and probably more.
Let's pass …

fs-lib: drop a bashism

---

modules.d/35network-legacy/dhclient-script.sh

The current dhclient-script doesn't handle the case when classless static route with mask length=0, the patch fixes the problem, sample dhcp code 121:
option rfc2442-classless-static-routes 0,10,0,0,1,16,169,254,0,0,0,0

35network-legacy: fix classless static route parsing

---

modules.d/95fcoe/parse-fcoe.sh

The kernel may only enable 'libfcoe' module. Some modules like bnx2fc
provides FCoE but only depend on 'libfcoe'. Loading 'fcoe' module may
fail but the kernel do support FCoE.
'libfcoe' will be installed as a dependency when installing block device
drivers if it's required. So no need to install it in installkernel.

95fcoe: load 'libfcoe' module as a fallback

---

test/TEST-10-RAID/create-root.sh
test/TEST-10-RAID/test.sh
test/TEST-12-RAID-DEG/test.sh
test/TEST-13-ENC-RAID-LVM/create-root.sh
test/TEST-13-ENC-RAID-LVM/test.sh
test/TEST-14-IMSM/create-root.sh
test/TEST-14-IMSM/test.sh
test/TEST-17-LVM-THIN/create-root.sh
test/TEST-17-LVM-THIN/test.sh
test/TEST-30-ISCSI/test.sh
test/TEST-31-ISCSI-MULTI/test.sh

On Fedora 30 the paritition sizes turn out to be too small again:
```
+ mkdir -p /sysroot
+ mount /dev/dracut/root /sysroot
+ cp -a -t /sysroot /source/bin /source/dev /source/etc /source/lib /source/lib64 /source/proc /source/root /source/sbin /source/sys /source/tmp /source/usr /source/var
cp: error writing '/sysroot/usr/lib64/libkrb5.so.3.3': No space left on device
cp: error writing '/sysroot/usr/lib64/libkrb5support.so.0.1': No space left on device
```
It turns out that there has been quite some size increase in some libraries,
notably glibc, though not all -- some even shrunk, ruling out a toolchain
problem. Here's are files over 1M we install on Fedora 30:
```
f29    f30
2.7M => 6.4M /usr/lib64/{libc-2.28.so => libc-2.29.so}
3.1M => 6.0M /usr/lib64/libcrypto.so.1.1.1c
2.0M => 3.5M …
```

test/{10,12,13,14,30,31}: increase the disk sizes

---

dracut.sh

The EFI executables produced by `dracut --uefi` must be placed in the subdirectory `/EFI/Linux` of the EFI system partition (ESP) according to the [Boot Loader Specification](https://systemd.io/BOOT_LOADER_SPECIFICATION#logic).
This is done correctly for the mount points `/boot` and `/boot/efi`, but for the mount point `/efi`, the files are placed in `/efi/Linux` instead of the correct `/efi/EFI/Linux`. This commit fixes the directory so that the EFI executables are picked up correctly by conforming boot loaders.
Apart from complying to the specification, the change is also in line with the commit message of 5c57209ba5ef36f8856b4ea1694de8e1da508b71 ("dracut.sh: add default path for --uefi") which introduced this feature as well as the documentation in …

dracut.sh: fix EFI directory if ESP is mounted to /efi

---

dracut.sh

on line 1086 it's used to check for the uefi_stub:
"${systemdutildir}/boot/efi/linux${EFI_MACHINE_TYPE_NAME}.efi.stub"
so it needs to be defined before that

move setting the "systemdutildir" variable before it's used

---

modules.d/99base/dracut-lib.sh

When DRACUT_SYSTEMD is set and DRACUT_QUIET=yes, vinfo returns 1. This is a problem for hooks which end with vinfo, as then the hook returns 1. Especially problematic if this is a shutdown hook, as it will be restarted again and again.
This commit fixes that.

99base: Don't let vinfo return 1

---

Makefile
dracut.sh
modules.d/90crypt/module-setup.sh
test/TEST-99-RPM/test.sh

`arch` is an alias for `uname -m` that is not provided by all distributions, so replacing it improves portability. This has already been done in some places, see e.g. ffe53c91c5e56f8fb1f3fbfa84275822074f52d6, this pull requests fixes the remaining occurrences.

Replace $(arch) by $(uname -m)

---

modules.d/01fips/fips-load-crypto.sh
modules.d/01fips/fips.sh
modules.d/01fips/module-setup.sh

In e54ab383 we moved the fips script to a later pahse of boot, since
the /boot might not be available early on.
The problem is that systemd-cryptsetup* services could be run now
started before the do_fips is executed and need the crypto modules
to decrypted the devices.
So let's split the do_fips and load the module before udev does the
trigger.

fips: split loading the crypto modules and checking the kernel

---

dracut-init.sh
modules.d/90qemu-net/module-setup.sh
modules.d/90qemu/module-setup.sh
modules.d/95virtfs/module-setup.sh

Eventually, we could add a full virt detection routine.
This would be useful e.g. to determine inclusion of
ucode for hostonly setups.

Consollidate the qemu virtualization detection

---

modules.d/00systemd/module-setup.sh

The varying rd.live options are not sufficient to cover all bases, such as a normal block device root. systemd has introduced the ability to remount these as tmpfs or overlayfs in the initrd. Dracut however does not include the required binary.
Including the binary and service is sufficient to mount normal block devices and loop mounted block devices as overlays in my tests, but I expect there to be conflicts with rd.live options that I was not able to test. All docker test environments pass locally with these inclusions.
Alternately this could be made available as an additional module, volatile options are quite limited currently so it likely wouldn't replace all rd.live cases either. Happy to work with anyone to achieve this.

00systemd: Support systemd.volatile option by including service

---

modules.d/90kernel-modules-extra/module-setup.sh

When you install a third-party driver, you will probably end in a
situation, where the module will be in a different directory and
in $depmod_module_dir you will only have symlink. If we resolve the
symlink before we pass the module path to instmod, the dracut-install
will only include the module with its original path, but not the
symlink. Hence the module can't be automatically loaded.
Dracut-install is clever enough to handle symlinks and will include both
the symlink and the module to the initrd.

90kernel-modules-extra: don't resolve symlinks before instmod

---

dracut.sh

Previously with squash module, some binaries will be reinstalled, but
stripping happens before that so new installed binaries is not stripped.
So adjust the squash and strip order, ensure new installed binaries are
stripped just the same way with the old binaries.
Also split squash into two stage to make the split easier, move the
squash temp dir into initdir so stripping will cover that too,
and print more usefule message.

dracut.sh: Adjust squash and strip order

---

.travis.yml
git2spec.pl

As Travis CI builds the merge commit[0] of given PR, doing `git pull` during
testing is somewhat useless and breaks testing of PRs against non-master
branches.
One of these *broken* PRs is, for example, https://github.com/dracutdevs/dracut/pull/612.
[0] i.e. `refs/pull/XXX/merge`, see https://docs.travis-ci.com/user/pull-requests/#how-pull-requests-are-built
>  Rather than build the commits that have been pushed to the branch the pull request is from, we build the merge between the source branch and the upstream branch.

travis: fetch only git tags

---

50-dracut.install
51-dracut-rescue.install

When booting with Fedora-Server-dvd-x86_64-30-20190411.n.0.iso,
/proc/cmdline is empty (libvirt, qemu host with bios, not sure if that
matters), after installation to disk, anaconda would "crash" in kernel-core
%posttrans, after calling kernel-install, because dracut would fail
with
> Could not determine the kernel command line parameters.
> Please specify the kernel command line in /etc/kernel/cmdline!
I guess it's legitimate, even if unusual, to have no cmdline parameters.
Two changes are done in this patch:
1. do not fail if the cmdline is empty.
2. if /usr/lib/kernel/cmdline or /etc/kernel/cmdline are present, but
empty, ignore /proc/cmdline. If there's explicit configuration to
have empty cmdline, don't ignore it.

51-dracut-rescue: do not require non-empty kernel cmdline

---

modules.d/98integrity/README

Default value of EVMKEYDESC (in evm-enable.sh) is "evm-key" and it's
also specified previously in this README file.
Signed-off-by: Petr Vorel <pvorel@suse.cz>

doc: Fix integrity key name

---

dracut.sh

This PR proposes to make **dracut** fail when using the `-i` or `--include` option and the specified argument doesn't exist or is not either a directory or a file.

Print an error if included item ('-i' option) doesn't exist or is neither a directory nor a regular file

---

modules.d/40network/netroot.sh
modules.d/98dracut-systemd/dracut-cmdline.sh
modules.d/99base/init.sh

Accidentally folded into commit e671c3a06a7e5 ('95iscsi/module-setup.sh:
do not require 'hostname' anymore').

all: remove debugging leftovers

---

dracut.sh

Since Bash 4.4, command substitutions containing null bytes produce a warning of the form
```
/usr/sbin/dracut: line 1958: warning: command substitution: ignored null byte in input
```
Remove the [trailing null byte](https://github.com/dracutdevs/dracut/blob/707d4e79feadb475b79fd8f15dd2fea70aa79869/dracut.sh#L1955) from the UEFI kernel command line file before printing it to suppress this warning.

dracut.sh: suppress "ignored null byte in input" warning

---

modules.d/90crypt/cryptroot-ask.sh
modules.d/95rootfs-block/mount-root.sh

When using the `crypt` module without systemd-cryptsetup-generator (with `dracut -o systemd`), there is some unwanted output:
- When decrypting LUKS2 partitions, a message
```
WARNING: Locking directory /run/cryptsetup is missing!
```
is printed.
- If `rootflags` are specified on the kernel command line, these are erroneously printed by the `rootfs-block` module.
Creating the required directory beforehand and redirecting the output of `getarg` removes these artefacts.

Suppress spurious output when using crypt module without systemd-cryptsetup-generator

---

modules.d/90dm/59-persistent-storage-dm.rules
modules.d/90dmraid/61-dmraid-imsm.rules
modules.d/90lvm/64-lvm.rules
modules.d/90mdraid/59-persistent-storage-md.rules
modules.d/90mdraid/65-md-incremental-imsm.rules
modules.d/95udev-rules/59-persistent-storage.rules
modules.d/95udev-rules/61-persistent-storage.rules

Starting with the 0.7.7 release of the multipath tools, the multipath
udev rules always set a value in ENV{DM_MULTIPATH_DEVICE_PATH} for any
device that multipath scans. A value of 0 means that the device is not
claimed by multipath, and a value of 1 means that it is. Because of
this, udev rules that check ENV{DM_MULTIPATH_DEVICE_PATH}=="?*" will
always return True, and act as if every scanned device is claimed by
multipath. Checking ENV{DM_MULTIPATH_DEVICE_PATH}=="1" will work
correctly for both the old and new versions of the multipath tools.

modules.d: fix udev rules detection of multipath devices

---

test/test-functions

This is essentially equivalent to what commit 712f471ebfae
('test/test-functions: correctly move server.log') does for V=2.

test: fix preserving server.log with V=1

---

.travis.yml

Thanks to @filbranden, who pointed me to [this tweet](https://twitter.com/_AkihiroSuda_/status/1167336407779557376), I discovered that Travis CI now supports KVM (`vmx` flag in `/proc/cpuinfo`) on Bionic nodes. This should speed up our CI significantly, as currently everything is being tested under QEMU.
Just a quick proof it indeed runs under KVM without any other tweaks (from my debugging session):
```
[    5.986821] Run /init as init process
systemd v241-12.git1e19bcd.fc30 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
Virtualization QEMU found in DMI (/sys/class/dmi/id/sys_vendor)
Virtualization found, CPUID=KVMKVMKVM
Found VM …
```

travis: switch to Bionic

---

modules.d/40network/module-setup.sh

In RHEL 8.2, NetworkManager will ship with the nm-initrd-generator, but
before the install bits fall into place we want to default to network-legacy.
This unblocks the enablement of the NetworkManager bits and is intended
to be reverted later on.

[RHEL] network: default to network-legacy even in presence of nm-initrd-generator

---

dracut.cmdline.7.asc
dracut.conf.5.asc
dracut.usage.asc
modules.d/10i18n/console_init.sh
modules.d/10i18n/module-setup.sh
test/TEST-04-FULL-SYSTEMD/test.sh

Fedora and others have used eurlatgr as the default console font
for some time now, or suggested using it:
https://fedoraproject.org/wiki/Changes/NewDefaultConsoleFont
https://wiki.archlinux.org/index.php/Linux_console#Fonts
The Fedora Change page lists some of the benefits and this file
lists all the characters (glyphs) supported by the font:
http://git.altlinux.org/people/legion/packages/kbd.git?p=kbd.git;a=blob;f=data/consolefonts/README.eurlatgr
The notable downside is that the font does not support Arabic,
Cyrillic or Hebrew as LatArCyrHeb-16 (partially) does, so in cases
where support for languages using them is needed a non-default
console font should be used. Fedora, for instance, uses langtable
to decide the console font to use based on installation language: …

Use eurlatgr as default console font

---

modules.d/40network/net-lib.sh

busybox seems to not properly support this option,
and it can be be safely omitted or replaced
with piping the output through head.

net-lib: remove calls to ip with -oneline option

---

test/TEST-16-DMSQUASH/create.py
test/TEST-16-DMSQUASH/test.sh

This change still supports Python 2.6 and 2.7 but loses support
for Python 2.5.
The reason for this change was that Fedora 30 does not ship
python-imgcreate but ships python3-imgcreate.
Signed-off-by: Böszörményi Zoltán <zboszor@pr.hu>

Make TEST-16-DMSQUASH Python 3 compatible

---

modules.d/01systemd-initrd/module-setup.sh
modules.d/99base/module-setup.sh

I'd like to rework CoreOS Ignition (which runs in the initramfs)
to include some values from the *real* `/etc/os-release` in
HTTP headers.
Looking at this, it turns out dracut eats almost all of the useful
information from it.  I don't think `dracut` should be the `ID`
here...dracut's not an OS itself, it's a way to *build* little
operating systems.  It'd be kind of like if Fedora's Koji
injected itself into `/etc/os-release`.
This code dates back a long time; not sure of all the rationale
behind it.
I changed it so that we keep extending the VERSION/PRETTY_NAME
with the dracut version, but otherwise "pass through" the
rest of the real `/etc/os-release` we were built from unchanged.

99base: Rework `/etc/initrd-release` to derive from real os-release

---

modules.d/40network/net-lib.sh

Before we check if dad is done we should first make sure,
that there is a link local address where we do the check.
Due to this issue, on ipv6 only setups sometimes dhclient started
asking for ip address, before the link local address was present
and failed immediately.

net-lib: check if addr exists before checking for dad state

---

dracut-functions.sh

reason:when filter/global_filter is set in lvm.conf, lvm vgs may be
failed

dracut: check_vol_slaves_all must return 1 when lvm vgs failed

---

modules.d/99squash/module-setup.sh
modules.d/99squash/squash-mnt-clear.service

Currently it starts the cleaner early and do the clean up job if switch
root is called. It's better to just start the service only on switch
root to avoid any risk of service dependency failure and make is
simpler.

99squash: Only start the cleaner on switch-root

---

modules.d/35network-legacy/net-genrules.sh
modules.d/95iscsi/iscsiroot.sh
modules.d/95iscsi/parse-iscsiroot.sh

This rebases https://github.com/openSUSE/dracut/pull/7 on top of master.
https://github.com/openSUSE/dracut/pull/7/commits/354296ed1ae4c52191bb7955e5260756f7f6f2a6 is missing, since the node case has been removed in master by 7d0848957c0cb9f9796b7f4ec4941000bfaaf6fe. Unsure what to do for this one, @gonzoleeman.

dracut fixes for iscsiroot

---

modules.d/90ppcmac/load-thermal.sh
modules.d/90ppcmac/module-setup.sh

The goal of this module is to enable automatic loading of the thermal/fan control modules on PowerPC based Macs (usually G5, which use the `windfarm` infrastructure), as on some modular kernel configurations this will not happen automatically which will result in the fans spinning up to 100% until they are manually loaded.
This is especially a problem in live systems where it takes some time to boot up and the spin-up happens before the system even leaves initramfs, but even on normal systems this is generally beneficial, as it means the modules are correctly loaded automatically.
This is inspired by a similar `thermal` hook in Debian's initramfs-tools, though it has been written from scratch for `dracut` and today's kernels (effectively 2012+, the Debian hook still loads `therm_p72` for …

modules.d: add a module for early fan control on PowerPC Macs

---

dracut.spec
modules.d/00mksh/module-setup.sh

Add support for MirBSD™ Korn Shell, an actively developed free implementation of the Korn Shell programming language and a successor to the Public Domain Korn Shell (pdksh).
http://www.mirbsd.org/mksh.htm
@haraldh please review

add mksh support v2

---

modules.d/95iscsi/module-setup.sh

Fixes these error messages during intird build:
cat: '/sys/devices/platform/host2/flashnode_sess-*/is_boot_target': No such file or directory
/usr/lib/dracut/modules.d/95iscsi/module-setup.sh: line 91: [: -eq: unary operator expected
cat: '/sys/devices/platform/host3/flashnode_sess-*/is_boot_target': No such file or directory
/usr/lib/dracut/modules.d/95iscsi/module-setup.sh: line 91: [: -eq: unary operator expected

iscsi: fix error messages with iSCSI root

---

modules.d/90livenet/livenetroot.sh

When we are using livenetroot image, we want dracut to try until it succeeds. Current setup will have the node fail to boot if there are transient network issues on the first failure. This patch will make it try forever which is usually long enough for transient issues to get worked out.

retry image download forever

---

dracut.sh

Intel has notified us that some microcode updates are not safe
to be applied during runtime. To accomodate for that, microcode
files shipped by SUSE and openSUSE have an '.early' postfix such
that triggering
/sys/devices/system/cpu/microcode/reload
from a booted system cannot pick up the ucode by accident, while
still allowing the code to be picked up during initrd time.
This change is needed to make this scheme work also in a hostonly
situation.
Currently, this affects only 06-4f-01, which is now 06-4f-01.early.
If a distro does not change the filename, the behavior does not
change.
Reference: osc#1098915

ucode: properly include early only ucode

---

modules.d/01fips/fips-boot.sh
modules.d/01fips/fips-noboot.sh

If you boot system with `fips` and not `fips=1` then you will get unary operator expected error. This will fix the problem.
Although it won't boot even after the patch but that is the same behavior as with `fips=1`, the error is fixed by this. It looks like fips on Fedora 30 and Rawhide is broken because of loop devices?
Tested also on Fedora 29 and it works correctly there.
Thanks @lnykryn for your help with this.

Fix boot with `fips` without a value

---

dracut.sh

Drop some unneeded metadata in the squash image, and print the error
message if something went wrong.

Fine tune mksquashfs options for squash module

---

modules.d/01fips/fips.sh

See individual commit messages for details. Though note none of these patches are actually specific to RHCOS and FCOS. I've also verified that I can boot up a traditional Fedora cloud server in FIPS mode with the patches.
More background information in:
https://github.com/coreos/fedora-coreos-tracker/issues/302

01fips: various fixes to adapt to RHCOS and FCOS

---

modules.d/95udev-rules/module-setup.sh

Include 70-persistent-net.rules (if present) in order to keep the persistent network device naming scheme on system upgrade.

keep network device naming scheme on upgrade

---

modules.d/35network-manager/nm-run.sh

commit 5e0f8c8a4ced ('network-manager: remove useless use of basename')
somewhat carelessly didn't take into account that $_i has a slash at
the end which made the result of the ## substitution be just an empty
string.
The slash was put to the end of /sys/class/net/*/ to make sure we're only
iterating directories, but it's not strictly necessary. In an unlikely case
something else than a directory appears in /sys/class/net/, we'll already deal
with it gracefully. Remove it.
This fixes the TEST-30-ISCSI test.

network-manager: fix getting of ifname from the sysfs path

---

test/TEST-50-MULTINIC/client-init.sh

Analogous to what commit 687e17aa7f2f ("network-manager: fix getting of
ifname from the sysfs path") fixes.

TEST-50-MULTINIC: fix how a basename is determined

---

test/TEST-20-NFS/server-init.sh
test/TEST-30-ISCSI/server-init.sh
test/TEST-31-ISCSI-MULTI/server-init.sh
test/TEST-40-NBD/server-init.sh
test/TEST-50-MULTINIC/server-init.sh
test/TEST-60-IFCFG/server-init.sh
test/TEST-70-BONDBRIDGETEAMVLAN/server-init.sh

The network interfaces appear asynchronously and sometimes just too late,
after we're already halfway throught server-init.sh:
+ ip link set dev eth0 name ens3
Cannot find device "eth0"
+ ip addr add 192.168.50.1/24 dev ens3
Cannot find device "ens3"
+ dhcpd -cf /etc/dhcpd.conf -lf /var/lib/dhcpd/dhcpd.leases ens3 ens5
...
[    8.040825] e1000 0000:00:03.0 eth0: (PCI:33MHz:32-bit) 52:54:01:12:34:56
[    8.047105] e1000 0000:00:03.0 eth0: Intel(R) PRO/1000 Network Connection
...
No subnet declaration for ens3 (no IPv4 addresses).
** Ignoring requests on ens3.  If this is not what
you want, please write a subnet declaration
in your dhcpd.conf file for the network segment
to which interface ens3 is attached. **
Whoopsie. Let's ensure all the interfaces are there before we proceed
fiddling …

TEST-{20,30,31,40,50,60,70): wait for server interfaces to come up

---

test/TEST-20-NFS/99-default.link
test/TEST-20-NFS/test.sh
test/TEST-50-MULTINIC/99-default.link
test/TEST-50-MULTINIC/test.sh
test/TEST-60-IFCFG/99-default.link
test/TEST-60-IFCFG/test.sh
test/TEST-70-BONDBRIDGETEAMVLAN/99-default.link
test/TEST-70-BONDBRIDGETEAMVLAN/test.sh

New systemd defaults to generating MAC addresses for software devices (whereas
previously they would inherit them from the first enslaved slave).
Sadly, among the things this breaks is our test fixture, where the dhcp servers
are configured to expect a particular MAC address. Disable this for the
affected tests, which are essentially the ones that use bridges and bonds.

TEST-{20,50,60,70): set MACAddressPolicy=keep

---

.travis.yml

We're on Fedora 31 that should be good enough for this test.
This reverts commit 7a2503ab8cec9473ad6dacf4f48b17344219f3c0.

Revert "travis: run TEST-14-IMSM on Fedora 29"

---

modules.d/95ssh-client/module-setup.sh

The actual syntax of nsswitch.conf is slightly different from the
current regular expression:
- A comment can appear anywhere, not just at the beginning of a
line.
- Action items take the general form [STATUS=ACTION] or
[!STATUS=ACTION] (with some optional whitespace).
- A service name cannot include a colon. This is a nitpick,
because there should never be more than a single colon per
line.
Signed-off-by: Petr Tesarik <ptesarik@suse.com>

95ssh-client: improve nsswitch.conf parser

---

modules.d/01fips/module-setup.sh

Add cts, Linux-5.0 commit:
* 196ad6043e9f ("crypto: testmgr - mark cts(cbc(aes)) as FIPS allowed")
Linux 4.20 commits for 'ofb' (FIPS allowed too):
* dfb89ab3f0a7 ("crypto: tcrypt - add OFB functional tests")
* e497c51896b3 ("crypto: ofb - add output feedback mode")
Signed-off-by: Alexey Kodanev <alexey.kodanev@oracle.com>

fips: add 'ofb' and 'cts' block cipher modes

---

modules.d/35network-legacy/ifup.sh

since we handle the retries explicitly via rd.net.dhcp.retry
Without -1 if user sets ip=dhcp6 and there is no dhcp on the network,
dhclient seems to wait indefinitely, ignoring rd.net.timeout.dhcp

network-legacy/ifup: dhclient should be started in oneshot mode

---

modules.d/35network-manager/module-setup.sh

We don't need `ip` but having it is *really* useful for people debugging
in an emergency shell.

modules/network-manager: Install `ip`

---

modules.d/01fips/fips.sh

Instead of carrying the kernel and hmac in the install.img (which takes
up more space) use the vmlinuz installed under /images/pxeboot/ and the
.hmac in the install.img /boot.
This check is triggered by the presence of /run/install/repo/images/pxeboot/vmlinuz
Related: rhbz#1782737

Check .hmac of boot.iso in fips mode

---

modules.d/35network-manager/nm-run.sh

NetworkManager would unnecessarily bring up the devices, colliding with
further attempts to rename the devices.
This is arguably a NetworkManager bug and should eventually be fixed there.
Running NetworkManager without the connection is unnecessary regardless.

network-manager: don't run NetworkManager when there are no connections

---

modules.d/95iscsi/module-setup.sh

Previous all files are installed with inst_dir, which will not install
the files under /etc/iscsi/, and it create folders with the same of the
files which is wrong.
Now only use inst_dir to install the config dir and ensure it
exists, and use inst_multiple to install the config files.

95iscsi: Fix /etc/iscsi installation

---

modules.d/35network-legacy/dhclient-script.sh

This is a simple trick to honor RFC 3442:
If the DHCP server returns both a Classless Static Routes option and
a Router option, the DHCP client MUST ignore the Router option.
Fixes #683 
Signed-off-by: Jacob Wen <jian.w.wen@oracle.com>

35network-legacy: using 'replace' instead of 'add' to add route

---

modules.d/00systemd/module-setup.sh
modules.d/01systemd-initrd/module-setup.sh
modules.d/02systemd-networkd/module-setup.sh
modules.d/06rngd/module-setup.sh
modules.d/90multipath/module-setup.sh
modules.d/90stratis/module-setup.sh
modules.d/95iscsi/module-setup.sh
modules.d/98dracut-systemd/module-setup.sh
modules.d/99squash/module-setup.sh

Replace manual creating of symbolic links via ``mkdir`` and ``ln`` with ``systemctl`` calls.
This patch also unify how symbolic links are created in ``module-setup.sh`` files. It might help new contributors with creating new dracut modules.

Replace ln with systemctl

---

modules.d/45ifcfg/write-ifcfg.sh

This patch should fix issue, where dns server were passed by parameter via cmd, but wasn't written to ifcfg file.
Resolve: rhbz#1767100

Write dns values passed by ip argument to ifcfg-* files

---

modules.d/90kernel-modules/module-setup.sh

If hostonly mode is in use, and there isn't any block device included
as hostonly device, then the initramfs won't need any block driver.
Eg. for kdump built image, there could be only one nfs mount point,
or the initramfs may only execute some network operation then reboot.
In such case, skip block driver installation to save space and time.

90kernel-modules: don't install any block driver if not needed

---

modules.d/35network-legacy/ifup.sh

Otherwise we won't retry dhclient again on that interface. In
FCOS/RHCOS, we want to bake in `ip=dhcp,dhcp6` so we automatically try
getting a DHCPv6 lease if DHCPv4 failed.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1793591

network-legacy/ifup: nuke pid and lease files if dhclient failed

---

dracut.sh

Some distributions ([Arch](https://wiki.archlinux.org/index.php/Microcode#Early_loading), [Gentoo](https://wiki.gentoo.org/wiki/Intel_microcode#Configuration)) ship prepacked microcode images. These are cpio images that follow the structure specified in the Linux kernel documentation ([`x86/microcode.rst`, "Early load microcode"](https://github.com/torvalds/linux/blob/master/Documentation/x86/microcode.rst#early-load-microcode)), the same structure dracut uses for its early microcode images.
In case of Arch Linux, the microcode for Intel CPUs is currently only available in this packed form, `/usr/lib/firmware/intel-ucode` does not exist. This commit adds a way to make use of these images on such systems by unpacking them to the early cpio directory. (Note that the packed image cannot be …

ucode: use microcode found in packed cpio images

---

dracut.sh
install/dracut-install.c

dracut, when passing --kmoddir, would only install modules that exist at
the same location as it will appear in the initramfs.
For most (possibly all) outputs, the output path would be /lib/modules,
so previously all kernel modules must be copied there or the module
installation silently fails.
Now use the original path variable, and install to the shortened path
variable (as calculated by kerneldirlen).
Note: This means that the argument to --kmoddir (and the modules filetree)
should be a directory that ends in 'lib/modules/$kernelversion'.

dracut-install: fetch kernel modules from kmoddir

---

dracut.cmdline.7.asc
modules.d/40network/net-lib.sh

On some devices kernel currently takes 5.2 seconds to detect carrier,
so let's make the default in dracut bit more sensible.
See also https://bugzilla.redhat.com/show_bug.cgi?id=1772010

40network: bump rd.net.timeout.carrier to 10 seconds

---

modules.d/35network-legacy/dhclient-script.sh

new_domain_name_servers and new_domain_search is only provided vit IPv4
see: https://src.fedoraproject.org/rpms/dhcp/blob/HEAD/f/dhclient-script#_148

dhclient-script: ipv6 uses different variables for nameservers

---

modules.d/40network/net-lib.sh

This reverts commit c603419030136570b5944dc4620f62d07b9e82bb.
wait_for_ipv6_dad_link is only called from dhclient script,
so the original intent "wait for IPv6 RA if using none/static IPv6 assignment"
does not seem to be correct.
Anyway, this brings an issue on isolated networks, where you don't
have any routes outside. dhclient-script hangs on this check
and after it times out, dhclient is able to set the address normally.

Revert "wait for IPv6 RA if using none/static IPv6 assignment"

---

dracut.cmdline.7.asc
modules.d/40network/net-lib.sh

Added boolean command line option rd.iscsi.mp
I have dual port Intel 10-Gigabit X540-AT2 and wanna boot my server from iscsi.
I tried to use iBFT to automatic interface configuration (as a sysadmin i'm a bit lazy) but it configures only one interface, thus multipath is not working.
cat /sys/firmware/ibft/ethernet*/flags
3
1
In network/net-lib.sh we have
(( $flags & 2 )) || continue
which completly excludes second nic port from ibft auto configuration.

network/net-lib.sh: Configure all iBFT interfaces

---

dracut.8.asc
dracut.conf.5.asc
dracut.sh

Support the EFI Stub loader's splash image feature.
Checks if `uefi_splash_image` exists in `dracutsysroot` if not unset
`uefi_splash_image`. Alternate Value parameter expansion adds section-vma
for splash image to EFI stub loader when the path to image is valid and
not an empty file.
I did not test on other distributions, but on Arch Linux the `systemd`
package includes a splash image at the path
`/usr/share/systemd/bootctl/splash-arch.bmp`. Perhaps, if this is a
common practice, a default image could be gathered from that directory.
It is required that the image be in bitmap (`.bmp`) format according to 
`splash.c`.
The code for `stub.c` and `splash.c` can be found at:
https://github.com/systemd/systemd/blob/master/src/boot/efi/stub.c …

Support the EFI Stub loader's splash image feature.

---

modules.d/35network-legacy/ifup.sh

Previously, we were doing `setup_net` from `ifup` for any setup that
wasn't DHCP, since those are already taken care of by `dhclient-script`.
The issue is that the case-statement we use to detect this doesn't catch
options like `ip=dhcp,dhcp6`.
Fix this by reworking the logic here to just check if a
`setup_net_$netif.sh` hook exists. If so, then we know that `setup_net`
will be called for this interface later.
This was causing issues in RHCOS which now ships with `ip=dhcp,dhcp6` to
support IPv6 environments[1]. The code here would make us do `setup_net`
pre-emptively which IIUC would then cause the initqueue to finish
earlier even if we had more udev netif events to process.
[1] coreos/coreos-assembler#1067
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1803926

network-legacy/ifup: fix ip=dhcp,dhcp6 setup_net logic

---

modules.d/80cms/cmssetup.sh

Followup to a8ba1c4e25051c3c482bb7a6a754c9d785463917

cms/cmssetup.sh: use $name instead of $env{INTERFACE}

---

fedora-test-github.sh

GitHub workflows fetch a clone of the dracut repository which doesn't
contain git tags, thus "breaking" the RPM build in certain situations
i.e.:
DRACUT_MAIN_VERSION in Makefile is defined as an output of `git describe`,
which in full git clone returns a tag with a numeric version. However,
without tags it returns SHA of the last commit, which later propagates into
`Provides: `attribute of the built RPM and can break dependency tree when
installed
---
This caused two issues:
```
/var/tmp/dracut-test.cfXQz4/dracut-a902d6a947e02b1dcbbb24e5f02f9e29e9b57955-1.fc30.src.rpm
...
++ cp --reflink=auto -a '/var/tmp/dracut-test.cfXQz4/dracut-[0-9]*.x86_64.rpm' '/var/tmp/dracut-test.cfXQz4/dracut-network-[0-9]*.x86_64.rpm' /var/tmp/dracut-test.cfXQz4/root//var/tmp/dracut-test.cfXQz4/
cp: cannot stat …
```

github: fetch git tags before testing

---

modules.d/95fcoe/fcoe-genrules.sh

Followup to a8ba1c4e25051c3c482bb7a6a754c9d785463917 and 11a5501d0f844b9e52f2f1b62d980b733c73f10a
---
Hopefully the last `$env{INTERFACE}`-related change, managed to completely overlook this one...

fcoe/fcoe-genrules.sh: use $name instead of $env{INTERFACE}

---

modules.d/90stratis/module-setup.sh

Change start script order to pre-mount as stratis require fully initialized udev.

stratis module: fix start script order

---

dracut.sh

If the temporary directory for images is mounted with 'noexec', dracut
may construct unbootable images because most dynamic libraries aren't
installed. Avoid this by using user's $TMPDIR as default temporary
directory and by clearly erroring out if if the temporary directory is
mounted with 'noexec'.
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

Use $TMPDIR and error out if tmpdir is mounted with 'noexec'

---

install/dracut-install.c

Dracut currently fails to create directories if two or more parent directories do not exist:
```
dracut-install: ERROR: failed to create directory '/Data/Variable/tmp/dracut.JwT7Fw/initramfs/usr/lib/udev'
dracut-install: ERROR: installing '/usr/lib/udev/rules.d'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /Data/Variable/tmp/dracut.JwT7Fw/initramfs -d /usr/lib/udev/rules.d
```
This patch fixes that by creating intermediate parent directories when they don't exist.

dracut_mkdir(): create parent directories as needed.

---

lsinitrd.sh

Debian mkinitramfs does not create the file 'early_cpio', so detection
of additional cpio images fails and only the first cpio is listed.
I checked some Arch and Gentoo initramfs files and these didn't have
'early_cpio' either, but they also have only one cpio part.
Fix this so that if check for 'early_cpio' fails, check if directory
'kernel' (as part of '/kernel/x86/microcode') exists.
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

Make lsinitrd usable for images made with Debian mkinitramfs

---

modules.d/90crypt/crypt-run-generator.sh
modules.d/90crypt/module-setup.sh

systemd provides its own cryptsetup facilities, and the
cryptsetup binary might not even exist, failing
to execute the discard flag processing.
Fixes #602

Do not call cryptsetup in a systemd environment

---

modules.d/90kernel-modules/module-setup.sh

Currently there is no usb support on RPi4 in the
initrd phase as the pcie-brcmstb module is missing.
If part of the boot is handled from a USB stick
(e.g. with Ignition), the stick cannot be accessed.
Reference: boo#1162669

90kernel-modules: Add PCI host controller modules

---

modules.d/50drm/module-setup.sh

DRM drivers are filtered for drm_crtc_init symbol,
but not all drivers use it. Especially, cirrus driver
doesn't use it since Linux 5.2.
The practical result is text plymouth theme instead of graphical when in qemu.
Fix it by looking also for drm_dev_register symbol.
Suggested by @haraldh
Fixes #712

Consider also drm_dev_register when looking for gpu driver

---

Makefile

With GNU Make 4.3 on both ArchLinux, and VoidLinux,
GITVERION is always empty because of bad substitution.
Change '\\#' to simply '#' can fix it,
but we don't need that complication.
We can merge DRACUT_MAIN_VERSION and GITVERSION into DRACUT_FULL_VERSION.
Because, GITVERSION will be attached back to DRACUT_MAIN_VERSION in all
situation.
While we're at it, detect if we're in git worktree by:
limiting GIT_CEILING_DIRECTORIES to parent directory of
dracut's top level directory; instead of checking for .git directory,
in order to support git-worktree, in such case, .git will be a file, see
gitrepository-layout(5)

Makefile: merge main-version and git-version earlier

---

modules.d/95nfs/parse-nfsroot.sh
modules.d/99base/dracut-lib.sh

It already lives in nfs-lib.sh, which is the more correct library scope.
Fixes #17

99base: Remove duplicate nfsroot_to_var from dracut-lib.sh

---

dracut.sh

dracut.sh already doesn't call fsfreeze if the output file is on
the root file system. For btrfs, however, this is not sufficient.
Because fsfreeze is a superblock operation, and all btrfs subvolumes
share the same superblock, fsfreeze may freeze the entire system
if the subvolume on which the output file is written and / are
subvolumes of the same file system. Avoid this by comparing file
system UUIDs for btrfs.
This should fix https://github.com/dracutdevs/dracut/issues/398.
Fixes: de576db3c225 ("call fsfreeze(8) on /boot to flush initramfs data & metadata to media")

dracut.sh: don't call fsfreeze on subvol of root file system

---

dracut.sh

Use environment variable TMPDIR (typically /run/user/$UID) as default
temporary directory, if available. This should be more private
location than /var/tmp. Path specified with --tmpdir is takes
precedence over TMPDIR and /var/tmp is still used as last resort if
neither TMPDIR is set nor --tmpdir is used.
Signed-off-by: Topi Miettinen <toiwoton@gmail.com>

Use TMPDIR if available

---

Makefile

The variable is not undefined anymore after the first assignment, so
we should check if variable is empty instead.

Makefile: fix VERSION again

---

modules.d/95fcoe/lldpad.sh

Using exit makes the pre-trigger stage finish after running 03-lldpad.sh
pre-trigger hook.

Fix pre-trigger stage by replacing exit with return in lldpad.sh

---

modules.d/95fcoe/lldpad.sh
modules.d/95fcoe/parse-fcoe.sh

rd.nofcoe should default to false, e.g. fcoe should be enabled unless
overwritten from the command line.
The same applies for lldapd.sh.

95fcoe: default rd.nofcoe to false

---

modules.d/90btrfs/module-setup.sh

fixes https://github.com/dracutdevs/dracut/issues/658
raid6_pq and xor takes time doing benchmarking
[    3.983009] request_module fs-btrfs succeeded, but still no fs?

btrfs: force preload btrfs module

---

modules.d/35network-manager/nm-config.sh
modules.d/35network-manager/nm-run.sh

The network-manager command line hook must install a
initqueue/finished hook to ensure that nm-run.sh is executed when
there are network connections to activate.
Fixes: #694

network-manager: ensure that nm-run.sh is executed when needed

---

modules.d/95dasd/module-setup.sh

`dasd.conf` needn't be present on system even if modules have been loaded.
Check if file exists to avoid error message during kernel update
```bash
dracut-install: ERROR: installing '/etc/dasd.conf'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.YvVRx5/initramfs -H /etc/dasd.conf
```

dasd: only install /etc/dasd.conf if present

---

modules.d/35network-legacy/dhclient-script.sh

No bonding going on here.
Signed-off-by: Patrick Talbert <ptalbert@redhat.com>

dhclient-script: Fix typo in output of  BOUND & BOUND6 cases

---

modules.d/45url-lib/module-setup.sh

curl no longer depends on NSS now in Fedora or RHEL, let's stop pulling it in

url-lib: drop NSS, curl no longer depends on it

---

dracut.cmdline.7.asc
modules.d/90multipath/module-setup.sh
modules.d/90multipath/multipathd-configure.service
modules.d/90multipath/multipathd.sh

Add support for 'rd.multipath=default' for using the default
configuration on boot. The intended purpose for this is to help support
ostree-based image boots from multipathed devices (such as Fedora and
Red Hat CoreOS).

multipath: add automatic configuration for multipath

---

test/TEST-99-RPM/test.sh

file /etc/dnf/modules.d/eclipse.module.rpmmoved is not owned by any package

TEST-99: exclude /etc/dnf/* from check

---

dracut.cmdline.7.asc
modules.d/95znet/parse-ccw.sh

qeth device may have a different IP for each boot, so the rd.ifname=
option will no longer work. So for znet device, introduce a
rd.znet_ifname= options, to subchannel id instead of MAC address as the
identifier and rename the interface.

95znet: Add a rd.znet_ifname= option

---

modules.d/90nvdimm/module-setup.sh

This is necessary to actually unlock NVDIMM keys during boot.

90nvdimm: include nvdimm keys in initrd

---

modules.d/99base/dracut-lib.sh

According to [POSIX.1-2017, 2.6.2 Parameter Expansion](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02):
> *${parameter%<b>[</b>word<b>]</b>}*
> [...] The *word* shall be expanded to produce a pattern.
This means if word contains variables that itself contain special characters like asterisks or backslashes, these are treated as pattern characters unless the variable is quoted. Try e.g. the following example in bash, dash or (busybox) ash:
```
i='a\c'; j='\'; echo "${i%$j*}"
```
This prints `a\c` because `$j*` is expanded to `\*`, escaping the asterisk. In contrast,
```
i='a\c'; j='\'; echo "${i%"$j"*}"
```
produces the expected result `a` because the backslash is not specially treated any more after quoting.
The quotes that this commit adds have …

dracut-lib.sh: quote variables in parameter expansion patterns

---

modules.d/10i18n/module-setup.sh

/etc/vconsole.conf must be installed always, even in generic initrds, not only host-only ones.
systemd-vconsole-setup is run at initrd stage and expects either /etc/vconsole.conf or kernel cmdline options to exist.
I have also proposed a change in systemd-vconsole-setup that makes it behave better if /etc/vconsole.conf does not exist:
https://github.com/systemd/systemd/pull/15479
But it is just a fallback. If /etc/vconsole.conf does not exist in initrd and if that patch is applied on systemd,
then the default consoel font is set despite the one being set in /etc/vconsole.conf and this setting is inherited
when new TTYs are opened. This leads to full ignorance of settings in /etc/vconsole.conf.
It is incorrect, and that is why this file must be copied to initrds always, but not only on …

i18n: Always install /etc/vconsole.conf

---

modules.d/00systemd/module-setup.sh

Fixes: https://github.com/dracutdevs/dracut/issues/795

systemd: skip dependency add for non-existent units

---

modules.d/35network-manager/module-setup.sh

Install libnss_dns.so and libnss_mdns4_minimal.so plugins for the Name
Service Switch (NSS) functionality of glibc so that name resolution
through /etc/resolv.conf and mDNS works in the initrd.
Fixes: #772
Rebase of https://github.com/dracutdevs/dracut/pull/774

network-manager: install libnss DNS and mDNS plugins

---

modules.d/35network-manager/module-setup.sh

So far machinery is only pulled in if the user has not yet included any ifcfg files.
Noticed when boot failed after changing my custom module's prefix to be loaded before other modules.
The current code contradicts the code and depends on when user decides  to add ifcfg files.
I therefore believe that it would be better to simply always pull in the required library.

Always pull in machinery to read ifcfg files

---

modules.d/90btrfs/module-setup.sh
modules.d/90crypt/module-setup.sh
modules.d/90kernel-modules/module-setup.sh

We don't want to play catch up with hash and encryption algorithms.
To be safe, just use the hammer and include all crypto.
Fixes https://github.com/dracutdevs/dracut/issues/802

Install crypto modules in 90kernel-modules

---

modules.d/90crypt/module-setup.sh

If a crypto kernel module changes from compiled in to module, the
encrypted disk might fail to open, because the kernel module was
not included in the initramfs.
This patch tries heuristically to catch such modules.
Fixes https://github.com/dracutdevs/dracut/issues/706

90crypt/module-setup.sh: try to catch kernel config changes

---

modules.d/90kernel-modules/module-setup.sh

Fixes udevd messages about failure of `modprobe -bv sg`.

90kernel-modules/module-setup.sh: add sg kernel module

---

modules.d/90crypt/module-setup.sh

The first line in crypttab with a `force` option causes all subsequent lines to be included as if they also had it set because the variable used to track it is not reset between loop iterations.  So fix that by just setting it to empty before the check for the force option.

90crypt/module-setup.sh: fix force on multiple lines

---

lsinitrd.sh

If `$uefi` is empty, this evaluated to true previously,
resulting in `initrd in UEFI: : 13M`.

Fix test in lsinitrd

---

modules.d/06rngd/module-setup.sh

By default rng-tools are compiled with pkcs11 support.
Make sure opensc-pkcs11.so library is installed inside initramfs to prevent error on boot

rngd: install dependant libs too

---

dracut.cmdline.7.asc

Fixes: https://github.com/dracutdevs/dracut/issues/816

dracut.cmdline.7.asc: clarify usage of `rd.lvm.vg` and `rd.lvm.lv`

---

modules.d/35network-manager/nm-run.sh

Since commit ff70adf873ef ("initrd: save hostname to a file in /run"),
the initrd generator of NetworkManager parses the hostname from 'ip='
options of the kernel command line and writes it to
/run/NetworkManager/initrd/hostname.
When that file exists, set the kernel hostname.
In presence of multiple hostnames in the command line, the last one
wins. Hostnames from command line always have precedence over ones
received through DHCP. This is a bit different from the legacy network
module that gives higher precedence to the hostname (from DHCP or
command line) of the last interface that is brought up, which depends
on the udev order.

network-manager: set kernel hostname from the command line

---

modules.d/95nfs/module-setup.sh
modules.d/95nfs/nfs-start-rpc.sh

Most rpc services are not needed for NFSv4, so skip these components
to save space. rpc.idmapd is still needed in case of
nfs4_disable_idmapping is set to 0.

95nfs: only install rpc services for NFS < 4 when hostonly is strict

---

modules.d/95iscsi/module-setup.sh

95iscsi: fix missing space when compiling cmdline args

---

dracut-init.sh
modules.d/01fips/fips.sh
modules.d/99base/dracut-lib.sh
modules.d/99base/init.sh

See https://bugzilla.redhat.com/show_bug.cgi?id=1804252.
RHEL-only
Resolves: #1846034

Adapt to the new udevadm version output

---

dracut.sh

On Fedora/RHEL, libcryto will verify both itself and libssl on start, if
libssl is missing, FIPS self test will fail. However libssl is not a
dependency of libcryto so dracut will not install it, unless some other
binary or library pulls it in. Systemd requires libssl, so in most cases
it just worked, but could fail in some corner cases where systemd is not
used.

Fips workaround for Fedora/RHEL

---

modules.d/91zipl/parse-zipl.sh

The zipl partition should not be mounted if SYSTEMD_READY=0 is set.
Otherwise booting issues with multipath will result.

91zipl: parse-zipl.sh: honor SYSTEMD_READY

---

modules.d/95iscsi/iscsiroot.sh

ipv6 addresses need square brackets, otherwise the iscsi discovery and log-in,
which adds the iscsi port after another colon will get confused and fail.

95iscsi: fix ipv6 target discovery

---

dracut.sh

This fixes two issues:
1) on non-x86 systems in non-hostonly config this would cause
an annoying warning on every initramfs generation
2) on non-x86 systems in hostonly config this would result in
early microcode not getting disabled

dracut.sh: fix early microcode detection logic

---

modules.d/90kernel-modules/module-setup.sh

Install pci_hyperv for SR-IOV devices on hyperv machines.

90kernel-modules: add pci_hyperv

---

modules.d/90ppcmac/module-setup.sh

respect `DRACUT_ARCH` like other modules, and 32-bit PowerPC Macs can possibly boot in LE mode (and there is some work undergoing), so don't exclude ppcle

90ppcmac: respect DRACUT_ARCH, don't exclude ppcle

---

mkinitrd-dracut.sh

Previously this would not catch ppc64le, now it does; same with i686.

mkinitrd-dracut.sh: use vmlinux regex for ppc*, vmlinuz for i686

---

dracut.sh

As far as I can tell, uname -m will never output ia32, only i386 or i686.

dracut.sh: fix ia32 detection for uefi executables

---

dracut-functions.sh
modules.d/95iscsi/module-setup.sh
modules.d/95nbd/module-setup.sh
modules.d/95resume/module-setup.sh

The iSCSI configuration is started after dracut checks for resume,
so we run into a timeout here. Additionally it's questionable if
resume on iSCSI makes sense (or is even supported on the platform),
so disable it for now.
References: bsc#999663
Signed-off-by: Hannes Reinecke <hare@suse.com>

95resume: Do not resume on iSCSI

---

modules.d/95nfs/nfs-lib.sh

NFS server provided by DHCP in next-server option has higher priority than DHCP-server itself.
RH Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1859513

Change the order of NFS servers during the boot

---

modules.d/35network-legacy/ifup.sh

combine code for "no ip option directed at our interface" and
"No ip lines default to dhcp"
correct evaluation of return code
fix application of "load_ipv6" call to ipv6 setup only

35network-legacy: simplify fallback dhcp setup

---

modules.d/40network/net-lib.sh

Infiniband MAC addresses have 20 octets.
Reference: bsc#996146

net-lib.sh: support infiniband network mac addresses

---

.github/labeler.yml

The new plugin does not seem to be as backward compatible with the previous plugin in use as it claimed hence I remove the broken bit.

Removing dracut entry not compat with new plugin

---

modules.d/90dmsquash-live/dmsquash-live-root.sh

osmin.img is no longer used by anaconda or generated by
livemedia-creator.  livecd-creator will soon drop it as well.
Removing this code will allow OverlayFS boots to proceed  when
osmin.img is present in the .iso image.

dmsquash-live-root: Remove obsolete osmin.img processing.

---

dracut.sh

- use [ ] instead of calling test manually, as most of the script is
doing.
- use quotes in hostonly_cmdline blocks, specially when dealing with the
conf files, whose names are set by users/system administrators
- uefi_splash_image was being assigned set to `${dracutsysroot}...`, which
is a variable that doesn't exist.
- we don't want the conditional to run the output of fsfreeze as
commands. Instead, we just need to know if any of the fsfreeze commands
failed.

dracut.sh: fix errors pointed out by shellcheck.

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/labeler.yml

This pull request fixes the UC in feature request template and a missing '-' in dracut install which caused incorrect label on PR
Fixes #

Fix Unicode and dracut install labeler

---

dracut.8.asc
dracut.sh

This pull request adds an excplicit `--version` parameter. Previously, the version was available as part of `--help` only.

dracut.sh: Add --version

---

dracut.cmdline.7.asc

dracut.cmdline.7.asc: fix typo

---

modules.d/50drm/module-setup.sh

1、refer to  PR in RHEL-8 branch (https://github.com/dracutdevs/dracut/pull/904).
2、fix graphics startup failure with the rhgb paramter in CentOS8.2

fix graphics startup failure with the rhgb paramter in CentOS8.2

---

modules.d/04watchdog-modules/module-setup.sh
modules.d/04watchdog/module-setup.sh

In some cases, user only want to include the watchdog module, not the
wdctl or any other userspace helper. For example, systemd have a
RebootWatchdogSec option that use watchdog to prevent reboot hangs. And
it can help prevent machines hangs when reboot directly within the
initramfs stage. So split the module installation to a standlone module.
Also when watchdog-module get included, install driver for all loaded
watchdog instaed of only install driver for active watchdog. Both
watchdog and watchdog-module return 255 in check(), so it's enabled only
when manually included, the watchdog may get configured/activated later.
Fixes #

04watchdog: split the watchdog module install

---

dracut.cmdline.7.asc
modules.d/90crypt/cryptroot-ask.sh
modules.d/90crypt/parse-crypt.sh

Add optional prefix `keysource:` for the values of `rd.luks.partuuid`,
`rd.luks.serial` and `rd.luks.uuid`.
If specified, ask for passphrase instead of waiting for keydevs to come
online.
This makes it possible to use an encrypted *keydev* with `rd.luks.key`.
The `keysource:` keyword essentially marks an `rd.luks.partuuid` / `rd.luks.serial` / `rd.luks.uuid` argument as always-ask-for-passphrase. Without it, and with `rd.luks.key` specified, dracut would wait for an appropriate key entry to appear in `/tmp/luks.keys` (which won't happen) until timeout, resulting in the asking-for-passphrase fallback for all devices.
What I'm not yet sure about is if the priority of 31 for a generated `cleanup`-hook is appropriate (another cleanup hook of the module uses 30-*). It seems to work fine for me …

90crypt: make `rd.luks.key` usable with encrypted keydev.

---

dracut.spec

Fix the following:
```
$ make rpm
...
RPM build errors:
Installed (but unpackaged) file(s) found:
/usr/lib/dracut/modules.d/04watchdog-modules/module-setup.sh
```

dracut.spec: include the 04watchdog-modules module

---

modules.d/90kernel-modules/module-setup.sh

Some SoCs now have drivers that user devfreq in early init and fail
if the drivers are missing so make sure we have them in the initrd.
Signed-off-by: Peter Robinson <pbrobinson@gmail.com>
kernel modules in initrd
Fixes #
Some arm devices that have GPU drivers that use devfreq for scaling

Include devfreq drivers in initrd

---

modules.d/50drm/module-setup.sh

This pull request adds support for checking platform bus for modalias used by hostonly mode for drm drivers.
- Fix ambiguous redirect related to space in variable.
- Iterate over modalias from plaform bus 
- Add drm_encoder_init to the computation for drm drivers related to display.

50drm hostonly support for platform bus

---

install/dracut-install.c

If there are any nonexistent libraries listed in /etc/ld.so.preload, ldd
prints error messages like:
ERROR: ld.so: object '/usr/lib64/libfoo.so.1' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
This causes resolve_deps() to return error, which leads to symlinks
(like usr/bin/awk) not being copied into the initrd.
Fixes #

dracut-install: ignore bogus preload libs

---

install/dracut-install.c

This was introduced with 6dafdda4a6bdb8721133e4267553c5d86564f9e8, but
is actually caused by the fact that modules that have already been
installed cause dracut_install() to return without adding the module
to the hashmap. This can happen if an earlier-run dracut module chose
to install the same module. Now modprobe statements like:
softdep usb_storage post: uas
softdep uas pre: usb_storage
(which look weird, but are perfectly valid), cause
dracut_install() to enter an infinite recursion if and only if
at least one of the files has previously been installed by another
module.
Fix this by also adding already installed modules to the hashmap.

dracut-install: fix edge-case regression with weak modules

---

dracut.cmdline.7.asc
modules.d/95nvmf/95-nvmf-initqueue.rules
modules.d/95nvmf/module-setup.sh
modules.d/95nvmf/nvmf-autoconnect.sh
modules.d/95nvmf/parse-nvmf-boot-connections.sh

This pull request reworks the FC-NVMe connection handling. The original design of creating custom systemd services on the fly and activate them via udev doesn't work in the initrd due to the lack of dbus.
This patchset reworks the connection handling by using initqueue jobs to establish the initial connections.
Also the manpage is updated to document the nvmf commandline options.

95nvmf: rework FC connection handling

---

modules.d/00systemd/module-setup.sh

We want these in the initramfs. Things related to clevis and systemd's
`cryptsetup-generator` reference these targets.

00systemd: add missing cryptsetup-related targets

---

modules.d/90crypt/module-setup.sh

This is enabled upstream in
https://github.com/systemd/systemd/pull/17149.

90crypt: pull in remote-cryptsetup.target enablement

---

modules.d/95rootfs-block/module-setup.sh

Some filesystem (e.g. ZFS, and btrfs subvolumes) don't use block
devices. Should they be mounted as `/`, `find_root_block_device`
yields nothing, hence dracut will append this problematic argument
to kernel cmdline:
root=/dev/block
On a machine that employ root ZFS on LUKS, which was setup with
an OpenPGP-encrypted key file, this argument renders that machine
unbootable. Remove that `root=/dev/block` manually could boot the
machine.
Let check if that device is a block device before write down `root`
argument. This is consistent with the check for block device in
`find_block_device`.
Signed-off-by: Đoàn Trần Công Danh <congdanhqx@gmail.com>
---
- rootfs-block: only write root argument for block device

rootfs-block: only write root argument for block device

---

modules.d/90kernel-modules/module-setup.sh

In the case of the s805x the drivers/hwmon directory contains the
scpi_hwmon kernel module.
On a running system, lsmod would output the following dependencies:
arm_scpi               24576  2 clk_scpi,scpi_hwmon
It means that if the clock driver is bundled in the initramfs it will
bring arm_scpi. But if scpi_hwmon is missing the scpi will be incomplete
and it can lead to crashes.
When the hwmon is bundled, no crash occurs
Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>
Fixes #

90kernel-modules: arm: add drivers/hwmon for arm/arm64

---

modules.d/90crypt/cryptroot-ask.sh

dracut feeds whatever it receives in password field of
crypttab(5) to `cryptsetup -d`, treating them as plain-text key file.
Meanwhile, dracut treats the key file from `rd.luks.key` differently,
by have some special rules to decrypt those key files that has extension of
`gpg` and `img`.
Let's begin to treat them the same.
This is a backward-incompatible change for those people
that uses plain-text key-file that has extension of `gpg` and `img`.
However, those setup is questionable to begin with.
---
*backward-incompatible*:
- TESTED: key-file that ends with gpg will be decrypted by gnupg before feeding into `cryptsetup`
- NOT-TESTED: key-file that ends with img will be decrypted before feeding into `cryptsetup`
Fixes #

[RFC] cryptroot-ask: unify /etc/crypttab and rd.luks.key

---

modules.d/98dracut-systemd/rootfs-generator.sh

This is a plain and simple hack around dependency issues between dracut
and systemd.
When using Tang-pinned LUKS root devices, we want to rely on
`systemd-cryptsetup@.service` to unlock it. However, that service only
runs `After=remote-fs-pre.target`, while `dracut-initqueue.service` has
`Before=remote-fs-pre.target` (which makes sense because we don't want
to attempt networked root devices before networking is up).
However, the rootfs-generator here wants to make sure that the root
device exists *before* exiting the initqueue via an initqueue/finished
"devexists" hook. This will never work though because by design
`systemd-cryptsetup@.service`, which unlocks the root device, won't run
until after we exit.
So we have a dependency cycle:
initqueue -> devexists hook -> root device -> …

98dracut-systemd: don't wait for root device if remote cryptsetup active

---

modules.d/99memstrack/memstrack-report.sh
modules.d/99memstrack/module-setup.sh

/usr/local/bin causes trouble for distros that do not use /usr/bin == /bin
/usr/bin/env likewise, plus the use of env is not needed here

99memstrack: use /bin/bash

---

modules.d/90dmsquash-live/iso-scan.sh

With commit 3c8c807, `/run/initramfs/isoscan` and `/run/initramfs/live`
mountpoints are unmounted upon `rd.live.ram` boots.
Save a reference link to the iso-scan device in `/run/initramfs/isoscandev` to easily remount
the source, if desired.
- [] I have reviewed and updated any documentation if relevant
- [] I am providing new code and test(s) for it
Fixes #

dmsquash-live/iso-scan: Provide an easy reference to iso-scan device.

---

modules.d/00systemd/module-setup.sh
modules.d/90crypt/module-setup.sh

This was added in https://github.com/systemd/systemd/pull/17149 and is
the designated cryptsetup target for all encrypted volumes that need to
be opened in the initrd.
So it effectively replaces `cryptsetup.target` and
`remote-cryptsetup.target` there. I've removed the latter since it was
added recently (by me) in #930, but kept `cryptsetup.target` since we've
been shipping it for a long time now.

90crypt: ship initrd-cryptsetup.target

---

dracut.cmdline.7.asc
modules.d/35network-legacy/parse-team.sh

Cfr. [Bug 1881463 - [RFE] Requesting ability to configure the runner for team interfaces in dracut.cmdline/installations](https://bugzilla.redhat.com/show_bug.cgi?id=1881463)
Requesting the ability to configure the runners for a team interface similar to bond.
bond=<bondname>[:<bondslaves>:[:<options>[:<mtu>]]]
vs
team=<teammaster>:<teamslaves>
This impacts the ability of users to perform network installations when LACP is required. There is no way to get to stage2 and get the kickstart without configuring this first and we can't do it in dracut.
Added a parameter for configuring the runner and aligned the default values with bonding config:
team=<teammaster>:<teamslaves>[:<teamrunner>]
Setup team device <teammaster> on top of <teamslaves>.
<teamslaves> is a comma-separated list of …

Configure the runner for team interfaces

---

dracut.sh
modules.d/90kernel-network-modules/module-setup.sh

Introduce a --hostonly-nics param, with this param, if strict hostonly mode is used, it will only install driver for specified **NIC.000p**
Fixes #

Introduce a --hostonly-nics option

---

dracut-functions.sh
modules.d/04watchdog-modules/module-setup.sh
modules.d/40network/module-setup.sh
modules.d/90kernel-modules/module-setup.sh
modules.d/90qemu-net/module-setup.sh
modules.d/95nfs/module-setup.sh

Install less module for strict hostonly mode. Strict hostonly mode is used by kdump, which expect the initramfs to be as small as possible. 
Fixes #

Install less module for strict hostonly mode

---

modules.d/00systemd/module-setup.sh
modules.d/90crypt/module-setup.sh

This reverts commit 8f56daa8c3c75b167823286553f223e5b46cd6ab.
The addition of `initrd-cryptsetup.target` was reverted in systemd:
https://github.com/systemd/systemd/pull/17467

Revert "90crypt: ship initrd-cryptsetup.target"

---

modules.d/90multipath/module-setup.sh

This makes /dev/disk/by-uuid links point to the right device.
Fixes #

install kpartx's 11-dm-parts.rules for multipath

---

modules.d/90multipath/multipath-shutdown.sh
modules.d/98dracut-systemd/dracut-cmdline-ask.sh

dracutinstall picks up interpreters and includes bash despite
the users' wishes or expectations, as modules should not require
bashisms at runtime.
Fixes #951

Remove uses of bash (and bash specific syntax) in runtime scripts

---

modules.d/95cifs/module-setup.sh
modules.d/95nfs/module-setup.sh

Sometimes, systems have more elaborate backends in nsswitch.conf,
the complexity of which we do not want in the initrd. SUSE systems
with atomic for instance, where those files may also reside in /usr/etc.
With this change, the unavaiable nsswitch.conf backends will be silently
ignored, and we still end up with all the information we need.
Reference: boo#1165366

Retrieve service, rpc and protcol entries via getent

---

dracut-init.sh

dracut builds today are fairly verbose to start, but on top of
that many of the messages tend to liberally use the
exclamation point `!` which calls attention to them.
I see these a lot when looking at rpm-ostree build logs
and it'd be nicer if we were quiet when there wasn't
an actual problem.
In this specific case, if the builder is explicitly adding
`--omit=foo`, there's no reason for us to say:
`dracut: dracut module 'foo' will not be installed, because it's in the list to be omitted!`
We already print the command line to start, so the information
is there.
(Not tested locally)

Don't print when a module is explicitly omitted (by default)

---

configure

When LDFLAGS contains ``-Wl,--as-needed``, the FTS library will be
ignored if it is specified before the .c source.
Signed-off-by: A. Wilcox <AWilcox@Wilcox-Tech.com>
Fixes: 62f27ee6f145 ("configure: find cflags and libs for fts on musl")
Obsoletes #781. Code is identical, but rebased on top of master.

configure: Find FTS library with --as-needed

---

modules.d/99base/dracut-lib.sh

Library file `modules.d/99base/dracut-lib.sh` contains initialization code that makes sure certain directories and links are created when a system runs from the produced initramfs. This file is normally sourced only from initramfs scripts. However, `modules.d/99base/module-setup.sh` includes it also when an initramfs image is being created to gain access to some of the functions in this library. This can result in creating unexpected directories and links on the current root file system when the dracut command is executed.
For instance, during a system installation when dracut is invoked to create an initial initramfs, the target sysroot might not contain directory `/run/initramfs` but have `/var/log`. This situation results in the code in `modules.d/99base/dracut-lib.sh` creating an …

Prevent creating unexpected files on the host when running dracut

---

dracut-bash-completion.sh

This pull request completes the bash-completion script by supporting the positional arguments ` /usr/bin/dracut [<initramfs> [<kernel-version>]]`

dracut-bash-completion.sh: add positional argument completion

---

modules.d/95fcoe/module-setup.sh

If fcoe module is loaded, the initramfs will always try load libfcoe
and bnx2fc, so also ensure they are installed if needed.
Try install libfcoe and bnx2fc when 95fcoe is installed.

95fcoe: ensure needed modules are installed

---

modules.d/95fcoe-uefi/module-setup.sh
modules.d/95fcoe/module-setup.sh

When in hostonly mode, 95fcoe module will still be installed even there
is no FCoE hostonly device. So use the new block_is_fcoe helper to check
for hostonly device in hostonly mode, avoid installing unneccessary module.

95fcoe: don't install if there is no FCoE hostonly devices

---

dracut-bash-completion.sh
dracut.8.asc
dracut.conf.5.asc
dracut.sh

Closes #921
This pull request adds support for an `--uefi-output` command line parameter and an `uefi_output` configuration directive.

Add --uefi-output for custom output filename

---

dracut.spec
modules.d/06dbus/dbus-cleanup.sh
modules.d/06dbus/module-setup.sh
modules.d/35network-wicked/module-setup.sh
modules.d/35network-wicked/wicked-config.sh
modules.d/35network-wicked/wicked-run.sh
modules.d/40network/module-setup.sh

This introduces support for [wicked](https://github.com/openSUSE/wicked) as network management module.
Todo:

Support for wicked network manager

---

modules.d/90multipath/multipathd.sh

From shellcheck:
/usr/lib/dracut/modules.d/90multipath/multipathd.sh:3:32: warning[SC2039]: In POSIX sh, == in place of = is undefined.
/usr/lib/dracut/modules.d/90multipath/multipathd.sh:3:32: warning[SC2193]: The arguments to this comparison can never be equal.

multipathd: fix the comparison

---

modules.d/95cifs/module-setup.sh
modules.d/95nfs/module-setup.sh

The underlying issues this was trying to solve is to get a cheap
workaround for the fact that (open)SUSE with atomic support moved
/etc stock files to /usr/etc in order to improve compatibility. But
now that even nsswitch.conf moved, this is no longer enough. And it
might be more trouble to support once it's in an official release.
So let's rather drop it now.
This reverts commit e0524af2bf83184e18d068bea4356a719d2385c2.

Revert "Retrieve service, rpc and protcol entries via getent in hostonly mode"

---

.github/workflows/fedora-33.yml

To test a more recent version of Fedora, add Fedora 33.

ci: add testing with Fedora 33

---

modules.d/35network-manager/nm-run.sh

Force NetworkManager run only once in initrd.
- On EL8.3 the NetworkManager keep restarting even if it exits successfully while waiting for Clevis to unlock. This patch ensures NetworkManager runs only once in initrd.

fix(35network-manager): avoid restarting NetworkManager 

---

dracut.logrotate

Distribution have now switched to systemd which comes with it's own logging system called the journal which has a built in logrotation support hence there is no reason for a dracut to support traditional syslog utility like logrotate anymore thus removing...

chore(cleanup): remove logrotate file

---

dracut.8.asc
dracut.sh

Added --no-uefi option, which useful when you have uefi=yes in dracut config.

feat(cli): add --no-uefi option

---

lsinitrd.sh

Let's make lsinitrd work on distributions that support efi and follow the boot loader specification shall we...

fix: add a missing efi support

---

modules.d/90kernel-modules/module-setup.sh

Otherwise e.g. the xts(aes) implementation provided by the vmx_crypto
module (which does usually get included on ppc64le) fails to initialize
when xts is built as a module (CONFIG_CRYPTO_XTS=m), because it can't
instantiate the fallback generic xts(aes) implementation (needs the
generic xts module).
(see commit message)
- not sure if this can be easily tested, as it requires running a kernel with a specific config and some HW crypto driver that requires a fallback algorithm implementation

fix(90kernel-modules): install generic crypto modules with hostonly unset

---

modules.d/90kernel-network-modules/module-setup.sh

A recent change in Linux kernel v5.10 split the MDIO drivers from the PHY
subdirectory into a new MDIO subdirectory [0]. This caused MDIO drivers
to not be included in the initramfs.
Also include the modules of this new subdirectory to prevent this issue.
[0]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a9770eac511
Fixes #

fix(kernel-network-modules): also install modules from mdio subdirectory

---

.github/workflows/pr.yml

This should hopefully fix:
* not checking the PR github title
* not error on the auto merge commit message

ci: use our own version of commisery

---

modules.d/98dracut-systemd/dracut-pre-pivot.service

This pull request adds a shared keyring mode to dracut-pre-pivot.service as requested thus fixes #1007

fix(1007): adding shared keyring mode to type unit

---

skipcpio/skipcpio.c

because CPIO_END might follow a NULL byte in buf
This pull request changes `skipcpio` by replacing `strstr` with `memmem` in the logic that searches for the `TRAILER!!!` within the buffer that scans the given file. Using `strstr` will erroneously return a false negative if `NULL` byte precedes it within `buf`.
I note that the `memmem` function is specific to glibc. I also note that `_GNU_SOURCE` is already defined.

fix(skipcpio): "edit skipcpio.c strstr memmem"

---

dracut.conf.d/fedora.conf.example
dracut.sh
modules.d/01systemd-coredump/module-setup.sh

This pull request introduces the systemd-coredump module and adds a missing global variable ( systemdutilconfdir )

feat(systemd-coredump): introducing systemd-coredump module

---

modules.d/04watchdog/module-setup.sh

Fix error `/usr/lib/dracut/modules.d/04watchdog/module-setup.sh: line 10: return: watchdog-modules: numeric argument required`.

fix(watchdog-modules): numeric argument required

---

dracut.spec

939b7e11d introduced a new module, but it was not added to the spec file, which makes make rpm to fail.
- [ yep ] I have tested it locally
- [ nope ] I have reviewed and updated any documentation if relevant
- [ nope ] I am providing new code and test(s) for it

fix(spec): add new systemd-coredump module to spec

---

modules.d/90mdraid/65-md-incremental-imsm.rules
modules.d/90mdraid/md-shutdown.sh
modules.d/90mdraid/mdraid-cleanup.sh
modules.d/90mdraid/mdraid-waitclean.sh
modules.d/90mdraid/mdraid_start.sh
modules.d/90mdraid/module-setup.sh
modules.d/90mdraid/parse-md.sh

First commit adds missing service.
It is a background daemon. It is important to start it during raid assembly. It switches md array to rw mode.
Later process can be safety killed and restarted after switch root.
The second one is small improvement, see:
https://git.kernel.org/pub/scm/utils/mdadm/mdadm.git/commit/?id=3e23ba9d7bd3c2a9fbddc286014480672763e563
We shall avoid creating daemons from udevd context. Fork shall be killed unconditionally but I observe situation when booting hangs for a while (I didn't investigate it deeply). Adding service resolves the problems.

fix: mdraid improvements

---

dracut.cmdline.7.asc
modules.d/35network-legacy/dhcp-multi.sh
modules.d/35network-legacy/ifup.sh
modules.d/35network-legacy/module-setup.sh
modules.d/35network-legacy/parse-ip-opts.sh
modules.d/40network/net-lib.sh

We can drastically improve boot times on some machines, or BM or VM
shapes, if we send DHCP requests in parallel on all interfaces
Add ip=single-dhcp as a kernel boot parameter, to send DHCP requests in
parallel on all interfaces. Thus, DHCP on each interface is overlapped
thereby reducing boot times for multiple interface machines.
This can help reduce the boot time by 1 minute per interface.
In addition, we may also save another 40 secs delay per interface, if
the link on which we try to send DHCP is in DOWN state. This can be
reduced by giving the following kernel command line parameter while
booting - rd.net.timeout.carrier=<timeout>.
Added manpage for ip=single-dhcp with the caveat that it does not
apply to Network Manager or SUSE wicked.
Signed-off-by: Anjali Kulkarni …

feat(network-legacy): send dhcp in parallel on all devices

---

modules.d/95nfs/module-setup.sh

commit 5840c466d tried to make it create the right directory according
to the directory layout on current host, but added "$initdir" prefix
to the if statement by accident, so the installation code have no
effect now. Just fix it.
Fixes #

Fix NFS mount failure for NFSv3

---

modules.d/90kernel-modules/module-setup.sh

External Memory Controller drivers can be built as a module.
On Tegra, this allows tegra_drm to load faster and without defered probes,
instead of waiting for the rootfs for the tegra*_emc dependency.
Tested on jetson-tk1 and ac100.
Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>
Note: Building Tegra EMC drivers as a module is possible with mainline for 5.11+.

feat(kernel-modules): add drivers memory for ARM

---

dracut.8.asc
dracut.sh
install/dracut-install.c
modules.d/00systemd/module-setup.sh
modules.d/01systemd-initrd/module-setup.sh
modules.d/01systemd-sysusers/module-setup.sh
modules.d/02caps/module-setup.sh
modules.d/02systemd-networkd/module-setup.sh
modules.d/05busybox/module-setup.sh
modules.d/06dbus-daemon/module-setup.sh
modules.d/06rngd/module-setup.sh
modules.d/35network-manager/module-setup.sh
modules.d/35network-wicked/module-setup.sh
modules.d/50gensplash/module-setup.sh
modules.d/50plymouth/module-setup.sh
modules.d/90kernel-modules/module-setup.sh
modules.d/90lvm/module-setup.sh
modules.d/90multipath/module-setup.sh
modules.d/90nvdimm/module-setup.sh
modules.d/95fcoe/module-setup.sh
modules.d/95iscsi/module-setup.sh
modules.d/95udev-rules/module-setup.sh
modules.d/98dracut-systemd/module-setup.sh
modules.d/98syslog/module-setup.sh
modules.d/99memstrack/module-setup.sh
modules.d/99squash/module-setup.sh

The file pattern passed to inst_multiple (if not quoted) is immediately substituted by the shell.
When dracutsysrootdir is set and the same package is not installed on the host then the files are obviously not found on the host system. dracut-install complains loudly in this case.
This can also create an issue if the package versions on the build host and the cross-compiled system differ in their file lists. In this case the file list is generated according to the host and not according to the sysroot.
Found during a test build on Yocto with wicked added for testing.
Handle file globbing in `dracut-install`'s `install_all()` function.
Fixed modules that were using file globbing with inst_multiple: 35network-wicked, 90kernel-modules, 90nvdimm, 95fcoe, 95udev-rules
Also fixed the dbus …

sysroot fixes

---

modules.d/50plymouth/module-setup.sh

If plymouth is used then its own installation script is preferred.
While plymouth's own variant of inst_binary resolves the library
dependencies properly, its inst_library shell function doesn't
actually install them in some cases properly.
Make sure to install both the required binaries and their
dependencies. In the worst case, it's a NOP.
Signed-off-by: Zoltán Böszörményi <zboszor@pr.hu>
Fixes #

fix(plymouth): install binaries with dependencies

---

modules.d/90kernel-modules/module-setup.sh

Reset controllers might be needed by some of the devices used in the
initrd. Particularly on the Raspberry Pi 4, 'xhci-pci' depends on a
platform specific reset controller.
Signed-off-by: Nicolas Saenz Julienne <nsaenzjulienne@suse.de>

90kernel-modules: arm/arm64: Add reset controllers

---

dracut.cmdline.7.asc
modules.d/99shutdown/module-setup.sh
modules.d/99shutdown/shutdown.sh

When terminating a system, the shutdown module attempts to unmount all file systems from under `/oldroot`. This reaps remaining file systems that systemd cannot unmount and detaches `/oldroot` itself.
In case that running umount for some file system repeatedly fails, the module reports this error and continues the processing in order to shutdown the system. This handles a condition when the umount command actually terminates but it can happen in some cases that it waits indefinitely.
An example with NFS mounts:
```
Running as unit: run-r367825c967ca4d88a793ae4793c02f8b.service
```
The invoked tail command escapes normal termination by systemd and prevents stopping mnt-nfs.mount and mnt-nfs-dir2.mount as it makes the mounts busy. Systemd then again attempts to unmount these file systems in …

fix(shutdown): add timeout to umount calls

---

dracut.spec
modules.d/01systemd-modules-load/module-setup.sh

Introducing systemd-modules-load which is an early boot service
that loads kernel modules from a static list, which is required for
kernel modules that do for example not support automatic module loading
( like key type parsers ).
This is a standalone systemd module which means it depends on no other module than systemd.

feat(systemd-modules-load): introducing systemd-modules-load module

---

dracut.sh

Previously with `no_kernel` the `for` loop errored on the modules
wildcard. By checking, if the file exists, this is mitigated.
"mv" asked interactively, if aliased in the user session, so a "--force"
was added.

fix: correct the squash quirk

---

modules.d/01systemd-sysctl/module-setup.sh

Introducing systemd-sysctl module which is an early boot
service that configures sysctl.
The systemd-sysctl module has dependency's on systemd and
systemd-modules-load module.

feat(systemd-sysctl): introducing systemd-sysctl module 

---

modules.d/90dmsquash-live/dmsquash-live-root.sh
modules.d/95nbd/nbdroot.sh

Allows to use an nbd device exporting an squashfs image in a overlay setup.
- [  ] I have reviewed and updated any documentation if relevant
- [  ] I am providing new code and test(s) for it

Allow LiveOS image from a nbd device

---

modules.d/01systemd-ask-password/module-setup.sh

Introducing systemd-ask-password module which is used to query a
system password or passphrase from the user.
This module can be used standalone ( systemd-ask-password )
( which is without plymouth & wall support )
With plymouth module ( systemd-ask-password + plymouth )
With wall module ( systemd-ask-password + wall ), which is currently
commented out since there is no foreseeable usecase for it or even exiting
wall module.
This is a standalone systemd module which means it depends on no other module than systemd.
Fixes #

feat(systemd-ask-password): introducing systemd-ask-password module
